### ISSUE TITLE
Add to check_linux_load_normalized.pl total number of CPU

### ISSUE THREAD

**Issue by rmalenko** [HariSekhon/nagios-plugins#109]
Hi Hari,

Would you mind add to check_linux_load_normalized.pl total number of CPU to output in a graph? I mean I can see Load and Average but graphs does not have info about total CPU.

Regards,
Rostyslav

**Comment by HariSekhon** [comment]
Done. To maintain backwards compatibility use the ```-C / --cpu-cores-perfdata``` switch (this avoids breaking existing graphs for people who are using this with PNP4Nagios which breaks when the number of fields changes)

**Comment by rmalenko** [comment]
Thank you a lot!
