### ISSUE TITLE
check_kafka.py --acks bug

### ISSUE THREAD

**Issue by vanhove** [HariSekhon/nagios-plugins#110]
Hello,

I found an issue with the check_kafka.py file.
the file has the following entry: 
`self.add_opt('-a', '--acks', default=1, choices=[1, 'all']`

I think it should be:
`self.add_opt('-a', '--acks', default=1, choices=['1', 'all']`

The input parameter needs to be parsed as a string.

Kr

**Comment by HariSekhon** [comment]
Hi @vanhove 

Thanks for raising this. You're correct it's a minor type bug in the option parser definition that only affects if you explicitly request 1 ack, which is the default.

I've pushed a fix for it.

Thanks

Hari
