### ISSUE TITLE
check_nagiostats.pl: sanity checking is a bit too strict

### ISSUE THREAD

**Issue by cobaugh** [HariSekhon/nagios-plugins#115]
I have a working nagios configuration with hundreds of hosts and thousands of services where MAXACTSVCLAT + MAXPSVSVCLAT really is 0. I feel like there must be a better way to see if we got back what we were expecting. Perhaps just looking at NUMSERVICES and NUMHOSTS would be sufficient in almost all cases?

**Comment by HariSekhon** [comment]
I've just changed it to check that it's not negative instead, this should resolve it for you.

I'll close this ticket, but feel free to re-open it if needed.

Thanks

Hari
