### ISSUE TITLE
elasticsearch authorization

### ISSUE THREAD

**Issue by simpleuser99** [HariSekhon/nagios-plugins#122]
Hello. Your elasticsearch plugin monitoring very good. But my elastic have authorization (login and pass) and I don't understand how to check my elastic with your plugin.
Do you help me?

**Comment by HariSekhon** [comment]
What are you using for authentication, Marvel or authenticated proxy with basic http auth?

This will take me some time to get around to as I'm not working on elasticsearch any more and I'll have to adjust the test suites etc.

**Comment by simpleuser99** [comment]
I use x-pack authentification. https://www.elastic.co/guide/en/x-pack/5.0/index.html

**Comment by HariSekhon** [comment]
Ok I'll put this on the backlog to build a new env to represent this and then do the plugin updates, it'll take a few weeks to get back to this as I have higher priority things to do first that align with my current project.

**Comment by simpleuser99** [comment]
Thank you for information. I look forward to updates.

**Comment by matejzero** [comment]
I'm also using authentication on my cluster (Search Guard addon) with just a Basic Auth. Actually, both X-pack and Search Guard have an option to use Basic Auth (linked to LDAP or internal database), which is probably the easiest to implement and I guess quite widely used.

**Comment by simpleuser99** [comment]
@HariSekhon How is it going?

**Comment by HariSekhon** [comment]
I've been busy and haven't got time to even think about looking at this right now, sorry, life sometimes throws you unexpected curve balls :-/

I will get back to this at some point but it won't be very soon unless something changes.

**Comment by koma85** [comment]
Any news?

**Comment by HariSekhon** [comment]
@koma85

Sorry I know this is still outstanding, I've had some things come up outside of tech and have also been half way across the world in the last few months for work... I will get back to this but it'll take me a little while as my current 2 clients priorities do not align with this. I suspect it'll be nearer the end of year before I upgrade all the test suites, containers, library and top level changes and test it all. I don't think it's difficult at all but I need to focus on all the preceeding tasks to make sure it's done right.

**Comment by koma85** [comment]
I understand :)

**Comment by ted3** [comment]
PR for ES checks using SSL and/or username/password authentication:

https://github.com/HariSekhon/nagios-plugins/pull/174
https://github.com/HariSekhon/lib/pull/24

**Comment by HariSekhon** [comment]
Thanks very much @ted3.

I've merged in your changes and added some validation and version number increases and back tested all tests for all elasticsearch plugins against all versions of Elasticsearch and everything works nice.

I still need to add Elasticsearch security automated tests to test the new functionality but since it reuses the same mechanisms as the other plugins from lib it should just work.

I'll close this ticket now.

Cheers

Hari
