### ISSUE TITLE
check_ssl_cert.pl - openssl don't exists

### ISSUE THREAD

**Issue by Rohlik** [HariSekhon/nagios-plugins#126]
When I run this command `docker run --rm -ti harisekhon/nagios-plugins check_ssl_cert.pl -H google.com` with latest Docker image I get this error:
`UNKNOWN: couldn't find executable '/usr/bin/openssl': No such file or directory`

**Comment by HariSekhon** [comment]
Hi @Rohlik

Thanks for raising this, I've just added the dependency in explicitly as docker is a pretty stripped down environment, this is normally present on servers.

I've pushed the changes, please `docker pull` to get the updates and try again.

Thanks

Hari

**Comment by HariSekhon** [comment]
I'll close this ticket as I've tested it and added an auto CI test on this now but feel free to re-open it or raise another as needed.
