### ISSUE TITLE
for users who cannot clone git repo

### ISSUE THREAD

**Issue by eniniz** [HariSekhon/nagios-plugins#129]
Hi,
I cannot clone git repo (proxy issue) so I download the zip and run make but I get that error:
```
git submodule init
fatal: Not a git repository (or any of the parent directories): .git
make[2]: *** [submodules] Error 128
make[2]: Leaving directory `.../plugins/nagios-plugins-master'
make[1]: *** [common] Error 2
make[1]: Leaving directory `.../plugins/nagios-plugins-master'
make: *** [build] Error 2

```
how can I solve this problem

**Comment by HariSekhon** [comment]
@eniniz 

You need to copy the perl and python sub-library repos as listed in the Makefile and the Manual Build sections of the github page.

Be aware most of these programs need Python or Perl libraries as listed in the build sections but those are usually pulled from PyPI and CPAN respectively so if your environment's egress filtering doesn't even have exemptions for those widely used software repositories then you'll have trouble getting very far.

**Comment by eniniz** [comment]
thank you Hari for responding. 
my problem was that when I download the zip file (that contains the plugins ) I find that the lib file was empty, so I re-download and it works

**Comment by HariSekhon** [comment]
Surprising, I've downloaded it before and lib was always empty as that's a different sub-repo, I would think you would need to download the zip from the lib repo and put it there, and same goes for the pylib repo.

Did you manage to build the Perl / Python dependencies for the plugins?

**Comment by eniniz** [comment]
as you said I downloaded the lib zip and put it with the plugins, 
But I never worked with perl so I don't know how to buil dependencies, can you help please .
and thank you in advance :)

**Comment by HariSekhon** [comment]
Look at `Makefile` at the top level, all the build commands are in there.

**Comment by HariSekhon** [comment]
Ultimately you need to be able to get the repos from git or the zips and be able to use `pip` and `cpan`/`cpanm` to install libraries (again usually pulled from the official internet repos).

If you can't do these then you're going to struggle and would be better off just getting the pre-built docker image as mentioned on the main page as it contains everything - if you were going to download one thing to have it work, that would be the one.
