### ISSUE TITLE
Does it possible to use check_A_Service when it is installed using ambari 

### ISSUE THREAD

**Issue by eniniz** [HariSekhon/nagios-plugins#130]
I wonder if it is possible to monitor a service when it is installed using Ambari, for example I install HDFS using it and when I run check_hadoop_datanodes_block_balance.pl I get : 
CRITICAL: 404 Not Found

**Comment by HariSekhon** [comment]
Yes it's still possible to monitor services individually. That specific plugin is one of a couple that needs updates for the latest Hadoop as it was written years ago (most have been tested and updated but not that one).

You may want to try the ambari plugins which can query service state.
