### ISSUE TITLE
Day 31 out of range check_cloudera_manager_license.pl

### ISSUE THREAD

**Issue by Miorg** [HariSekhon/nagios-plugins#133]
Hi,

I had this issue:
`./check_cloudera_manager_license.pl -H par01stgmgt1 -u XXXXX -p XXXXXXX -T --tls-noverify
CRITICAL: Day '31' out of range 1..30 at ../lib/HariSekhonUtils.pm line 3043.`

I found solution for correct issue. In HariSekhonUtils.pm line 3043 i changed:
`my $epoch = timegm($sec, $min, $hour, $day, $month_int, $year-1900) || code_error "failed to convert timestamp $year-$month-$day $hour:$min:$sec";`
to
`my $epoch = timegm($sec, $min, $hour, $day, $month_int-1, $year-1900) || code_error "failed to convert timestamp $year-$month-$day $hour:$min:$sec";`.

This modification solved my problem:
`./check_cloudera_manager_license.pl -H par01stgmgt1 -u XXXXX -p XXXXXXX -T --tls-noverify
OK: 994 days remaining on Cloudera Manager license
`
I just add `-1` after $month-int
I don't know if i can push my modification, so in first time i prefer give my correction here.

Thx for your all probe and your job.

**Comment by HariSekhon** [comment]
@Miorg 

Thanks very much for the fix, I've tested this and updated accordingly.

The documentation for that perl module was too sparse but you do indeed need to subtract one to get the right result.

Cheers

Hari
