### ISSUE TITLE
check_hadoop_namenode* failing on HDP 2.5

### ISSUE THREAD

**Issue by tylerhawkes** [HariSekhon/nagios-plugins#135]
We're running HDP 2.5 and all I'm getting back is "CRITICAL 404 Not Found". It looks the page needs to be updated to be /dfshealth.html. After making that change, I still get "UNKNOWN: Failed to determine configured_capacity, either output is incomplete or format has changed, use -vvv to debug" for almost every check.

Here's what I'm getting back (with -vvv):

verbose mode on

check_hadoop_namenode.pl version 0.9.3  =>  Hari Sekhon Utils version 1.18.6

NameNode host:            dw-hadoop01
NameNode port:            50070
warning  upper:           1
critical upper:           1

setting timeout to 10 secs

setting http per request timeout to 9.00 secs

querying namenode dw-hadoop01 DFS overview
HTTP GET http://dw-hadoop01:50070/dfshealth.jsp
returned HTML:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 NOT_FOUND</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /dfshealth.jsp. Reason:
<pre>    NOT_FOUND</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>

</body>
</html>

http status code:     404
http status message:  Not Found

CRITICAL: 404 Not Found

**Comment by HariSekhon** [comment]
Hi @tylerhawkes 

Thanks for raising this and sorry for the slow reply, I have been all over the place in the last few months.

The plugin uses dfshealth JSP which has been completely replaced by AJAX calls so it's not aquite as simple a matter of changing the URL path and fixing up the parsing...

I've deconstructed the AJAX calls and will write new replacement plugins for these functions with better code design shortly.

I'll probably do this in the next week or two as time permits.

Cheers

Hari

**Comment by HariSekhon** [comment]
@tylerhawkes 

I've released a few new plugins to replace functionality of `check_hadoop_namenode.pl` and deprecated the plugin.

Please try the adjacent `check_hadoop_*` plugins and let me know how you get on and if there is anything else you need.

**Comment by HariSekhon** [comment]
Hi @tylerhawkes 

Have you had a chance to use the new python plugins for newer versions of Hadoop yet?

Please let me know if you're ok to close this ticket.

**Comment by tylerhawkes** [comment]
I haven't had a chance to use them and probably won't for a while. Go ahead
and close the ticket.
