### ISSUE TITLE
check_solr_api_ping.pl - invalid collection defined: must be alphanumeric, with optional periods in the middle

### ISSUE THREAD

**Issue by Tontonitch** [HariSekhon/nagios-plugins#138]
Hello,
The plugin check_solr_api_ping.pl fails with "invalid collection defined: must be alphanumeric, with optional periods in the middle" when the collection name includes the character "-".
Removing the validate_collection line make the plugin working, but of course there is no more validation of the collection name. Would be nice to allow the "-" character in collection names.
Regards,
Yannick

**Comment by HariSekhon** [comment]
Thanks for raising this, I've just pushed a change which should fix this for you.

Please try again and let me know.

Cheers

Hari

**Comment by HariSekhon** [comment]
I'm going to close this ticket for now, you can re-open if the issue persists for you.
