### ISSUE TITLE
check_whois.pl .biz whois servers name admin and tech email differently.  

### ISSUE THREAD

**Issue by jeff-cook** [HariSekhon/nagios-plugins#143]
The .biz whois servers name admin and tech email differently.  It uses "Administrative Contact Email:" and "Technical Contact Email:"

jwhois -d google.com | grep Email
Registrant Email: dns-admin@google.com
Admin Email: dns-admin@google.com
Tech Email: dns-admin@google.com

 jwhois -d google.biz | grep Email
Registrant Email:                            dns-admin@google.com
Administrative Contact Email:                dns-admin@google.com
Technical Contact Email:                     dns-admin@google.com

**Comment by jeff-cook** [comment]
Created pull request #144

**Comment by HariSekhon** [comment]
Closing as resolved as pull request https://github.com/HariSekhon/nagios-plugins/pull/144 was merged
