### ISSUE TITLE
check_whois.pl .coop Updated Date format not supported

### ISSUE THREAD

**Issue by jeff-cook** [HariSekhon/nagios-plugins#145]
The "Updated Date" format not supported correctly by the check_whois.pl script.  It keeps showing the "Last update of WHOIS database:"

```
 jwhois nic.coop | grep pdate
Updated Date: 2016-04-29T00:15:27.0Z
>>> Last update of WHOIS database: 2017-03-29T21:47:11.0Z <<<


/check_whois.pl  -v  -d nic.coop
WARNING: 36 days left for nic.coop domain, expires '05-05-2017' (36<60, w=60/c=30) nameservers:ns0.centralnic-dns.com,ns1.centralnic-dns.com,ns2.centralnic-dns.com,ns3.centralnic-dns.com,ns4.centralnic-dns.com,ns5.centralnic-dns.com registrant:'DotCooperation' registrar:'DotCooperation' created:2015-05-05 updated:2017-03-29 admin_email:'support@nic.coop' tech_email:'support@nic.coop' | whois_query_time=0.5765s

```

The "Creation Date" is in the same format and is working as expected.

**Comment by jeff-cook** [comment]
I think the "Creation Date:" is matching on line 406.  
That format may just need to get added to 420.

**Comment by HariSekhon** [comment]
I've added a fix to exclude picking up the last update of the whois database and tested against nic.coop.

I'll close this ticket but you're free to re-open if if still needed.

Cheers

Hari
