### ISSUE TITLE
Getting this issue for check_kafka_pl

### ISSUE THREAD

**Issue by rajesh054** [HariSekhon/nagios-plugins#150]
Can't locate Kafka.pm in @INC (@INC contains: ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./check_kafka.pl line 45.

**Comment by HariSekhon** [comment]
Did you build the project as per the README instructions to install the Kafka CPAN module?

If so, have you tried installing the Kafka CPAN module by hand to see if it's failing to install for any reason?

**Comment by rajesh054** [comment]
I have followed these steps , only 


Automated Build from Source

git clone https://github.com/harisekhon/nagios-plugins

cd nagios-plugins

make

**Comment by rajesh054** [comment]
and also getting this error when running this command 

1)   ./check_kafka.pl -H 192.168.12.104 -vv
CRITICAL: Can't locate Kafka.pm in @INC (@INC contains: ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./check_kafka.pl line 45.


2) ./check_kafka.py -H 192.168.12.104 --list-topics
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Kafka Topics:

CRITICAL: KafkaConfigurationError: KafkaConfigurationError: Request timeout (4500.0) must be larger than session timeout (30000)
[root@JIFFY2 nagiosplugin]# whereis kafka

**Comment by rajesh054** [comment]
And Also i want to know that how can i  monitor apache flink in nagios???

**Comment by HariSekhon** [comment]
it's possible that the Kafka CPAN module didn't install properly, please try:
```
cpan Kafka
```
and paste the full output and any log file if it lists one.

**Comment by HariSekhon** [comment]
For the latter python plugin can you please paste the output with `-v -v -v` switches added,

**Comment by rajesh054** [comment]
#cpan Kafka
Reading '/root/.cpan/Metadata'
  Database was generated on Mon, 10 Apr 2017 05:29:02 GMT
Kafka is up to date (1.001013).

This is the output i got

**Comment by rajesh054** [comment]
This is the output i got

./check_kafka.pl -H 192.168.12.104 -v -v -v
CRITICAL: Can't locate Kafka.pm in @INC (@INC contains: ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./check_kafka.pl line 45.
[root@JIFFY2 nagiosplugin]# ./check_kafka.py -H 192.168.12.104 -v -v -v
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
2017-04-10 19:36:08,331 - cli.py[main:165](16430) - INFO  - Hari Sekhon check_kafka.py version 0.3.9 =>  CLI version 0.3 =>  Utils version 0.10.20
2017-04-10 19:36:08,331 - cli.py[main:166](16430) - INFO  - https://github.com/harisekhon/nagios-plugins
2017-04-10 19:36:08,331 - cli.py[main:167](16430) - INFO  - verbose level: 3 (DEBUG)
2017-04-10 19:36:08,331 - utils.py[log_option:2155](16430) - INFO  - timeout:  10
2017-04-10 19:36:08,331 - cli.py[main:170](16430) - DEBUG - setting timeout alarm (10)
2017-04-10 19:36:08,331 - utils.py[log_option:2155](16430) - INFO  - brokers:  192.168.12.104
--topic not specified

Usage: check_kafka.py [options]

Options:
  -H broker_list, -B broker_list, --host=broker_list, --brokers=broker_list
                        Kafka Broker seed list in form host[:port],host2[:port2]... (default: localhost:9092)
  -T TOPIC, --topic=TOPIC
                        Kafka Topic
  -p PARTITION, --partition=PARTITION
                        Kafka Partition (default: 0)
  -a ACKS, --acks=ACKS  Acks to require from Kafka. Valid options are '1' for Kafka partition leader, or 'all' for all In-Sync Replicas (may
                        block causing timeout if replicas aren't available, default: 1)
  -s secs, --sleep=secs
                        Sleep in seconds between producing and consuming from given topic (default: 0.5)
  --list-topics         List Kafka topics from broker(s) and exit
  --list-partitions     List Kafka topic paritions from broker(s) and exit
  -w N, --warning=N     Warning threshold or ra:nge (inclusive, default: 1)
  -c N, --critical=N    Critical threshold or ra:nge (inclusive, default: 2)
  -t secs, --timeout=secs
                        Timeout in secs (default: 10)
  -v, --verbose         Verbose mode (-v, -vv, -vvv)
  -V, --version         Show version and exit
  -h, --help            Show full help and exit

**Comment by rajesh054** [comment]
Is the timeout defined in your files anywhere 
CRITICAL: KafkaConfigurationError: KafkaConfigurationError: Request timeout (4500.0) must be larger than session timeout (30000)

**Comment by HariSekhon** [comment]
The Perl module isn't found in your perl path, does the following result in an error?
```
perl -e 'use Kafka;'
```

For the python plugin that error is due to a change in the underlying Kafka python library in the latest version, I have just pushed an update which should get past if for you, please run
```
git pull
```
and then try again with the python version.

**Comment by rajesh054** [comment]
I did this perl -e 'use Kafka;' but did not got any thing
[root@JIFFY2 nagiosplugin]# perl -e 'use Kafka;'
[root@JIFFY2 nagiosplugin]#

**Comment by HariSekhon** [comment]
If you didn't get any error message from that then it means the Kafka perl module is correctly installed, are you calling the nagios plugin as the same user with the same environment (eg. $PERLPATH)?

I noticed you're using root, perhaps the permissions on the perl module are wrong and only root can read them.

Also did you try the git pull updated python plugin which should work now with the latest python Kafka library.

**Comment by rajesh054** [comment]
ya i did git pull  for python and it is giving output

./check_kafka.py -H 192.168.12.104 --list-topics
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Kafka Topics:

CRITICAL: NoBrokersAvailable: NoBrokersAvailable

**Comment by HariSekhon** [comment]
That's probably because it can't connect.

What does
```
nc -v 192.168.12.104 9092
```
show? What port is your Kafka broker listening on, 9092 or 6667? The plugin defaults to 9092 if you don't specify the ```--port``` switch.

**Comment by rajesh054** [comment]
Thank you, above command worked  for me and
sorry for creating multiple ticket , i did not saw that i was creating multiple tickets

**Comment by HariSekhon** [comment]
If you can connect to Kafka was nc then the kafka plugin should be able to connect too instead of getting the no brokers available message. Can you please double check your IP and port and try `-v -v -v` to show the full debug output?

**Comment by HariSekhon** [comment]
@rajesh054 

Please try `make update-no-recompile` to get the latest version and if the issue still persists then run the plugin again with `-vvv` and paste the full output so I can debug and fix it for you.

Thanks

Hari

**Comment by HariSekhon** [comment]
Closing for lack of feedback - this plugins works with the bundled dockerized integration tests.

Please re-open if needed.
