### ISSUE TITLE
check_linux_timezone

### ISSUE THREAD

**Issue by ddk85** [HariSekhon/nagios-plugins#154]
Hi,
Try to use your plugin on CentOS 6, but receive folowing:
`./check_linux_timezone.pl  -T MSK
WARNING: timezone is 'MSK'. Zoneinfo file '/usr/share/zoneinfo/MSK' not found! You may need to specify the path manually using --zoneinfo-file (if you don't have a zoneinfo installation because you're on a minimal docker distribution like Alpine then you can set --zoneinfo-file to /etc/localtime to avoid this error)`
ok, try it:
`./check_linux_timezone.pl  -T MSK --zoneinfo-file /etc/localtime 
WARNING: localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! timezone is 'MSK'`
also try this:
`./check_linux_timezone.pl  -T MSK --zoneinfo-file /usr/share/zoneinfo/Europe/Moscow 
WARNING: localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! localtime file '/etc/localtime' exceeded 10 lines, aborting check! timezone is 'MSK'`

Same with another timezones.

Install plugins as wrote in readme:
git clone https://github.com/harisekhon/nagios-plugins
cd nagios-plugins
make perl-libs  (I need only timezone plugin)

**Comment by HariSekhon** [comment]
I've just tested MSK on CentOS 6 and applied a fix for you which should resolve this.

FYI I believe the correct `--zoneinfo-file` to double check against MSK is /usr/share/zoneinfo/Europe/Moscow.

Let me know if this resolves it for you.

Cheers

Hari

**Comment by HariSekhon** [comment]
Fixed for russian timezone and tested, closing for lack of feedback.
