### ISSUE TITLE
check_yum.py - problem with regional settings different from en

### ISSUE THREAD

**Issue by thezipman** [HariSekhon/nagios-plugins#155]
The Popen routine is invoked in the environment of the user, but it relies on the usage of Yum in English language; this is not the case in many systems in non English speaking countries.

The following patch sets the environment variable LANG to en_US so the output of yum is correctly interpreted.
I'm not sure if the code in the OLD_PYTHON section is OK... I don't have the possibility to test it.

```
--- check_yum.py.orig   2017-04-19 00:49:38.375184584 +0200
+++ check_yum.py        2017-04-19 00:48:22.029677085 +0200
@@ -144,12 +144,14 @@
         if OLD_PYTHON:
             self.vprint(3, "subprocess not available, probably old python " \
                          + "version, using shell instead")
+            os.environ['LANG'] = "en_US"
             returncode, stdout = commands.getstatusoutput(cmd)
             if returncode >= 256:
                 returncode = returncode / 256
         else:
             try:
-                process = Popen(cmd.split(), stdin=PIPE, stdout=PIPE, stderr=STDOUT)
+                env = {'LANG': 'en_US'}
+                process = Popen(cmd.split(), stdin=PIPE, stdout=PIPE, stderr=STDOUT, env=env)
             except OSError, error:
                 error = str(error)
                 if error == "No such file or directory":

```

**Comment by HariSekhon** [comment]
Hi @thezipman 

Can you please give me an example of your locale, what is your LANG set to before this fix so that I can reproduce the error, fix it and test again.

Thanks

Hari

**Comment by HariSekhon** [comment]
@thezipman 

Did you see my last question asking what your locale is set to on your OS? I want to fix and close this but need to be able to reproduce and test it.

**Comment by HariSekhon** [comment]
Closing for lack of feedback, please re-open if needed.

Thanks

Hari
