### ISSUE TITLE
Can't locate loadable object for module Socket6 in @INC

### ISSUE THREAD

**Issue by mattmnx** [HariSekhon/nagios-plugins#158]
I have this installed on 3 servers and 1 of the servers I'm having issues. I had a lot of dependency errors but I was able to copy over the files from the working servers. Now, though, I am seeing this issue. Any insight into what I need to do? I did the same thing across the 3 servers and they are all similarly built.

Thanks!

**Comment by HariSekhon** [comment]
Is Socket6 installed on the server?

What happens when you run `sudo cpan Socket6`?

**Comment by HariSekhon** [comment]
The instructions do say rather than trying to copy and graft things around just run `git clone ...` and then run `make` - it automates everything you need.

**Comment by HariSekhon** [comment]
@mattmnx 

Did you try installing the Socket6 module as mentioned above?

**Comment by HariSekhon** [comment]
Closing for lack of feedback.
