### ISSUE TITLE
Can not connect to Broker

### ISSUE THREAD

**Issue by Sumontanaskar** [HariSekhon/nagios-plugins#159]
root@elk:/home/sumonta/nagios-plugins# ./check_kafka.pl -H elk.linuxplayer.com -B elk.linuxplayer.com:9092 -T TutorialTopic -p 0
CRITICAL: Error: Invalid argument: Server 'elk.linuxplayer.com:9092' is not connected

But kafka is working fine with consumer and producer.

**Comment by HariSekhon** [comment]
Hi @Sumontanaskar 

Can you please do an update and then run again with `-vvv` and paste the full output back so I can see what is happening?

Thanks

Hari

**Comment by HariSekhon** [comment]
Closing for lack of feedback - this works with the dockerized integration tests.

Please reopen if needed after trying latest version via `make update`.

Thanks

Hari
