### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by inscrutabledude** [HariSekhon/nagios-plugins#160]
I created a folder inside /usr/local/nagios/libexec/ and did git clone and make perl

I then ran ./check_elasticsearch_cluster_status.pl --help

I got the following error:
CRITICAL: Can't locate Sub/Util.pm in @INC (@INC contains: lib/HariSekhon/.. ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/local/share/perl5/Try/Tiny.pm line 20.

I need to know what I'm doing wrong here.  My knowledge of make is limited, so please try to explain at a basic level as far as possible.  Thanks in advance.

Environment:  Nagios XI on CentOS 7 in Azure

**Comment by HariSekhon** [comment]
It seems that environment is missing the Sub::Util package, try installing it like so:

```
cpan Sub::Util
```
and then try again.

**Comment by inscrutabledude** [comment]
Thank you, that worked, I appreciate the help!

**Comment by HariSekhon** [comment]
You're welcome. The real question is why this has come up in your environment and not others.

I've added Sub::Util to the list of CPAN dependencies in the build just to make sure it's there in different environments.
