### ISSUE TITLE
Can you please tell me how to add kafka plugin to an installed nagios server?

### ISSUE THREAD

**Issue by bhargav123** [HariSekhon/nagios-plugins#161]

**Comment by HariSekhon** [comment]
Download and build the project as per the instructions at:

https://github.com/HariSekhon/nagios-plugins#automated-build-from-source

The configure Nagios as per the links at the bottom of the page:

https://github.com/HariSekhon/nagios-plugins#enterprise-monitoring-systems

http://nagios.sourceforge.net/docs/3_0/objectdefinitions.html#command

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#service

and for local checks that run remotely on servers:

https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf
