### ISSUE TITLE
check_ssl_cert.pl SNI support

### ISSUE THREAD

**Issue by Petertjuh360** [HariSekhon/nagios-plugins#165]
Doesn't support SNI

**Comment by HariSekhon** [comment]
Hi Peter,

Thanks for raising this issue, this feature was actually requested, added and tested in conjunction with another user quite a long time ago. Can you please clarify how you are trying to use SNI and paste the full output of running the plugin on the command line using three verbose switches for debug mode so I can see the openssl command that is being triggered and the result?

```
check_ssl_cert.pl -vvv -H ...
```

Thanks

Hari

**Comment by HariSekhon** [comment]
Also be aware another user and I have both just submitted patches for this program to cover updates to openssl 1.1 and for Debian Stretch from issue #163 so please run

```
make update
```

before re-running the plugin so you have the latest version.

Thanks

Hari

**Comment by HariSekhon** [comment]
@Petertjuh360 

Also what version of openssl do you have installed, it's possible an update to openssl may require an update to this plugin in a similar fashion to #163

**Comment by HariSekhon** [comment]
Closing for lack of response, please re-open with details if necessary.
