### ISSUE TITLE
check_yum.pl: UNKNOWN: Yum output signature does not match current known format.

### ISSUE THREAD

**Issue by zefsauce** [HariSekhon/nagios-plugins#167]
After a yum update on all my CentOS 7 machines, the check_yum.pl plugin returns the following: 

UNKNOWN: Yum output signature does not match current known format. Output format may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

Output from -vvv:

#  check_nrpe -H 'xxx.xxx.xxx.xxx' -c check_yum.pl -a '-A -t 60 -vvv'
Output: verbose mode on

check_yum.pl version 0.2 => Hari Sekhon Utils version 1.18.9

setting timeout to 60 secs

cmd: /usr/bin/yum check-update
output:

Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
* base: mirrors.xmission.com
* epel: mirror.oss.ou.edu
* extras: mirror.us-midwest-1.nexcess.net
* updates: repo1.ash.innoscale.net

exitcode: 0

Section:
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
* base: mirrors.xmission.com
* epel: mirror.oss.ou.edu
* extras: mirror.us-midwest-1.nexcess.net
* updates: repo1.ash.innoscale.net

UNKNOWN: Yum output signature does not match current known format. Output format may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
Errors:
Return code: 3

**Comment by zefsauce** [comment]
Same issue when not piping through check_nrpe:

[root@waffle ~]# /usr/local/nagios/libexec/check_yum.pl -A -t 60 -vvv
verbose mode on

check_yum.pl version 0.2  =>  Hari Sekhon Utils version 1.18.9

setting timeout to 60 secs

cmd: /usr/bin/yum  check-update
output:

Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.unifiedlayer.com
 * epel: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: centos.firehosted.com

exitcode: 0

Section:
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.unifiedlayer.com
 * epel: mirror.steadfast.net
 * extras: repos.forethought.net
 * updates: centos.firehosted.com

UNKNOWN: Yum output signature does not match current known format. Output format may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

**Comment by HariSekhon** [comment]
@zefsauce 

Thanks very much for raising this issue - I've just pushed a fix and tested on CentOS 7 for when there are no package updates available. I've also tested the python version check_yum.py which works as expected.

I'll close this ticket but you're free to re-open it if needed.

Thanks

Hari

**Comment by zefsauce** [comment]
Issue resolved. Thanks!
