### ISSUE TITLE
check_yum.pl version 0.3 gets UNKNOWN (exitcode: 100) on rhel-7-server-rpms channel

### ISSUE THREAD

**Issue by jvandermeulen** [HariSekhon/nagios-plugins#168]
As the verbose output (-vvv) shows over 28000 lines it is not pasted here bu uploaded to:  
https://paste.fedoraproject.org/paste/-D8L4cwIGDF2dx8TPIp8nQ

The error  occurs on RHEL 7.3 on the  rhel-7-server-rpms channel and reads:

> UNKNOWN:  failed to determine the number of security & total updates. Format may have changed. (..)

The command used was:

> ./check_yum.pl  --no-warn-on-lock --disablerepo epel -t 55 -vvv

**Comment by HariSekhon** [comment]
I've tested and pushed a fix for this and also an update to the python version as well for anybody using the `--all-updates` mode.

Please `make update-no-recompile` to get the latest versions, try again and let me know - this should resolve it for you.

Cheers

Hari

**Comment by jvandermeulen** [comment]
Thank you very much Hari. I can confirm that it works now!
