### ISSUE TITLE
cassandra plugin installation

### ISSUE THREAD

**Issue by antonzhelyazkov** [HariSekhon/nagios-plugins#172]
Hi,

Could you help me to install cassandra monitoring plugins on centos 7. It seems that cassandra monitoring plugins needs external perl modules - 

```use HariSekhonUtils;```
```use HariSekhon::Cassandra::Nodetool;```

Could I download and install this modules?

**Comment by HariSekhon** [comment]
Those are my custom libraries which are available as a git submodule to this project, simply follow the instructions on the github page and you'll see that you simply need to run `make` from the nagios-plugins directory to install all dependencies.

**Comment by antonzhelyazkov** [comment]
Hi Hari,

Thank you for quick reply. I read the instructions and tried to run ```make``` and ```make install``` but it seems that with these commands will come a lots of updates to perl and python. I want to avoid this. Is it possible to place modules in perl modules directory and run the monitoring plugins?

**Comment by HariSekhon** [comment]
As per doc you can always do just `make perl` which will install to system perl or if running in Perlbrew it will install the modules locally as you suggest.

**Comment by antonzhelyazkov** [comment]
Hi,

If you point lib directory in perl modules configuration, scripts are running pretty well
