### ISSUE TITLE
check_cassandra*  times out

### ISSUE THREAD

**Issue by daytonjones** [HariSekhon/nagios-plugins#173]
When using the check_cassandra* checks I get timeouts... interestingly enough, nodetool timeouts as well - even though I can see communication happening when using tcpdump.  All other (basic) nagios checks (ssh, http, etc) work just fine.  I realize this is probably more of a core cassandra issue, but what could I be missing to get nodetool, and thereby your cassandra checks, working properly? 

I'm using Nagios Core (4.3.2) on Ubuntu 16.04 and Cassandra ReleaseVersion: 3.11.0.

The hosts (nagios and cassandra nodes) are in AWS and in the same VPC.

**Comment by HariSekhon** [comment]
Yeah this is a nodetool problem rather than a plugin problem, it depends on what tcpdump is showing, but you could also check the cassandra logs, check_tcp / netcat against port 7199 from nagios host etc.

**Comment by HariSekhon** [comment]
Also, have you tried running the plugins from a cassandra host itself to exclude inter-node networking as an issue?

There are actually functional tests ([tests/test_cassandra.sh](https://github.com/HariSekhon/nagios-plugins/blob/master/tests/test_cassandra.sh)) against Cassandra using Docker in this repo that do exactly that which have all passed validation against Cassandra 3.11.

**Comment by daytonjones** [comment]
Have not run the check_cassandra* on the nodes themselves, but check_tcp reports ok:
```
/usr/local/nagios/libexec$ ./check_tcp -H my.node -p 7199
TCP OK - 0.001 second response time on my.node port 7199|time=0.001039s;;;0.000000;10.000000
```

I'll track down the nodetool issue... running from my desktop to my.node it takes 3.5 minutes to return, but it does finally give results... Once I get that working, I'll revisit the checks.   Thanks!

**Comment by HariSekhon** [comment]
Ok let me know, now I'm curious as to what the issue is!

**Comment by HariSekhon** [comment]
Any update on this?

**Comment by HariSekhon** [comment]
Closing for lack of feedback.
