### ISSUE TITLE
check_aws_s3_file.pl port number override

### ISSUE THREAD

**Issue by francishooijen** [HariSekhon/nagios-plugins#175]
I'd like to use this script to check our S3 storage, but it runs on a different port then 80 or 443. Any way to override this?

**Comment by HariSekhon** [comment]
Hi @francishooijen 

Thanks for raising this interesting question. Are you using some internal S3 compatible storage or something, how is it running on a different port to AWS?

There was no reason to add a `--port` option as I normally provide with other programs in this repo as I expected that AWS would always use the official port...

However you can quickly and easily edit the single line 107 to put a port number after `$aws_host`:

https://github.com/HariSekhon/nagios-plugins/blob/master/check_aws_s3_file.pl#L107

**Comment by HariSekhon** [comment]
I may consider adding an official --port switch although I don't have S3 usage to test so I must wait and also I would be inclined to release a lot more code for this when I do, it's on the backlog of things for this project which I will be releasing in the next few months.

**Comment by francishooijen** [comment]
Hi, thanks for your quick reply! i tried your suggestion, but it doesn't appear to work in combination with --no-ssl

**Comment by francishooijen** [comment]
We are running an internal S3 storage. How and why its not running on standard ports i don't know, i'd have to ask our S3 guru, im no S3 expert, i just want to monitor it...

**Comment by HariSekhon** [comment]
That's what I thought, internal product mimicking S3... thanks for confirming. I will release much better coverage of this field in the upcoming months.

For now if you look at line 106 the protocol `--no-ssl` is handled separately by just setting http rather than https in the URL so the two should be orthogonal. I suspect something else is going on.

Can you please use debug mode (`-v -v -v`) and paste the detailed output back in to this ticket (you may be interested in the `scrub.pl` program from my [Tools repo](https://github.com/harisekhon/tools) which can automatically anonymize IPs, hostnames etc from the output.

**Comment by francishooijen** [comment]
@HariSekhon you are right is does appear to be something different:

check_aws_s3_file.pl version 0.4.1  =>  Hari Sekhon Utils version 1.18.11

host:                     xxx.xxx.xxx.xxx
filename:                 nagios.check
aws bucket:               nagios
aws access key:           XXXXXXXXXXXXXXXXXX2O
aws secret key:           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYR
ssl enabled:              false

setting timeout to 10 secs

setting http per request timeout to 9.00 secs

crafting authenticated request
querying HEAD http://xx.xx.xx.xx/nagios.check
status line: 403 Forbidden

CRITICAL: failed to retrieve file 'nagios.check' from xxx.xxx.xxx.xxx: 403 Forbidden

if i try https://key:secret@ip/nagios/nagios.check in a browser the file does download..
i see in the http query that there is no /bucket/file just /file...

**Comment by HariSekhon** [comment]
The bucket is sent in a host header as per the AWS spec, see this line:

https://github.com/HariSekhon/nagios-plugins/blob/master/check_aws_s3_file.pl#L100

You might be able to just set `--file` to `bucket/filename` and see if that works.

**Comment by francishooijen** [comment]
./check_aws_s3_file.pl --aws-access-key ########## --aws-secret-key ######### --bucket nagios --file nagios.check  --no-ssl -v -v -v

Same result

**Comment by HariSekhon** [comment]
I mean try:

```
./check_aws_s3_file.pl --aws-access-key ########## --aws-secret-key ######### --bucket nagios --file nagios/nagios.check --no-ssl -v -v -v
```

**Comment by HariSekhon** [comment]
I've just pushed a version in a new branch, you can try downloading this one and see how it works with bucket in the path and also I've added `--host` and `--port` options too:

https://raw.githubusercontent.com/HariSekhon/nagios-plugins/aws_s3_update/check_aws_s3_file.pl

I can't test it right now so you'll have to let me know if it works.

**Comment by francishooijen** [comment]
No luck.. I'll debug tomorrow with out S3 / Ceph guy... Maybe the problem is caused at his end...

Thanks for you help!!

**Comment by HariSekhon** [comment]
I've added the options for --host and --port, this is tested via CI against Minio internal private cloud storage.
