### ISSUE TITLE
check_yum - Error counting packages when "Obsoleting Packages" in output

### ISSUE THREAD

**Issue by wintertouch** [HariSekhon/nagios-plugins#176]
OS: RHEL 7
yum version: yum-3.4.3-154.el7.noarch
rpm version: 4.11.3-25.el7.x86_64

Output from check follows:
<pre>
[user@host ~]$ python check_yum.py -A -C -vvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.8.2
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum check-update -C
Returncode: '100'
Output: 'Loaded plugins: package_upload, product-id, search-disabled-repos, subscription-
              : manager
Repo rhel-7-server-rpms forced skip_if_unavailable=True due to: /etc/pki/entitlement/entitlement-key.pem

NetworkManager-config-server.noarch   1:1.8.0-11.el7_4       rhel-7-server-rpms
grub2.x86_64                          1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-common.noarch                   1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-pc.x86_64                       1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-pc-modules.noarch               1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-tools.x86_64                    1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-tools-extra.x86_64              1:2.02-0.65.el7_4.2    rhel-7-server-rpms
grub2-tools-minimal.x86_64            1:2.02-0.65.el7_4.2    rhel-7-server-rpms
iptables.x86_64                       1.4.21-18.2.el7_4      rhel-7-server-rpms
iptables-services.x86_64              1.4.21-18.2.el7_4      rhel-7-server-rpms
kernel.x86_64                         3.10.0-693.5.2.el7     rhel-7-server-rpms
kexec-tools.x86_64                    2.0.14-17.2.el7_4      rhel-7-server-rpms
kmod.x86_64                           20-15.el7_4.4          rhel-7-server-rpms
kmod-libs.x86_64                      20-15.el7_4.4          rhel-7-server-rpms
libgudev1.x86_64                      219-42.el7_4.4         rhel-7-server-rpms
nss.x86_64                            3.28.4-15.el7_4        rhel-7-server-rpms
nss-sysinit.x86_64                    3.28.4-15.el7_4        rhel-7-server-rpms
nss-tools.x86_64                      3.28.4-15.el7_4        rhel-7-server-rpms
openssh.x86_64                        7.4p1-13.el7_4         rhel-7-server-rpms
openssh-clients.x86_64                7.4p1-13.el7_4         rhel-7-server-rpms
openssh-server.x86_64                 7.4p1-13.el7_4         rhel-7-server-rpms
python-perf.x86_64                    3.10.0-693.5.2.el7     rhel-7-server-rpms
python-rhsm.x86_64                    1.19.10-1.el7_4        rhel-7-server-rpms
python-rhsm-certificates.x86_64       1.19.10-1.el7_4        rhel-7-server-rpms
rhnsd.x86_64                          5.0.13-7.1.el7_4       rhel-7-server-rpms
selinux-policy.noarch                 3.13.1-166.el7_4.5     rhel-7-server-rpms
selinux-policy-targeted.noarch        3.13.1-166.el7_4.5     rhel-7-server-rpms
subscription-manager.x86_64           1.19.23-1.el7_4        rhel-7-server-rpms
systemd.x86_64                        219-42.el7_4.4         rhel-7-server-rpms
systemd-libs.x86_64                   219-42.el7_4.4         rhel-7-server-rpms
systemd-sysv.x86_64                   219-42.el7_4.4         rhel-7-server-rpms
tzdata.noarch                         2017c-1.el7            rhel-7-server-rpms
wget.x86_64                           1.14-15.el7_4.1        rhel-7-server-rpms
Obsoleting Packages
grub2.x86_64                          1:2.02-0.65.el7_4.2    rhel-7-server-rpms
    grub2.x86_64                      1:2.02-0.64.el7        @rhel-7-server-rpms
grub2-tools.x86_64                    1:2.02-0.65.el7_4.2    rhel-7-server-rpms
    grub2-tools.x86_64                1:2.02-0.64.el7        @rhel-7-server-rpms
grub2-tools-extra.x86_64              1:2.02-0.65.el7_4.2    rhel-7-server-rpms
    grub2-tools.x86_64                1:2.02-0.64.el7        @rhel-7-server-rpms
grub2-tools-minimal.x86_64            1:2.02-0.65.el7_4.2    rhel-7-server-rpms
    grub2-tools.x86_64                1:2.02-0.64.el7        @rhel-7-server-rpms
'
UNKNOWN: Error parsing package information, inconsistent package count (41 count vs 38 num packages), yum output may have changed. Please make sure you have upgraded to the latest version from https://github.com/harisekhon/nagios-plugins. If the problem persists, please raise a ticket at https://github.com/harisekhon/nagios-plugins/issues with the full -vvv output
[user@host ~]$
</pre>

**Comment by HariSekhon** [comment]
I've just pushed a fix, please test again and paste the debug `-vvv` output if you have any issues.

Thanks

Hari

**Comment by HariSekhon** [comment]
Hi @wintertouch 

Did you get a chance to test this update so we can close this ticket?

Thanks

Hari

**Comment by wintertouch** [comment]
Unfortunately we've upgraded the servers and no longer have a live "Obsoleting" message.

I ran the patch in debug mode with the previous output and the issue appears to be resolved.

Thanks!
winter

**Comment by HariSekhon** [comment]
Ok, let's close this ticket in that case. It should be solved but you can always re-open or raise a new ticket referencing this one later if you encounter any future issue.

Thanks

Hari
