### ISSUE TITLE
Looking for Monitoring scripts to add kafka topics in Nagios

### ISSUE THREAD

**Issue by Sarahshee** [HariSekhon/nagios-plugins#178]
Looking Monitoring scripts to add kafka topics in Nagios , please advice how to create a script?

**Comment by HariSekhon** [comment]
You don't normally want to add topics, they should be created once and then tested for existent and message passing successfully as per the programs in this repo.

You can use the same libraries as the programs in this repo or the Kafka commands which you can see in the tests/test_kafka.sh script which tests these nagios plugins

**Comment by Sarahshee** [comment]
Hi , thanks for the reply . I agree topics no need to create .

In the existing Script tests/test_kafka.sh includes docker , I’ll need to rid of the docker .

My requirement is I’ll need to create a monitoring script for only kafka cluster usingbwith the existing topics and need to bring them in to nagios .

Can you help me to create a script on it without docker ?

Thanks

**Comment by HariSekhon** [comment]
See `check_kafka.py` and `check_kafka.pl` - they test an existing topic by inserting a message and reading it back. Just have your app messages with that nagios content.

**Comment by Sarahshee** [comment]
Sure will check ..

Thanks
