### ISSUE TITLE
Make giving errors, says several packages are not installed (but they are actually installed by default).

### ISSUE THREAD

**Issue by Kristada673** [HariSekhon/nagios-plugins#179]
My system has no internet. I just want to use the service `check_hadoop_namenode.pl`. How can I install this plugin alone please? When I tried to follow your GitHub instructions, I cannot `make` as it weirdly says that several packages that are installed by default (like, `which`, `tar`, `gcc`, `whet`, etc) are not installed! A screenshot of a part of the error is attached below:

![whatsapp image 2017-12-27 at 4 52 23 pm](https://user-images.githubusercontent.com/17232248/34376386-6acba1b4-eb26-11e7-83b6-39d2ee6ae2a0.jpeg)

I manually downloaded and installed the RPMs of each of the 30 odd packages it said was missing. But still, I am getting the same "missing package" error when `make`ing the clone of your GIT repo.

Or, is there any way in which I can download and install all the dependency packages (and their dependencies, and so on) that are required when `make`ing, so that `make` does not give error and runs successfully?

**Comment by HariSekhon** [comment]
If you download the RPM packages and CPAN / PyPI dependencies then you can use any plugin without needing to run ```make``` - all ```make``` does is fetch the git submodules and install the system packages and CPAN and PyPI dependencies for Perl and Python respectively.

If building manually just install the packages for the plugin and make sure you have the ```lib``` or ```pylib``` git submodules on disk for Perl or Python respectively.

As this is quite a large project and there are a lot of dependencies you may want to consider using the pre-build docker images which contain all the dependencies pre-built and is the best option in your case for all checks that execute remotely over the network (which is most of them).

**Comment by Kristada673** [comment]
This is so very frustrating. I tried manually downloading all dependencies, but more dependencies of those  dependencies keep springing up, and so on. Furthermore, even some of the existing Nagios plugins that come installed by default when installing Nagios are not working, as I describe here: https://stackoverflow.com/questions/48003431/how-do-i-get-nagios-plugins-to-work

And to make matters worse, I could not find a decent tutorial on the web on how to install a Nagios plugin. (I was asked to install Nagios and Ganglia just 2 days ago, so I am a novice in this kind of stuff, this is not my area of expertise.) Could you please help me out by guiding me on just how to get this damn 'check_hadoop_namenode.pl' to get working? It would be a great help! A brief step-by-step to-do list would be sufficient. Thanks.

**Comment by HariSekhon** [comment]
There should be no check_ganglia! in front of check_hadoop_namenode and also you'd need a command definition. At the bottom of the main page are the links to the nagios documentation you need for service and command definitions.

The dependencies are basically like for every other Perl or Python program in the world, for which there are a million web pages describing, but if you have Docker that is the best option as you can download the image with all dependencies and just `docker run <program> <args>`.

I'm going to close this ticket as this isn't a problem specific to this project but general systems administration.
