### ISSUE TITLE
Need help in installing

### ISSUE THREAD

**Issue by pswalia06** [HariSekhon/nagios-plugins#182]
[verizon@orion-RHEL-122 ~]$ git clone https://github.com/harisekhon/nagios-plugins
Cloning into 'nagios-plugins'...
remote: Counting objects: 27005, done.
remote: Compressing objects: 100% (5/5), done.
Receiving objects:  21% (5672/27005)   
remote: Total 27005 (delta 2), reused 5 (delta 1), pack-reused 26999
Receiving objects: 100% (27005/27005), 5.27 MiB | 8.68 MiB/s, done.
Resolving deltas: 100% (18353/18353), done.
[verizon@orion-RHEL-122 ~]$ 
[verizon@orion-RHEL-122 ~]$ 
[verizon@orion-RHEL-122 ~]$ 
[verizon@orion-RHEL-122 ~]$ 
[verizon@orion-RHEL-122 ~]$ cd nagios-plugins
[verizon@orion-RHEL-122 nagios-plugins]$ make
====================
Nagios Plugins Build
====================
make common
make[1]: Entering directory `/home/verizon/nagios-plugins'
if [ -x /sbin/apk ];        then make apk-packages; fi
if [ -x /usr/bin/apt-get ]; then make apt-packages; fi
if [ -x /usr/bin/yum ];     then make yum-packages; fi
make[2]: Entering directory `/home/verizon/nagios-plugins'
# to fetch and untar ZooKeeper, plus wget epel rpm
rpm -q wget || yum install -y wget
wget-1.14-15.el7_4.1.x86_64
# epel-release is in the list of rpms to install via yum in setup/rpm-packages.txt but this is a more backwards compatible method of installing that will work on older versions of RHEL / CentOS as well so is left here for compatibility purposes
#
# python-pip requires EPEL, so try to get the correct EPEL rpm
# this doesn't work for some reason CentOS 5 gives 'error: skipping https://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm - transfer failed - Unknown or unexpected error'
# must instead do wget 
rpm -q epel-release      || yum install -y epel-release || { wget -t 100 --retry-connrefused -O /tmp/epel.rpm "https://dl.fedoraproject.org/pub/epel/epel-release-latest-`grep -o '[[:digit:]]' /etc/*release | head -n1`.noarch.rpm" && sudo rpm -ivh /tmp/epel.rpm && rm -f /tmp/epel.rpm; }
epel-release-7-11.noarch
# installing packages individually to catch package install failure, otherwise yum succeeds even if it misses a package
for x in `sed 's/#.*//; /^[[:space:]]*$/d' setup/rpm-packages.txt setup/rpm-packages-dev.txt`; do rpm -q $x || sudo yum install -y $x; done
perl-5.16.3-292.el7.x86_64
python-2.7.5-58.el7.x86_64
package python-pip is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Artifactory-Cloudera-rpms                                | 1.4 kB     00:00     
Artifactory-centos-7-base                                | 1.4 kB     00:00     
Artifactory-centos-7-extras                              | 1.4 kB     00:00     
Artifactory-centos-7-updates                             | 1.4 kB     00:00     
Artifactory-epel                                         | 1.4 kB     00:00     
Artifactory-mysql                                        | 1.4 kB     00:00     
pdagent                                                  | 2.5 kB     00:00     
rhel-7-server-rpms                                       | 3.5 kB     00:00     
Package python2-pip-8.1.2-5.el7.noarch already installed and latest version
Nothing to do
python-setuptools-0.9.8-7.el7.noarch
epel-release-7-11.noarch
perl-libwww-perl-6.05-2.el7.noarch
package perl-DBD-MySQL is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package perl-DBD-MySQL.x86_64 0:4.023-5.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================
 Package                      Arch                 Version                   Repository                               Size
===========================================================================================================================
Installing:
 perl-DBD-MySQL               x86_64               4.023-5.el7               Artifactory-centos-7-base               140 k

Transaction Summary
===========================================================================================================================
Install  1 Package

Total download size: 140 k
Installed size: 323 k
Downloading packages:
perl-DBD-MySQL-4.023-5.el7.x86_64.rpm                                                               | 140 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : perl-DBD-MySQL-4.023-5.el7.x86_64                                                                       1/1 
  Verifying  : perl-DBD-MySQL-4.023-5.el7.x86_64                                                                       1/1 

Installed:
  perl-DBD-MySQL.x86_64 0:4.023-5.el7                                                                                      

Complete!
tar-1.26-32.el7.x86_64
wget-1.14-15.el7_4.1.x86_64
which-2.20-7.el7.x86_64
git-1.8.3.1-12.el7_4.x86_64
ethtool-4.8-1.el7.x86_64
net-tools-2.0-0.22.20131004git.el7.x86_64
curl-7.29.0-42.el7_4.1.x86_64
iputils-20160308-10.el7.x86_64
openssl-1.0.2k-8.el7.x86_64
package python-pyasn1 is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package python-pyasn1-0.1.6-2.el7.noarch is obsoleted by python2-pyasn1-0.1.9-7.el7.noarch which is already installed
Nothing to do
package jwhois is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package jwhois available.
Error: Nothing to do
package python-jenkins is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package python-jenkins available.
Error: Nothing to do
tzdata-2017c-1.el7.noarch
expat-devel-2.1.0-10.el7_3.x86_64
gcc-4.8.5-16.el7_4.1.x86_64
package gcc-c++ is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package gcc-c++.x86_64 0:4.8.5-16.el7_4.1 will be installed
--> Processing Dependency: libstdc++-devel = 4.8.5-16.el7_4.1 for package: gcc-c++-4.8.5-16.el7_4.1.x86_64
--> Running transaction check
---> Package libstdc++-devel.x86_64 0:4.8.5-16.el7_4.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================
 Package                    Arch              Version                        Repository                               Size
===========================================================================================================================
Installing:
 gcc-c++                    x86_64            4.8.5-16.el7_4.1               Artifactory-centos-7-updates            7.2 M
Installing for dependencies:
 libstdc++-devel            x86_64            4.8.5-16.el7_4.1               Artifactory-centos-7-updates            1.5 M

Transaction Summary
===========================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 8.7 M
Installed size: 24 M
Downloading packages:
(1/2): libstdc++-devel-4.8.5-16.el7_4.1.x86_64.rpm                                                  | 1.5 MB  00:00:00     
(2/2): gcc-c++-4.8.5-16.el7_4.1.x86_64.rpm                                                          | 7.2 MB  00:00:00     
---------------------------------------------------------------------------------------------------------------------------
Total                                                                                      113 MB/s | 8.7 MB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libstdc++-devel-4.8.5-16.el7_4.1.x86_64                                                                 1/2 
  Installing : gcc-c++-4.8.5-16.el7_4.1.x86_64                                                                         2/2 
  Verifying  : libstdc++-devel-4.8.5-16.el7_4.1.x86_64                                                                 1/2 
  Verifying  : gcc-c++-4.8.5-16.el7_4.1.x86_64                                                                         2/2 

Installed:
  gcc-c++.x86_64 0:4.8.5-16.el7_4.1                                                                                        

Dependency Installed:
  libstdc++-devel.x86_64 0:4.8.5-16.el7_4.1                                                                                

Complete!
package libev-devel is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package libev-devel available.
Error: Nothing to do
package libffi-devel is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package libffi-devel.x86_64 0:3.0.13-18.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================
 Package                    Arch                 Version                     Repository                               Size
===========================================================================================================================
Installing:
 libffi-devel               x86_64               3.0.13-18.el7               Artifactory-centos-7-base                23 k

Transaction Summary
===========================================================================================================================
Install  1 Package

Total download size: 23 k
Installed size: 27 k
Downloading packages:
libffi-devel-3.0.13-18.el7.x86_64.rpm                                                               |  23 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libffi-devel-3.0.13-18.el7.x86_64                                                                       1/1 
  Verifying  : libffi-devel-3.0.13-18.el7.x86_64                                                                       1/1 

Installed:
  libffi-devel.x86_64 0:3.0.13-18.el7                                                                                      

Complete!
package mysql-devel is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package mariadb-devel.x86_64 1:5.5.56-2.el7 will be installed
--> Processing Dependency: mariadb-libs(x86-64) = 1:5.5.56-2.el7 for package: 1:mariadb-devel-5.5.56-2.el7.x86_64
Package 1:mariadb-libs-5.5.56-2.el7.x86_64 is obsoleted by mysql-community-libs-5.6.38-2.el7.x86_64 which is already installed
--> Finished Dependency Resolution
Error: Package: 1:mariadb-devel-5.5.56-2.el7.x86_64 (rhel-7-server-rpms)
           Requires: mariadb-libs(x86-64) = 1:5.5.56-2.el7
           Available: 1:mariadb-libs-5.5.35-3.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.35-3.el7
           Available: 1:mariadb-libs-5.5.37-1.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.37-1.el7_0
           Available: 1:mariadb-libs-5.5.40-1.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.40-1.el7_0
           Available: 1:mariadb-libs-5.5.40-2.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.40-2.el7_0
           Available: 1:mariadb-libs-5.5.41-2.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.41-2.el7_0
           Available: 1:mariadb-libs-5.5.44-1.el7_1.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.44-1.el7_1
           Available: 1:mariadb-libs-5.5.44-2.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.44-2.el7
           Available: 1:mariadb-libs-5.5.47-1.el7_2.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.47-1.el7_2
           Available: 1:mariadb-libs-5.5.50-1.el7_2.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.50-1.el7_2
           Available: 1:mariadb-libs-5.5.52-1.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.52-1.el7
           Available: 1:mariadb-libs-5.5.56-2.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.56-2.el7
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: 1:mariadb-devel-5.5.56-2.el7.x86_64 (rhel-7-server-rpms)
           Requires: mariadb-libs(x86-64) = 1:5.5.56-2.el7
           Available: 1:mariadb-libs-5.5.35-3.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.35-3.el7
           Available: 1:mariadb-libs-5.5.37-1.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.37-1.el7_0
           Available: 1:mariadb-libs-5.5.40-1.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.40-1.el7_0
           Available: 1:mariadb-libs-5.5.40-2.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.40-2.el7_0
           Available: 1:mariadb-libs-5.5.41-2.el7_0.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.41-2.el7_0
           Available: 1:mariadb-libs-5.5.44-1.el7_1.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.44-1.el7_1
           Available: 1:mariadb-libs-5.5.44-2.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.44-2.el7
           Available: 1:mariadb-libs-5.5.47-1.el7_2.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.47-1.el7_2
           Available: 1:mariadb-libs-5.5.50-1.el7_2.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.50-1.el7_2
           Available: 1:mariadb-libs-5.5.52-1.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.52-1.el7
           Available: 1:mariadb-libs-5.5.56-2.el7.x86_64 (rhel-7-server-rpms)
               mariadb-libs(x86-64) = 1:5.5.56-2.el7
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
ansible-2.3.1.0-3.el7.noarch has missing requires of python-crypto
openssl-devel-1.0.2k-8.el7.x86_64
package perl-CPAN is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package perl-CPAN.noarch 0:1.9800-292.el7 will be installed
--> Processing Dependency: perl(local::lib) for package: perl-CPAN-1.9800-292.el7.noarch
--> Processing Dependency: perl(Digest::SHA) for package: perl-CPAN-1.9800-292.el7.noarch
--> Running transaction check
---> Package perl-Digest-SHA.x86_64 1:5.85-4.el7 will be installed
---> Package perl-local-lib.noarch 0:1.008010-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================
 Package                      Arch                Version                     Repository                              Size
===========================================================================================================================
Installing:
 perl-CPAN                    noarch              1.9800-292.el7              Artifactory-centos-7-base              292 k
Installing for dependencies:
 perl-Digest-SHA              x86_64              1:5.85-4.el7                Artifactory-centos-7-base               58 k
 perl-local-lib               noarch              1.008010-4.el7              Artifactory-centos-7-base               64 k

Transaction Summary
===========================================================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 415 k
Installed size: 958 k
Downloading packages:
(1/3): perl-CPAN-1.9800-292.el7.noarch.rpm                                                          | 292 kB  00:00:00     
(2/3): perl-Digest-SHA-5.85-4.el7.x86_64.rpm                                                        |  58 kB  00:00:00     
(3/3): perl-local-lib-1.008010-4.el7.noarch.rpm                                                     |  64 kB  00:00:00     
---------------------------------------------------------------------------------------------------------------------------
Total                                                                                      7.2 MB/s | 415 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : perl-local-lib-1.008010-4.el7.noarch                                                                    1/3 
  Installing : 1:perl-Digest-SHA-5.85-4.el7.x86_64                                                                     2/3 
  Installing : perl-CPAN-1.9800-292.el7.noarch                                                                         3/3 
  Verifying  : perl-CPAN-1.9800-292.el7.noarch                                                                         1/3 
  Verifying  : 1:perl-Digest-SHA-5.85-4.el7.x86_64                                                                     2/3 
  Verifying  : perl-local-lib-1.008010-4.el7.noarch                                                                    3/3 

Installed:
  perl-CPAN.noarch 0:1.9800-292.el7                                                                                        

Dependency Installed:
  perl-Digest-SHA.x86_64 1:5.85-4.el7                        perl-local-lib.noarch 0:1.008010-4.el7                       

Complete!
python-devel-2.7.5-58.el7.x86_64
package snappy-devel is not installed
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package snappy-devel available.
Error: Nothing to do
make[2]: *** [yum-packages] Error 1
make[2]: Leaving directory `/home/verizon/nagios-plugins'
make[1]: *** [system-packages] Error 2
make[1]: Leaving directory `/home/verizon/nagios-plugins'
make: *** [build] Error 2
[verizon@orion-RHEL-122 nagios-plugins]$ 
[verizon@orion-RHEL-122 nagios-plugins]$ 
[verizon@orion-RHEL-122 nagios-plugins]$

**Comment by HariSekhon** [comment]
What version of RHEL are you on?

Can you show the output of
```
cat /etc/*release
```

**Comment by HariSekhon** [comment]
Any update on this?

**Comment by HariSekhon** [comment]
Closing for lack of response.
