### ISSUE TITLE
ImportError: No module named blessings

### ISSUE THREAD

**Issue by shsubramanian** [HariSekhon/nagios-plugins#184]
I just cloned and built this on Ubuntu 16.04. When i add the checks (check_influxdb_*) to icinga2, it gives the following error.

But running from terminal gives the correct result. Anyone faced this issue?

Traceback (most recent call last):
File "/usr/lib/nagios/plugins/nagios-plugins/check_influxdb_api_ping.py", line 41, in <module>
    from harisekhon import RestNagiosPlugin
  File "/usr/lib/nagios/plugins/nagios-plugins/pylib/harisekhon/__init__.py", line 26, in <module>
    from harisekhon.cli import CLI
  File "/usr/lib/nagios/plugins/nagios-plugins/pylib/harisekhon/cli.py", line 43, in <module>
    from blessings import Terminal
ImportError: No module named blessings

**Comment by shsubramanian** [comment]
BTW tried installing blessings using "pip install blessings". It says the module is already latest version.

**Comment by pablodav** [comment]
is it trying to use python3? try installing with `pip3 install blessings`

**Comment by shsubramanian** [comment]
Apparently this was happening for "nagios" user alone. I put the directory under /usr/lib/nagios/plugins which is "PluginDir" in ICINGA and accessed via PluginDir + "/nagios-plugins". That fixed the issue. Looks like something to do with PATH settings.

**Comment by shsubramanian** [comment]
Reopening as I started facing this issue in a new installation. Any pointers appreciated.

nagios-plugins - latest, make build successful. Validate the CPAN modules and python module requirements, all installed
Ubuntu - 16.0.4 Xenial
ICINGA - 2.9.2
Python - 2.7.12

Note: i have few other VMs where this works fine for root as well as nagios user. :(

sudo -H -u nagios bash -c '/usr/lib/nagios/plugins/nagios-plugins/check_influxdb_api_ping.py -H 127.0.0.1' - throws error

`Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/nagios-plugins/check_influxdb_api_ping.py", line 43, in <module>
    from harisekhon import RestNagiosPlugin
  File "/usr/lib/nagios/plugins/nagios-plugins/pylib/harisekhon/__init__.py", line 26, in <module>
    from harisekhon.cli import CLI
  File "/usr/lib/nagios/plugins/nagios-plugins/pylib/harisekhon/cli.py", line 43, in <module>
    from blessings import Terminal
ImportError: No module named blessings`

/usr/lib/nagios/plugins/nagios-plugins/check_influxdb_api_ping.py -H 127.0.0.1 - works fine

**Comment by shsubramanian** [comment]
Closing it again.

Permissions on /usr/local/lib/python2.7/dist-packages were different: drw-r-Sr--

Directory permission set via
find /usr/local/lib/python2.7/dist-packages -type d -exec chmod 755 {} +

File permission set via
find /usr/local/lib/python2.7/dist-packages -type f -exec chmod 644 {} +
