### ISSUE TITLE
Invalid perfdata value error for check_solr_metrics

### ISSUE THREAD

**Issue by shsubramanian** [HariSekhon/nagios-plugins#188]
The check_solr_metrics.pl is generating a lot of warnings for GraphiteWriter and InfluxDBWriter.

`[2018-04-09 05:52:17 -0700] warning/GraphiteWriter: Ignoring invalid perfdata value: ''org.apache.solr.handler.admin.CollectionsHandler '=>
Context:
	(0) Processing check result for 'solr03!check_solr_metrics'`

Is there any issue with the output format? I am using ICINGA1 version: r2.8.2-1, Solr 6.3.0

`OK: Solr cache documentCache cumulative_evictions=419, cumulative_hitratio=0.61, cumulative_hits=35736, cumulative_inserts=22791, cumulative_lookups=58527, evictions=0, hitratio=0.62, hits=192, inserts=116, lookups=308, size=116, warmupTime=0, fieldCache entries_count=2454, fieldValueCache cumulative_evictions=0, cumulative_hitratio=0, cumulative_hits=0, cumulative_inserts=0, cumulative_lookups=0, evictions=0, hitratio=0, hits=0, inserts=0, lookups=0, size=0, warmupTime=0, filterCache cumulative_evictions=0, cumulative_hitratio=0, cumulative_hits=0, cumulative_inserts=0, cumulative_lookups=0, evictions=0, hitratio=0, hits=0, inserts=0, lookups=0, size=0, warmupTime=0, perSegFilter cumulative_evictions=0, cumulative_hitratio=0, cumulative_hits=0, cumulative_inserts=0, cumulative_lookups=0, evictions=0, hitratio=0, hits=0, inserts=0, lookups=0, size=0, warmupTime=0, queryResultCache cumulative_evictions=0, cumulative_hitratio=0.82, cumulative_hits=17789, cumulative_inserts=3948, cumulative_lookups=21684, evictions=0, hitratio=0.56, hits=25, inserts=20, lookups=45, size=20, warmupTime=0, query time 101ms, QTime 11ms | 'documentCache => cumulative_evictions'=419 'documentCache => cumulative_hitratio'=0.61 'documentCache => cumulative_hits'=35736 'documentCache => cumulative_inserts'=22791 'documentCache => cumulative_lookups'=58527 'documentCache => evictions'=0 'documentCache => hitratio'=0.62 'documentCache => hits'=192 'documentCache => inserts'=116 'documentCache => lookups'=308 'documentCache => size'=116 'documentCache => warmupTime'=0 'fieldCache => entries_count'=2454 'fieldValueCache => cumulative_evictions'=0 'fieldValueCache => cumulative_hitratio'=0 'fieldValueCache => cumulative_hits'=0 'fieldValueCache => cumulative_inserts'=0 'fieldValueCache => cumulative_lookups'=0 'fieldValueCache => evictions'=0 'fieldValueCache => hitratio'=0 'fieldValueCache => hits'=0 'fieldValueCache => inserts'=0 'fieldValueCache => lookups'=0 'fieldValueCache => size'=0 'fieldValueCache => warmupTime'=0 'filterCache => cumulative_evictions'=0 'filterCache => cumulative_hitratio'=0 'filterCache => cumulative_hits'=0 'filterCache => cumulative_inserts'=0 'filterCache => cumulative_lookups'=0 'filterCache => evictions'=0 'filterCache => hitratio'=0 'filterCache => hits'=0 'filterCache => inserts'=0 'filterCache => lookups'=0 'filterCache => size'=0 'filterCache => warmupTime'=0 'perSegFilter => cumulative_evictions'=0 'perSegFilter => cumulative_hitratio'=0 'perSegFilter => cumulative_hits'=0 'perSegFilter => cumulative_inserts'=0 'perSegFilter => cumulative_lookups'=0 'perSegFilter => evictions'=0 'perSegFilter => hitratio'=0 'perSegFilter => hits'=0 'perSegFilter => inserts'=0 'perSegFilter => lookups'=0 'perSegFilter => size'=0 'perSegFilter => warmupTime'=0 'queryResultCache => cumulative_evictions'=0 'queryResultCache => cumulative_hitratio'=0.82 'queryResultCache => cumulative_hits'=17789 'queryResultCache => cumulative_inserts'=3948 'queryResultCache => cumulative_lookups'=21684 'queryResultCache => evictions'=0 'queryResultCache => hitratio'=0.56 'queryResultCache => hits'=25 'queryResultCache => inserts'=20 'queryResultCache => lookups'=45 'queryResultCache => size'=20 'queryResultCache => warmupTime'=0 query_time=101ms query_QTime=11ms`

**Comment by HariSekhon** [comment]
It's likely a character problem which I could fix easily if I determine which one. It looks like the output is truncated, please run the plugin with the args on the command line and paste the full output in this ticket.

I suspect it's the dots in the `org.apache...` due to graphite using these are metric key separators.

**Comment by HariSekhon** [comment]
I've just pushed a change, please

```make update-no-recompile```

and then try again.

**Comment by shsubramanian** [comment]
Cool, that worked. No more warnings. You rock!!

**Comment by HariSekhon** [comment]
Cool, thanks for letting me know, closing this ticket now.

Cheers

Hari
