### ISSUE TITLE
UNKNOWN: Error parsing package information, inconsistent package count

### ISSUE THREAD

**Issue by Yiejoon4** [HariSekhon/nagios-plugins#191]
Hi,

after kernel update on redhat systems and without rebooting until maintenance windows, following unknown message ist created. Already the newest plugin version.

/usr/lib/nagios/plugins/check_yum.py --all-updates --cache-only
UNKNOWN: Error parsing package information, inconsistent package count (2 count vs 0 num packages), yum output may have changed. Please make sure you have upgraded to the latest version from https://github.com/harisekhon/nagios-plugins. If the problem persists, please raise a ticket at https://github.com/harisekhon/nagios-plugins/issues with the full -vvv output

sudo /usr/lib/nagios/plugins/check_yum.py --all-updates --cache-only -vvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.8.3
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum check-update -C
Returncode: '0'
Output: 'Loaded plugins: product-id, search-disabled-repos, subscription-manager
Security: kernel-3.10.0-862.2.3.el7.x86_64 is an installed security update
Security: kernel-3.10.0-862.el7.x86_64 is the currently running version
'
UNKNOWN: Error parsing package information, inconsistent package count (2 count vs 0 num packages), yum output may have changed. Please make sure you have upgraded to the latest version from https://github.com/harisekhon/nagios-plugins. If the problem persists, please raise a ticket at https://github.com/harisekhon/nagios-plugins/issues with the full -vvv output

Thank you in advance.

**Comment by HariSekhon** [comment]
Try the latest version I've just pushed

**Comment by Yiejoon4** [comment]
Have try the latest version and it looks good 👍 Thanks.
