### ISSUE TITLE
Can't get docker checks to work

### ISSUE THREAD

**Issue by nofear87** [HariSekhon/nagios-plugins#193]
Running the docker checks results in:

> CRITICAL: Docker connection failed: ('Connection aborted.', error(2, 'No such file or directory'))

I have to mount the docker.sock into the container? Can't find anything in docs.

Cmd:

`docker run harisekhon/nagios-plugins check_docker_images.py -H unix://var/run/docker.sock`

**Comment by HariSekhon** [comment]
Yes if you're running it like this then you would need to expose the socket within the docker image as per standard docker behaviour, try the docker -v switch to mount the socket to be available inside the container, eg.:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock harisekhon/nagios-plugins check_docker_images.py -H unix://var/run/docker.sock
```

**Comment by HariSekhon** [comment]
Probably just give octal unix permissions on the docker.sock file to the nrpe user.

**Comment by HariSekhon** [comment]
Is this still an issue for you or should I close this ticket?

**Comment by HariSekhon** [comment]
That'll probably only work if you give the exact command with args and then use sudo in front of the call. I think it's more tricky to get right.

I would first try to chown/chgrp/chmod the permissions on the socket to be readable by the nrpe user so you don't have to do anything special to get it working.

**Comment by nofear87** [comment]
I add read access for every user without success.

**Comment by HariSekhon** [comment]
Docker docs says that because docker daemon recreates the socket and assigns the docker group, the permissions won't last, hence adding to the docker group is the solution:

```
If you don’t want to use sudo when you use the docker command, create a Unix group called docker and add users to it. When the docker daemon starts, it makes the ownership of the Unix socket read/writable by the docker group.
```
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

Since this is just an environment / permissions issue rather than a code issue, I'll close this ticket now.
