### ISSUE TITLE
check_yum.py doesn't function correctly when run by system user RHEL 6.9

### ISSUE THREAD

**Issue by codingwatermelon** [HariSekhon/Nagios-Plugins#196]
Hi there,

First post here, so be sure to let me know if I'm missing any important information.

I have a strange issue with the `check_yum.py` plugin not working correctly when run by a system user, and this issue seems to be confined to RHEL 6.9.

I can run the plugin fine via command line with a non-privileged (and privileged) user and it gives the expected output:
```
YUM CRITICAL: 14 Security Updates Available. 16 Non-Security Updates Available | security_updates_available=14 non_security_updates_available=16 total_updates_available=30
```

but when I try with my system user (I use Icinga, so the user is `icinga`), I get this output:
```
UNKNOWN: Security plugin for yum is required. Try to 'yum install yum-security' (RHEL5) or 'yum install yum-plugin-security' (RHEL6) and then re-run this plugin. Alternatively, to just alert on any update which does not require the security plugin, try --all-updates
```

This doesn't quite make sense because I do have the security plugin installed and the plugin does seem to work when **not** being run by a system user (as indicated in the first plugin output). However, there have been times where the plugin will actually work as expected, but only for a couple of minutes. 
Another really strange issue was that I was getting the "bad" output on a different RHEL server (v7.5) and after running `yum install yum-security` and _not even having to install anything,_ `check_yum.py` started working out of nowhere.

I don't think this plugin requires any dependencies as indicated by the docs:

> Some plugins like check_yum.py can be copied around independently 

so I'm really not certain as to what could be causing this strange behavior.

Could somebody give me some guidance?

Thanks!!

**Comment by Hatsikki** [comment]
I have encountered the same issue, tested it on a few RHEL7 servers, no issues. Installed it on a different server, also RHEL7 and I get the UNKNOWN error. 
User rights are similar, yum package is up-to-date. Thinking it might be an OS setting, but I have no idea where to look at the moment.

**Comment by HariSekhon** [comment]
Perhaps your sudo commands are too specific? Including arguments limits the execution to only permitting sudo with those arguments, so enabling extra switches you may end up sudo being denied.

One way of isolating this is to run the plugin as root on both servers and see if it works. If so then it's definitely just your local sudo config on each server and not an actual code problem.

**Comment by codingwatermelon** [comment]
Hmm, I'm still not sure if my problem is within sudo rights or yum itself. I just tested this one of my problem servers:

1. Run script unprivileged --------------> get error like above
2. Escalate, run script privileged -------> get error like above
3. Run script privileged again (~30 seconds after running the script in step 2) --> get desired output
4. Deescalate, run script unprivileged --> get desired output

???

I can't make sense of this behavior.

**Comment by HariSekhon** [comment]
To isolate sudo have you checked /var/log/messages or /var/log/secure for sudo messages to check it was authorized.

After discounting that then it's on to check permissions around yum and the security plugin files.

Also, is SELinux disabled? This command will show it:

```
getenforce
```

**Comment by HariSekhon** [comment]
Did you ever figure this out? I've pushed a new version for RHEL 8.

I suspect in your outputs for runs 2 & 3 above that caching is at play, which you can test with `yum makecache` command and the `--cache-only` switch on the plugin.

**Comment by Hatsikki** [comment]
I've decided to install the check as an RPM for RHEL7, and with that manage the sudo rights to add a line in the sudoers file with the following line: 
icinga     ALL=NOPASSWD:/opt/nems-it/icinga-nrpe/plugins/check_yum 

Allowing 'icinga' to execute the script.
