### ISSUE TITLE
How to make ElasticSearch status=yellow show critical in Icinga?

### ISSUE THREAD

**Issue by raptureveteran** [HariSekhon/nagios-plugins#198]
I can't figure this out. 

check_elasticsearch_cluster_status doesn't have an option to change how this alerts

check_elasticsearch_cluster_stats shows a key "status=green" but I can't figure out how to utilize critical threshold to fire off a critical alert for when the status is both yellow and red.

IS this possible?

**Comment by HariSekhon** [comment]
You can do generically with a shell script wrapper, it's so trivial to do that I have just written one and uploaded it to `older/warning_to_critical.sh`.

Just put that in front of any nagios plugin on the command line and if the plugin returns WARNING it will upgrade it to CRITICAL for you.
