### ISSUE TITLE
check_ambari_* - List Services in Maintenance state

### ISSUE THREAD

**Issue by Rayn0r** [HariSekhon/Nagios-Plugins#204]
How difficult would it be to extend a script or add one, that lists all services which are in maintenance mode?

**Comment by HariSekhon** [comment]
This was already on the unofficial todo list as iirc it is available in the API and will be done at some point in the reasonably near future as soon as I get time.

Looking back at check_ambari_services.pl it already has an option to not alert if a service is in maintenance mode.

I should be able to easily add a separate check just to check for services in maintenance mode, I just need to find time outside of my current assignment.

**Comment by HariSekhon** [comment]
Closing for lack of progress as this is no longer on the roadmap given Hortonworks is dead.
