### ISSUE TITLE
Kafka.pm not found -- Trying to use "check_kafka.pl"

### ISSUE THREAD

**Issue by johnhighway** [HariSekhon/nagios-plugins#206]
Hello,

I'm trying to see if "check_kafka.pl" will satisfy our monitoring needs to determine the health of our topics in the Kafka cluster. Unfortunately, when I tried to test run the script, it complained that it "kafka.pm". I tried searching your libraries for it but didn't see it.

Can you help?

Edited: Nevermind, I didn't realize that Kafka.pm was actually a Perl module on CPAN. I thought it was something you've written as part of your library.

**Comment by HariSekhon** [comment]
Did you run make as per the build instructions?
