### ISSUE TITLE
Return code of 4 for service 'Kafka Check' on host 'kafka' was out of bounds

### ISSUE THREAD

**Issue by srinandsk** [HariSekhon/nagios-plugins#210]
commands.cfg
----------------
define command{
command_name check_kafka
command_line $USER2$/check_kafka.py --brokers $HOSTADDRESS$:32789 -T $ARG1$
}

localhost.cfg
--------------
define service{
use local-service,graphed-service ; Name of service template to use
host_name kafka
service_description Kafka Check
check_command check_kafka!topic
}

Error
------
Return code of 4 for service 'Kafka Check' on host 'kafka' was out of bounds

IT WORKS PERFECTLY ON THE COMMAND LINE

**Comment by HariSekhon** [comment]
Did you try it on the command line as the same user that you run nagios as?

You probably have a very restrictive UMASK environment variable set such as 077 and installed the modules as root so the nagios user cannot read them.

**Comment by srinandsk** [comment]
Sometimes all of a sudden I get the error even on command line, has it got something to do with the shell (bash/sh)  ? Strange problem

**Comment by HariSekhon** [comment]
Which user are you using on the command line and which user is nagios running as?

It's complaining the kafka module isn't present, you probably don't have read permissions to the python site packages module directory tree for kafka.

**Comment by srinandsk** [comment]
Thanks so much Hari for the help, it was indeed a problem with the user. From the command line, the user was 'root', while with Nagios as a tool, the user was 'nagios'.
Problem solved, you can close this thread
