### ISSUE TITLE
check_mysql_query.pl

### ISSUE THREAD

**Issue by blakhawk23** [HariSekhon/Nagios-Plugins#216]
Hi. Is there a way to use negative numbers in the warning and critical thresholds?

**Comment by HariSekhon** [comment]
Try standard nagios range thresholds of `min:max` or the inverted check of `@min:max` where the result has to be outside that range ie. lower than min or higher than max, and you should be able to leave out either min or max too eg. just use `min:` or `:max`.

This is documented in this section:

https://github.com/HariSekhon/Nagios-Plugins#goals
