### ISSUE TITLE
Thank you! :)

### ISSUE THREAD

**Issue by MarcusCaepio** [HariSekhon/Nagios-Plugins#222]
This is not an issue, but just a thank you to @HariSekhon .
I am a fan of your plugins and your idea to build a docker container with the plugins and all their dependencies. This inspired me to do the same with check_vmware_esx and the vmware perl SDK. It keeps me away from trouble with different perl module versions and works like a charm.

So again, thank you very much ! :)

Cheers,
Marcus

**Comment by HariSekhon** [comment]
You're welcome :)
