### ISSUE TITLE
check_yum.pl fails with "UNKNOWN: failed to determine the number of security updates. Format may have changed." on CentOS8

### ISSUE THREAD

**Issue by joopmartens** [HariSekhon/Nagios-Plugins#226]
Just tried to run check_yum.pl on CentOS 8 and it unfortunately fails with the following error:

```
./check_yum -vvv
verbose mode on

check_yum version 0.7.5  =>  Hari Sekhon Utils version 1.19.5


setting timeout to 30 secs

cmd: /usr/bin/yum  --security check-update
output:

Last metadata expiration check: 0:49:27 ago on Thu 26 Sep 2019 06:47:05 PM CEST.

exitcode: 0

UNKNOWN: failed to determine the number of security updates. Format may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

```

This probably is caused by dnf providing a different output format for the command: /usr/bin/yum  --security check-update

```
/usr/bin/yum  --security check-update
Last metadata expiration check: 1:04:29 ago on Thu 26 Sep 2019 06:47:05 PM CEST.
```
It is e.g. missing an output line like `No packages needed for security; 2 packages available` like when running the command on CentOS 7.

Could you try to support dnf/CentOS 8?

**Comment by HariSekhon** [comment]
It's already on the backlog, can't promise when though. If it was a minor change I'd just extend `check_yum.py` to cover it but not checked yet.

**Comment by HariSekhon** [comment]
Also looks like there isn't a docker image available for the new CentOS version (`dockerhub_show_tags.py` is in my [DevOps Python Tools](https://github.com/harisekhon/devops-python-tools) repo):
```
dockerhub_show_tags.py centos

DockerHub

repo: centos
tags: latest
      5
      5.11
      6
      6.10
      6.6
      6.7
      6.8
      6.9
      7
      7.0.1406
      7.1.1503
      7.2.1511
      7.3.1611
      7.4.1708
      7.5.1804
      7.6.1810
      centos5
      centos5.11
      centos6
      centos6.10
      centos6.6
      centos6.7
      centos6.8
      centos6.9
      centos7
      centos7.0.1406
      centos7.1.1503
      centos7.2.1511
      centos7.3.1611
      centos7.4.1708
      centos7.5.1804
      centos7.6.1810
```

**Comment by joopmartens** [comment]
Good to hear that it is already in your backlog and that you are willing to spend the effort to support CentOS 8. 

I shall be patient and wait until it is available ;-)

Thanks for providing your plugins! It's really appreciated.

**Comment by JimKeating2** [comment]
Yes, Thanks again for providing your plugins for Nagios!  
Works great with Centos 7 but not on Centos 8.  
JK

**Comment by HariSekhon** [comment]
CentOS 8 docker images are now available so I've pushed a compatibility update, please try the latest version and let me know.

I do not have any system in need of security updates, so cannot test that part until DNF systems actually get some security updates which I can test via docker.

**Comment by joopmartens** [comment]
I have tested check_yum.py and it successfully determines the non-security updates. My system either isn't in need of any security updates so I also have to wait for new security updates until I can verify if those are also properly determined.

Thanks so far!

**Comment by joopmartens** [comment]
After all available updates have been installed I receive the following error:

./check_yum.py -vvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.10.0
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum --security check-update
Returncode: '0'
Output: 'Last metadata expiration check: 0:42:40 ago on Tue 03 Mar 2020 09:43:43 PM CET.
'
YUM WARNING: Cannot find summary line in yum output. Please make sure you have upgraded to the latest version from https://github.com/harisekhon/nagios-plugins. If the problem persists, please raise a ticket at https://github.com/harisekhon/nagios-plugins/issues with the full -vvv output

**Comment by HariSekhon** [comment]
@joopmartens I've just pushed a fix for that, please try the latest version.

**Comment by joopmartens** [comment]
Looking good:

./check_yum.py -vvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.10.1
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum --security check-update
Returncode: '0'
Output: 'Last metadata expiration check: 0:34:41 ago on Wed 04 Mar 2020 07:49:23 PM CET.
'
YUM OK: 0 Security Updates Available. 0 Non-Security Updates Available | security_updates_available=0 non_security_updates_available=0 total_updates_available=0

Thanks for the support HariSekhon!
