### ISSUE TITLE
Hadoop API change - yarn queue plugin - Fair Scheduler support

### ISSUE THREAD

**Issue by FSidorowicz** [HariSekhon/Nagios-Plugins#241]
Hi,
I wanted to use Yarn monitoring plugin (check_hadoop_yarn_queue_capacity.pl).
It turned out that API has changed. I modified the line 76 of the plugin but the results are:
- the leaf queues are not monitored (only the root.<queue>). I need to go one step deeper,
- the % of usage is not relevant (it shows very high %) and it somehow dobles the output:
     OK: queue used capacity of allocated: 'root.batch' = 0.00%, 'root.default' = 0.00%, 'root.users' = 102400.00%, 'root.<hidden_name>' = 1721344.00% | 'root.batch'=0.00%;;; 'root.default'=0.00%;;; 'root.users'=102400.00%;;; 'root.<hidden_name>'=1721344.00%;;;

Is that possible to modify the script to show valid % of queue usage? If so is it possible to modify it to show % of used cluster (not the queue itself as it's set as default)? It would be nice to have a option which % to show.
Of course the script would have to go deeper than only the first level (for example not only show root.users queue usage but also all queues under root.users)

I attach a file from test environment where only 1 queue exists under root.users. The above results are from json from the production enviroment. If you need it for the issue with irrelevant % please provide feedback.

[cloudera_json.txt](https://github.com/HariSekhon/Nagios-Plugins/files/3909986/cloudera_json.txt)

Thank you and best regards
Filip

**Comment by HariSekhon** [comment]
Hi Filip,

What version of Hadoop are you using (3.x?) and on what distro (Cloudera CDH 6?) ?

Thanks

Hari

**Comment by FSidorowicz** [comment]
Hi Hari,

thanks for taking this up. We are using hdp 2.6.0 and Cloudera version CDH 5.14.4

Thank you,
Filip

**Comment by HariSekhon** [comment]
This appears to be a Fair Scheduler vs Capacity Scheduler API issue, the plugin was written against Hortonworks which by default uses the Capacity Scheduler.

I've pushed an update in a new branch `yarn_fair_scheduler_queue_check`. Please try that via

```
git checkout yarn_fair_scheduler_queue_check
```
 and then try again. If it works I'll merge it to the master branch.

Thanks

Hari

**Comment by FSidorowicz** [comment]
Hi Hari,
thank you for quick action. The script counts used % properly. However, it gives the same output twice and it does not go deeper than 1 leaf under root. Can you also please modify the code so it would:
- not double the output
- go inside queues, for example we have multiple queues under root.users.

The current output:
OK: queue used capacity of total cluster: 'root.default' = 0.00%, 'root.batch' = 0.94%, 'root.users' = 2.95%, 'root.anon' = 49.95% | 'root.default'=0.00%;;; 'root.batch'=0.94%;;; 'root.users'=2.95%;;; 'root.anon'=49.95%;;;

**Comment by HariSekhon** [comment]
The output "doubling" is by design, everything after the pipe character is perfdata which Nagios or similar systems can use for Graphing (if you look closely the format is slightly different, and the perfdata after the pipe won't appear in your monitoring UI anyway).

I've just pushed an update to recurse, please git pull in the yarn_fair_scheduler_queue_check branch and try again.

Thanks

Hari

**Comment by FSidorowicz** [comment]
Thank you for very quick action. It looks good now. In the end I will try to finally run it via nagios. 

However, there is one issue - I have to provide json file manually and modify your code to read the file. Our cluster is secured (ssl + kerberos) so I have to use curl with additional flags and I can't get it working in your script (it gets compilation errors):
curl -k -i --negotiate -u : https://MY_RM_HOST:8090/ws/v1/cluster/scheduler

Additionally if it worked this curl generates additional lines before the proper json so we'll have "invalid json error". Can you also please make the plugin to be able to get this curl and cut those lines? I paste the curl's beginning:

HTTP/1.1 401 Authentication required
Cache-Control: must-revalidate,no-cache,no-store
Date: Wed, 04 Dec 2019 07:49:32 GMT
Pragma: no-cache
Date: Wed, 04 Dec 2019 07:49:32 GMT
Pragma: no-cache
Content-Type: text/html; charset=iso-8859-1
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Negotiate
Set-Cookie: hadoop.auth=; Path=/; Secure; HttpOnly
Content-Length: 1416

HTTP/1.1 200 OK
Cache-Control: no-cache
Expires: Wed, 04 Dec 2019 07:49:32 GMT
Date: Wed, 04 Dec 2019 07:49:32 GMT
Pragma: no-cache
Expires: Wed, 04 Dec 2019 07:49:32 GMT
Date: Wed, 04 Dec 2019 07:49:32 GMT
Pragma: no-cache
Content-Type: application/json
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Negotiate YGYGCSqGSIb3EgECAgIAb1cwVaADAgEFoQMCAQ+iSTBHoAMCAReiQAQ+blSoZEUqNMahllIVjKZr0zYXzaGC48G9QnWfSweVretz/uEGucPjezi4w2XsI3uNPl144fV/DLUq/Dav2+E=
Set-Cookie: hadoop.auth="u=hue&p=hue/ANONYMOUS_PRINCIPAL@AUSTRIA.LOCAL&t=kerberos-dt&e=1575481772037&s=YjOFb5GhxCqGZC+rOvcCLVOunZY="; Path=/; Secure; HttpOnly
Transfer-Encoding: chunked

{"scheduler":{"schedulerInfo":{"type":"fairScheduler","rootQueue":{"maxApps":214 ..................................................................

Thanks,
Filip

**Comment by HariSekhon** [comment]
If you `kinit` first and have LWP::Authen::Negotiate installed (part of the automated build), then it should just pick up the TGT from the environment and use it so that you don't have to bother with manual curl exports.

I've just enabled optional SSL support for you as well in the latest push to the new branch `yarn_fair_scheduler_queue_check`.

If you still want to use curl, you can strip the headers by piping through sed:

```
curl ...  | sed -n '/^{/,$p'
```

Lastly, modifying the code to read the file is simple, I did this to reproduce from your sample output, commenting out the curl function call around line 65:
```
#my $content = curl $url;
$/ = undef;
open my $fh, '<', 'cloudera_json.txt' or die;
my $content = <$fh>;
```

**Comment by FSidorowicz** [comment]
Hi Hari,
I don't think we solved an issue.  

I know how to use your script to read from a file and there is even easier way than "sed" command to filter proper jason - just tail -n 1 <file>.
However, what we want to achieve together is the possibility to use just your perl script, nothing more.

I'm not sure about the LWP::Authen::Negotiate thing, but please go through my concerns below:

So the issue is that your plugin now uses following command to get the json with queue usage:
* my $url = "$protocol://$host:$port/ws/v1/cluster/scheduler"; 
* my $content = curl $url;
This unfortunately is something I could do from hand as I could manually change "http" to "https" in older versions of your script. And it does not work because:

The real issue is that to get the json we can't just use "curl <url>". The curl has to have 2 options:
-to enable login to SSL without passing certs so "-k"
-to authenticate using valid kerberos ticket do "i --negotiate -u :" (the ticket must be available).

So can you change your script to use:
* NOT "curl <url>"
* YES "curl -k -i --negotiate -u : <url>"

And take just the last line of the JSON.  In my opinion this would work fine. Can you provide your feedback? 
Even if your solution with LWP::Authen::Negotiate might work it seems that "my way" is easier to achieve in my environment because it's just about passing different curl and taking only last line. 

Best regards,
Filip

**Comment by HariSekhon** [comment]
the `curl` in the code is not the `curl` command, but a perl function that automatically does the things you need based on the cli options and environment available.

The `--ssl-noverify` switch does the equivalent of `-k` in curl command.

The `-u : --negotiate` is done automatically by the curl function's underlying LWP library if there is a valid TGT from a prior `kinit` command.

You shouldn't need to modify any code to get this working.

Also, the `tail -n1` would break if the API changed to return multi-line json, whereas the sed will take every line from the line starting with an opening brace to signify start of json to the end of the content, which means it'll match single line json like now, or multi-line json should it ever change in future.

**Comment by FSidorowicz** [comment]
Hi Hari,

thanks for your input. But I am having "invalid json" error and I thought it is this curl issue.
Please see below outputs.

1) when I provide server FQDN (in your script line 56 and port in line 57) I get the below error. Adding a host to /etc/hosts does not work. Ping and telnet works with fqdn.

invalid host '[here is my fqdn]' defined: not a valid hostname or IP address

2) when I provide IP adress it does not work (via a browser it also does not work, it works with FQDN so option 1)). I also see "http" not "https". 

2019-12-05 14:06:19 +0100  verbose mode on

2019-12-05 14:06:19 +0100  final_plugin.pl version 0.2  =>  Hari Sekhon Utils version 1.19.5

2019-12-05 14:06:19 +0100  host:                     my_ip_is_here
2019-12-05 14:06:19 +0100  port:                     8090
2019-12-05 14:06:19 +0100
2019-12-05 14:06:19 +0100  setting timeout to 10 secs

2019-12-05 14:06:19 +0100  HTTP GET http://my_ip_is_here:8090/ws/v1/cluster/scheduler
** GET http://my_ip_is_here:8090/ws/v1/cluster/scheduler ==> 200 Assumed OK
2019-12-05 14:06:19 +0100  returned HTML:




2019-12-05 14:06:19 +0100  http status code:     200
2019-12-05 14:06:19 +0100  http status message:  Assumed OK

CRITICAL: invalid json returned by Yarn Resource Manager at 'http://my_ip_is_here:8090/ws/v1/cluster/scheduler'

**Comment by HariSekhon** [comment]
If you are using Kerberos then you need to specify the FQDN to match the service principal of the remote service, otherwise authentication will fail, this commonly doesn't work when using an IP / short hostname / alias etc.

You're probably hitting this line of code which doesn't recognize the host:

https://github.com/HariSekhon/lib/blob/master/HariSekhonUtils.pm#L1402

If you are using a custom internal top level domain name, then you'd need to add it to the list of valid TLDs as per the doc here (common ones such as .internal are already in there):

https://github.com/HariSekhon/lib#custom-tlds

**Comment by FSidorowicz** [comment]
This may be the cause. I added proper domain to the custom tlds file and I recieve below error:

TLD: 'MY_DOMAIN' from tld file '/usr/local/lib64/perl5/resources/custom_tlds.txt' not validated, skipping that TLD at /usr/local/lib64/perl5/HariSekhonUtils.pm line 659, <$tmpfh> line 23.

How to "validate" my TLD?

**Comment by HariSekhon** [comment]
That means the TLD you added to the file doesn't pass the regex validation for what a valid TLD can be and has been assumed to be an error in the file and that line ignored.

It's a defence against user error when editing the config.

See the regex validating the config input here:

https://github.com/HariSekhon/lib/blob/master/HariSekhonUtils.pm#L655

Did you accidentally add the whole domain name instead of just the `.last_bit` eg. `.com`, `.internal` etc?

**Comment by HariSekhon** [comment]
If your TLD contains non-alphanumeric characters I would be curious to know what that is.

If you look at the official internet IANA list of top level domains there is not one in that file which does not match the regex validation in the comment above. This is what TLDs should look like (comment lines starting with `#` are ignored of course as per general unix standards).

https://github.com/HariSekhon/lib/blob/master/resources/tlds-alpha-by-domain.txt

**Comment by FSidorowicz** [comment]
I had a dot (.) in the TLD, i just left the last string, my mistake sorry! It now goes through that step.
However, still it does not return any valid json (and it uses http):


2019-12-05 18:47:04 +0100  verbose mode on

2019-12-05 18:47:04 +0100  final_plugin.pl version 0.2  =>  Hari Sekhon Utils version 1.19.5

2019-12-05 18:47:04 +0100  host:                     my_host
2019-12-05 18:47:04 +0100  port:                     8090
2019-12-05 18:47:04 +0100
2019-12-05 18:47:04 +0100  setting timeout to 10 secs

2019-12-05 18:47:04 +0100  HTTP GET http://my_host:8090/ws/v1/cluster/scheduler
** GET http://my_host:8090/ws/v1/cluster/scheduler ==> 200 Assumed OK
2019-12-05 18:47:04 +0100  returned HTML:




2019-12-05 18:47:04 +0100  http status code:     200
2019-12-05 18:47:04 +0100  http status message:  Assumed OK

CRITICAL: invalid json returned by Yarn Resource Manager at 'http://my_host:8090/ws/v1/cluster/scheduler'

**Comment by HariSekhon** [comment]
Are you using the latest version from the yarn_fair_scheduler_queue_check branch??

Because my one with `--ssl` and `--debug` shows

```
./check_hadoop_yarn_queue_capacity.pl -H localhost --ssl --debug
2019-12-05 17:58:45 +0000  verbose mode on

2019-12-05 17:58:45 +0000  check_hadoop_yarn_queue_capacity.pl version 0.2  =>  Hari Sekhon Utils version 1.19.5

2019-12-05 17:58:45 +0000  host:                     localhost
2019-12-05 17:58:45 +0000  port:                     8088
2019-12-05 17:58:45 +0000  SSL enabled:              true
2019-12-05 17:58:45 +0000  SSL noverify:             false
2019-12-05 17:58:45 +0000  
2019-12-05 17:58:45 +0000  setting timeout to 10 secs

2019-12-05 17:58:45 +0000  HTTP GET https://localhost:8088/ws/v1/cluster/scheduler
...
```

**Comment by FSidorowicz** [comment]
Yes, but i have taken the code manually into my file. That is why you see different file name.

**Comment by FSidorowicz** [comment]
It finally seems to be an ssl config issues. With curl -k it worked. Maybe you can help here?

2019-12-05 20:11:57 +0100  verbose mode on

2019-12-05 20:11:57 +0100  final_plugin.pl version 0.2  =>  Hari Sekhon Utils version 1.19.5

2019-12-05 20:11:57 +0100  host:                     server
2019-12-05 20:11:57 +0100  port:                     8090
2019-12-05 20:11:57 +0100  SSL enabled:              true
2019-12-05 20:11:57 +0100  SSL noverify:             false
2019-12-05 20:11:57 +0100
2019-12-05 20:11:57 +0100  setting timeout to 10 secs

2019-12-05 20:11:57 +0100  HTTP GET https://server:8090/ws/v1/cluster/scheduler
** GET https://server:8090/ws/v1/cluster/scheduler ==> 500 Can't connect to vlbicat001.at.inside:8090 (certificate verify failed)
2019-12-05 20:11:57 +0100  returned HTML:

Can't connect to server:8090 (certificate verify failed)

SSL connect attempt failed with unknown error error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed at /usr/share/perl5/LWP/Protocol/http.pm line 51.


2019-12-05 20:11:57 +0100  http status code:     500
2019-12-05 20:11:57 +0100  http status message:  Can't connect to server:8090 (certificate verify failed)

CRITICAL: 500 Can't connect to server:8090 (certificate verify failed)

**Comment by HariSekhon** [comment]
I recommend you just take the latest version of plugin from the new branch and use `--ssl-noverify` which will solve that.

The code is written to be flexible enough that it shouldn't need users to edit to change anything, just use the command line switches like any regular linux coreutil.

**Comment by FSidorowicz** [comment]
Yes, with "noverify" parameter it works!!! Great job!  I'll try to add it to Nagios finally.
One more thing - regarding resource manager High Availability. Did you think of adding a support for HA in the plugin? Maybe just if the script would fail it could just run again for the second server?

**Comment by HariSekhon** [comment]
I have done that for other scripts eg. `check_hadoop_hdfs_webhdfs.pl` but upon reflection it's better to run this through a simple load balancer - configurations for which I have provided in the adjacent repo (which is also a submodule of this repo):

https://github.com/harisekhon/haproxy-configs

It's 1 command to set up the HAProxy and run the scripts through that for each service.

This drastically simplifies failover logic and modularizes everything, and HAProxy has a great stats page that shows what's up / down and has health checks which I've pre-configured in the configs. All you have to do is replace the server lines with the addresses of the servers, you could even run it locally on the nagios server.
