### ISSUE TITLE
check_yum displays wrong information

### ISSUE THREAD

**Issue by nofear87** [HariSekhon/Nagios-Plugins#242]
Please be as specific as possible when raising an issue.

Running yum update displays:

> No packages marked for update

the output from check_yum is

> YUM CRITICAL: 1 Security Update Available. 106 Non-Security Updates Available 

I try 

> yum clean all

 and 

> yum makecache

 without success. Any ideas?

**Comment by HariSekhon** [comment]
Hi @nofear87 

Thanks for raising this.

If you want post the debug output with `-vvv` I will try to upload a fix for it shortly.

Cheers

Hari

**Comment by nofear87** [comment]
`Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.8.8
Author: Hari Sekhon

setting plugin timeout to 60 seconds
running command: /usr/bin/yum --security check-update
Returncode: '100'
Output: 'Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: centosmirror.netcup.net
 * epel: mirror.23media.com
 * extras: mirror.23media.com
 * updates: centos.mirrors.as250.net
 --> libXxf86vm-1.1.4-1.el7.i686 from base excluded (updateinfo)
 --> libXxf86vm-1.1.4-1.el7.x86_64 from base excluded (updateinfo)
 --> libXxf86dga-devel-1.1.4-2.1.el7.i686 from base excluded (updateinfo)
 --> libXxf86dga-devel-1.1.4-2.1.el7.x86_64 from base excluded (updateinfo)
 --> libXxf86dga-1.1.4-2.1.el7.i686 from base excluded (updateinfo)
 --> libXxf86dga-1.1.4-2.1.el7.x86_64 from base excluded (updateinfo)
 --> libXxf86misc-devel-1.0.3-7.1.el7.i686 from base excluded (updateinfo)
 --> libXxf86misc-devel-1.0.3-7.1.el7.x86_64 from base excluded (updateinfo)
 --> libXxf86misc-1.0.3-7.1.el7.i686 from base exc
`

**Comment by nofear87** [comment]
the complete output seems to be to large for clipboard (24000 lines)

**Comment by HariSekhon** [comment]
Could you put it in a pastebin website / github gist or something and then put the link to it here?

If I can get your full output I can write you a fix locally.

**Comment by nofear87** [comment]
I dont understand why the plugin output is another then output from running from terminal.

I run: `yum --security check-update` and get result: `No packages needed for security; 0 packages available`

The output from running plugin with `-vvv` is 1 ` package(s) needed for security, out of 107 available`

I dont think that this is a problem with your code?

**Comment by nofear87** [comment]
https://gist.github.com/nofear87/f1464d52cd10ecbc43750e026328453a

**Comment by HariSekhon** [comment]
This part of your output:

```
 --> python2-ipaserver-4.6.5-11.el7.centos.3.noarch from updates excluded (updateinfo)
 --> 1:virt-dib-1.40.2-5.el7_7.1.x86_64 from updates excluded (updateinfo)
 --> firewall-applet-0.6.3-2.el7_7.1.noarch from updates excluded (updateinfo)
 --> tuned-utils-systemtap-2.11.0-5.el7_7.1.noarch from updates excluded (updateinfo)
1 package(s) needed for security, out of 107 available
```

says that yum is outputting there is indeed 1 security update available.

This might be an environment issue, are you running your yum command as root as well? Iirc you need to run as root to get the visibility of the security updates.

**Comment by nofear87** [comment]
`sudo yum update`: 

```
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.net
 * epel: ftp.plusline.net
 * extras: mirror.infonline.de
 * updates: centos.mirrors.as250.net
No packages marked for update
```

`sudo yum check-updates --security`: 

`No packages needed for security; 0 packages available`

`sudo yum check-updates` :

```
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.net
 * epel: ftp.plusline.net
 * extras: mirror.infonline.de
 * updates: centos.mirrors.as250.net
```

**Comment by nofear87** [comment]
its the same on 5 centos 7 machines....after the latest updates

**Comment by HariSekhon** [comment]
I see the problem, you're running the plugin in docker, which is reporting the status inside the CentOS OS of the docker container.

To get it to check the state of the host on which the docker container is running you'd need to mount the host's yum / rpm directories to be readable in the docker container, something like:

```
sudo docker run --rm -v /var/lib/yum:/var/lib/yum -v /var/lib/rpm:/var/lib/rpm -v /var/cache/yum:/var/cache/yum harisekhon/nagios-plugins check_yum.py -v -v -v
```

Tbh you don't really need to use docker for that check, that plugin has no dependencies so you can just copy the python script around to all your servers, that's what everyone else does.

**Comment by nofear87** [comment]
Yes, you are right. That was a fundamental misunderstanding. Thanks for your support!
