### ISSUE TITLE
check_zookeeper.pl: fails when %mntr keys check results in negative return values (-1)

### ISSUE THREAD

**Issue by hypnotortoise** [HariSekhon/Nagios-Plugins#28]
During checks of the return values from %mntr configuration settings, the script exits when the returned config result from zookeeper host is negative.

In our case this was occuring for the following %mntr keys:
UNKNOWN: invalid value found for mntr zk_open_file_descriptor_count '-1'
UNKNOWN: invalid value found for mntr zk_max_file_descriptor_count '-1'

I fixed the regex to also match negative results on line  236:

```
$mntr{$_} =~ /^[+-]?\d+$/ or quit "UNKNOWN", "invalid value found for mntr $_ '$mntr{$_}'";
```

**Comment by JulieSur** [comment]
I have received similar error in my Nagios script for 'zk_min_latency'. 
During checks of the return values from %mntr configuration settings, the script exits when the returned config result from zookeeper host is negative.
In our case this was occurring for the following %mntr keys:

UNKNOWN: invalid value found for mntr zk_min_latency '-681​'

**Comment by rexconsulting** [comment]
I also am seeing zk_min_latency reported in negative numbers. I've seen this in other application's instrumentation (ODSEE's cn=monitor counters) where it appears the value outgrows the variable type. I wonder if that's what's going on here.

**Comment by harisekhon** [comment]
@rexconsulting 

Let's move this discussion to the right ticket which addresses that scenario as this one was explained and patched to solve.

https://github.com/harisekhon/nagios-plugins/issues/51

**Comment by JulieSur** [comment]
I have reached out to my team for confirmation on what information I can share to replicate the issue.

**Comment by harisekhon** [comment]
@JulieSur Ok thanks. If information security is an issue you can anonymize any configs / log outputs using ```scrub.pl``` from my [Toolbox](https://github.com/harisekhon/toolbox) repo.

Make sure to follow up in ticket https://github.com/harisekhon/nagios-plugins/issues/51 though so there is a trail for that issue instead of piggybacking this one which was solved.

**Comment by JulieSur** [comment]
Thanks @harisekhon,
I have informed the team with details. I have also updated ticket#51.

**Comment by chrismichael22** [comment]
I'm also seeing zk_avg_latency making the check exit when having float values

Output from 'mntr':
=> zk_version   3.6.1--104dcb3e3fb464b30c5186d229e00af9f332524b, built on 04/21/2020 15:01 GMT
=> zk_server_state      follower
=> zk_peer_state        following - broadcast
=> zk_ephemerals_count  6
=> zk_min_latency       0
=> zk_avg_latency       2.2262
=> zk_num_alive_connections     3
=> zk_max_file_descriptor_count 1048576
=> zk_outstanding_requests      0
=> zk_approximate_data_size     16810
=> zk_znode_count       179
=> zk_open_file_descriptor_count        64
=> zk_global_sessions   6
=> zk_local_sessions    0
=> zk_uptime    2736438
=> zk_last_client_response_size 16
=> zk_max_latency       48
=> zk_packets_sent      1512
=> zk_outstanding_tls_handshake 0
=> zk_packets_received  1608
=> zk_max_client_response_size  1000
=> zk_connection_drop_probability       0.0
=> zk_watch_count       20
=> zk_min_client_response_size  16
=> zk_quorum_size       3
=> zk_proposal_count    0
=> zk_outstanding_changes_removed       0
=> zk_stale_requests_dropped    0
=> zk_large_requests_rejected   0
=> zk_connection_rejected       0
=> zk_sessionless_connections_expired   0
=> zk_looking_count     1
=> zk_dead_watchers_queued      0
=> zk_stale_requests    0
=> zk_connection_drop_count     106
=> zk_learner_proposal_received_count   861
=> zk_digest_mismatches_count   0
=> zk_dead_watchers_cleared     0
=> zk_response_packet_cache_hits        164
=> zk_bytes_received_count      64251
=> zk_add_dead_watcher_stall_time       0
=> zk_request_throttle_wait_count       0
=> zk_response_packet_cache_misses      19
=> zk_ensemble_auth_success     0
=> zk_prep_processor_request_queued     0
=> zk_learner_commit_received_count     861
=> zk_stale_replies     0
=> zk_connection_request_count  108
=> zk_ensemble_auth_fail        0
=> zk_diff_count        0
=> zk_response_packet_get_children_cache_misses 18
=> zk_connection_revalidate_count       0
=> zk_quit_leading_due_to_disloyal_voter        0
=> zk_snap_count        0
=> zk_unrecoverable_error_count 0
=> zk_commit_count      0
=> zk_stale_sessions_expired    0
=> zk_response_packet_get_children_cache_hits   34
=> zk_sync_processor_request_queued     861
=> zk_outstanding_changes_queued        0
=> zk_request_commit_queued     861
=> zk_ensemble_auth_skip        0
=> zk_tls_handshake_exceeded    0
=> zk_revalidate_count  0
...
mntr zk_approximate_data_size = 16810
mntr zk_avg_latency = 2.2262
UNKNOWN: invalid value found for mntr zk_avg_latency '2.2262'

The ideal check should be ^[+-]?([0-9]*[.])?[0-9]+$
