### ISSUE TITLE
docker image missing java and cassandra tools

### ISSUE THREAD

**Issue by ted3** [HariSekhon/Nagios-Plugins#330]
cassandra checks will not work without cassandra nodetool utility and without java

without java non-cassandra script functionality probably isn't all there either

i tried to map in my host /usr/bin and got nodetool to run, but java is still a dependency it fails on

either the image needs to be built to pull in host cassandra and java libraries or image should be built to contain all the libraries needed for scripts to run

[someuser@somehost]$ docker run -it -v /usr/bin:/usr/local/host/bin harisekhon/nagios-plugins bash
[root@7ddf84ccc046 nagios-plugins]# check_cassandra_nodes.pl 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
UNKNOWN: couldn't find 'nodetool' in $PATH (/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/cassandra/bin:/opt/cassandra/bin:/cassandra/bin)
[root@7ddf84ccc046 nagios-plugins]# java -version
bash: java: command not found
[root@7ddf84ccc046 nagios-plugins]# /usr/local/host/bin/nodetool 
which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/github/nagios-plugins)
Java executable not found (hint: set JAVA_HOME)

CentOS Linux release 7.5.1804 (Core)

**Comment by HariSekhon** [comment]
Yes I'm aware, this image used to have this but the docker image size started getting too big.

I've pushed a new larger image with Cassandra and Java installed for you to be able to use the nodetool plugins from the docker image. Please try

`harisekhon/nagios-plugins:cassandra`

**Comment by ted3** [comment]
thank you for quick response, trying that image now
