### ISSUE TITLE
check_mysql_query.pl error 

### ISSUE THREAD

**Issue by AgentZoy** [HariSekhon/Nagios-Plugins#337]
Hi i want to use your check for nagios
When I try run check from terminal I got error
CRITICAL: file not found: '/usr/share/perl5/resources/tlds-alpha-by-domain.txt'

How check is runned

./check_mariadb.pl -H localhost -P 3306 -u root -p pass -d information_schema -q 'select round(VARIABLE_VALUE/1024/1024) from information_schema.GLOBAL_STATUS where VARIABLE_NAME = "Memory_used";' -w 3000

OS debian 10 plus all latest updates

Cant understand how to fix

Info founded https://mariadb.com/resources/blog/advanced-mariadb-monitoring-with-nagios/

**Comment by HariSekhon** [comment]
You need to git clone the entire repository and keep it in one piece, the resource file is in the repo. See the Quick Start instructions.
