### ISSUE TITLE
check_whois.pl .fr domains seems not supported 

### ISSUE THREAD

**Issue by NegroTruc** [HariSekhon/Nagios-Plugins#357]
Hi,

When checking a .fr domain it gets the following error :
`UNKNOWN: expiry not found in output from whois sigma.fr`

And with option --name-servers (and --no-expiry) :
`WARNING: invalid status 'not identified,not identified,not identified,not identified,not identified,not identified' found!`

Maybe a problem of parsing. 

Thanks for the plugin !

**Comment by NegroTruc** [comment]
Update :
For the "expiry" problem, .fr whois uses "Expiry date:". It's not match by the script. I have added "Expiry" at line 379.

For the second problem, it wasn't a "nameservers" problem, but a "status" problem. There are many "status" type in the .fr whois. For exemple :
```
# jwhois google.fr | grep status
status:      ACTIVE
eligstatus:  ok
reachstatus: ok
eligstatus:  not identified
reachstatus: ok
eligstatus:  not identified
reachstatus: not identified
```

I don't really know what the "reachstatus" and "eligstatus" means so I will skip them... ¯\_(ツ)_/¯
I have changed the line 435 to only match the "status:" line (with a "^", it must start line), not the others. It's works.

**Comment by HariSekhon** [comment]
I've updated it and this now works for .fr domains again:

```shell
$ check_whois.pl -d sigma.fr 
OK: 352 days left for sigma.fr domain, expires '26-05-2023' | whois_query_time=0.0821s
```
