### ISSUE TITLE
cPanel - YUM check - unknown output

### ISSUE THREAD

**Issue by MrAlci** [HariSekhon/Nagios-Plugins#361]
Something going wrong when cPanel is installed.

Tested the same methode on a DirectAdmin server with the same specs
[root@deploytest4 plugins]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

Our monitoring throws a unknown notification.

UNKNOWN: exit code: 1, output: cPanel Addons Production Feed                   165  B/s

[root@deploytest4 plugins]# python3 /usr/lib64/nagios/plugins/check_yum -vvvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.11.3
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum --security check-update
Returncode: '0'
Output: 'Last metadata expiration check: 1:12:59 ago on Mon 01 Mar 2021 11:21:53 AM CET.
'
YUM OK: 0 Security Updates Available. 0 Non-Security Updates Available | security_updates_available=0 non_security_updates_available=0 total_updates_available=0

**Comment by HariSekhon** [comment]
I've just pushed a fix for DNF format changes, please git pull and try the latest version 12.3.

I've tested this on Rocky Linux 8, Alma Linux 8 and CentOS 8.
