### ISSUE TITLE
Yum output signature (1 unique lines) is larger than number of total updates (0) on CentOS7

### ISSUE THREAD

**Issue by tahitijul** [HariSekhon/Nagios-Plugins#365]
Hi, 

i had such warning when i execute check_yum.py (on last version too).
Here is in attachment the output of check_yum.py -vvv
[output.txt](https://github.com/HariSekhon/Nagios-Plugins/files/6250092/output.txt)

Thanks for your help.

Julien

**Comment by tahitijul** [comment]
Problem solved for me, by using info on the last line of output.txt :

No packages needed for security; 0 packages available

output lines not accounted for: ['Including mirror: centos.crazyfrogs.org', 'Including mirror: centos.mirror.fr.planethoster.net', 'Including mirror: ftp.pasteur.fr', 'Including mirror: mirrors.ircam.fr', 'Including mirror: distrib-coffee.ipsl.jussieu.fr', 'Including mirror: mirror.freethought-internet.co.uk', 'Including mirror: mirror.in2p3.fr', 'Including mirror: mirrors.ircam.fr', 'Including mirror: centos.crazyfrogs.org', 'Including mirror: miroir.univ-paris13.fr', 'Including mirror: centos.mirror.fr.planethoster.net', 'Including mirror: ftp.pasteur.fr', 'Including mirror: mirror.in2p3.fr', 'Including mirror: mirrors.ircam.fr', 'Including mirror: distrib-coffee.ipsl.jussieu.fr', 'Including mirror: centos.crazyfrogs.org', 'Including mirror: miroir.univ-paris13.fr', 'Including mirror: mirror.in2p3.fr', 'Including mirror: distrib-coffee.ipsl.jussieu.fr']

YUM WARNING: Yum output signature (1 unique lines) is larger than number of total updates (0). Please make sure you have upgraded to the latest version from https://github.com/harisekhon/nagios-plugins. If the problem persists, please raise a ticket at https://github.com/harisekhon/nagios-plugins/issues with the full -vvv output`

I add the sentences 'Including mirror' into check_yum (L453) :

449         excluded_regex = re.compile('|'.join(
450             [' from .+ excluded ',
451              r'^\s*\*\s*',
452              r'^\s*$',
453              **'Including mirror',** 
454              'Determining fastest mirrors',

I realize warning with check_yum.py happens only if there is no system update (just after yum -y update for example), it's OK if you have at least 1 update to do.  
I am not dev, don't know how to code and contribute to code, hope it helps.

**Comment by HariSekhon** [comment]
Thanks for raising this, I've just updated the code with this change.
