### ISSUE TITLE
check_yum.py Yum output signature (1 unique lines) is larger than number of total updates on Centos 7

### ISSUE THREAD

**Issue by ionoci** [HariSekhon/Nagios-Plugins#381]
Hi, 
we had an issue using katello-host-tools yum plugin for enabled repository report upload. The output confused check_yum.py.
Adding the output of the plugin "Uploading Enabled Repositories Report" to the excluded_regex, fixed the issue.
Perhaps you may include this in your code.

Kind regards
Ionoci

**Comment by HariSekhon** [comment]
Thanks, I've added that.
