### ISSUE TITLE
jwhois / whois

### ISSUE THREAD

**Issue by tetzispa** [HariSekhon/Nagios-Plugins#391]
Hey !

i tried to use your script, but it doesnt work because on debian 11 there is no "jwhois" but only whois. When i use the whois's path, it does not work neither.

could you update your script for whois instead jwhois (or add option to choose the whois we have/want) ?

thx a lot

**Comment by HariSekhon** [comment]
I don't currently use that script as I used to manage hundreds of domains but don't any more, so I'm not geared up to testing such a rewrite would work as well universally.

Plus the regex matching is quite sensitive to both ordering as well as matching, so I likely wouldn't change it until I'm ready to go all in on it again, but I have no current plans to do so as I'm off working on other things.

If possible, I'd recommend trying to download jwhois and use that.

**Comment by tetzispa** [comment]
you can close the case, i found an old deb jwhois package who works on debian 11 :D

sorry to bother you :)

**Comment by HariSekhon** [comment]
Sure, please post the link to the package you're using in case it's of interest to others.

**Comment by tetzispa** [comment]
ofc : i DL the package here : http://old.kali.org/kali/pool/main/j/jwhois/jwhois_4.0-2.1_i386.deb and the dependency there : http://ftp.fr.debian.org/debian/pool/main/g/gdbm/libgdbm3_1.8.3-14_i386.deb

**Comment by yakatz** [comment]
Tested on Ubuntu 22.04

That libgdm3 package is no longer available, but you can still get it from Launchpad:

Webpage: https://launchpad.net/ubuntu/bionic/amd64/libgdbm3/1.8.3-14  
Direct download: http://launchpadlibrarian.net/264797245/libgdbm3_1.8.3-14_amd64.deb

(You can get jwhois from there too: https://launchpad.net/ubuntu/xenial/amd64/jwhois/4.0-2.1ubuntu1 )

**Comment by yakatz** [comment]
You probably also want the most updated jwhois.conf: https://raw.githubusercontent.com/parseword/jwhois.conf/master/jwhois.conf
