### ISSUE TITLE
check_whois.pl is not recognizing expiry for *.name

### ISSUE THREAD

**Issue by pbiering** [harisekhon/nagios-plugins#40]
while whois of $DOMAIN.name provides expiry, it isn't recognized by check_whois.pl

$ whois google.name
[Querying whois.nic.name]
[whois.nic.name]
...
   Domain Name: GOOGLE.NAME
...
   Created On: 2010-06-17T00:46:09Z
   Expires On: 2015-06-17T00:46:12Z  <-!!!
   Updated On: 2014-05-16T09:23:05Z

Would be great if support can be added, thank you!

**Comment by harisekhon** [comment]
@pbiering 

Could you please provide -vvv output for your actual domain?

I have tried google.name with a couple of whois clients, the bsd whois on Mac and jwhois on Linux (which this plugin uses) and neither returns the expiry or created date information to check for google.name.

If you can give me the exact domain then I'll promptly make sure this plugin supports it where the information is available. It may be the case that Google's registration is more defensive than the domain you're trying to check...

Regards,

Hari

**Comment by pbiering** [comment]
Hi Hari,

> I have tried google.name with a couple of whois clients

CentOS 7 and Fedora 21 have installed:

$ whois --version
jwhois version 4.0, Copyright (C) 1999-2007  Free Software Foundation, Inc.
This program is free software with ABSOLUTELY NO WARRANTY; you may
redistribute it under the terms of the GNU General Public License.

$ rpm -qf `which whois`
jwhois-4.0-37.fc21.x86_64

$ rpm -qf `which whois`
jwhois-4.0-38.el7.x86_64

which is showing the output:

$ whois google.name |grep Expire
   Expires On: 2015-06-17T00:46:12Z

below the requested -vvv output

Hope this helps,
	Peter

# ./plugins-extra/check_whois.pl -vvv -d google.name
verbose mode on

check_whois.pl version 0.10.6  =>  Hari Sekhon Utils version 1.8.20

domain:                   google.name
warning  lower:           60
critical lower:           30

setting timeout to 10 secs

cmd: /bin/jwhois
output:

jwhois version 4.0, Copyright (C) 1999-2007  Free Software Foundation, Inc.
This program is free software with ABSOLUTELY NO WARRANTY; you may
redistribute it under the terms of the GNU General Public License.

Usage: jwhois [OPTIONS] [QUERY]
  --version                  display version number and patch level
  --help                     display this help
  -v, --verbose              verbose debug output
  -c FILE, --config=FILE     use FILE as configuration file
  -h HOST, --host=HOST       explicitly query HOST
  -n, --no-redirect          disable content redirection
  -s, --no-whoisservers      disable whois-servers.net service support
  -a, --raw                  disable reformatting of the query
  -i, --display-redirections display all redirects instead of hiding them
  -p PORT, --port=PORT       use port number PORT (in conjunction with HOST)
  -r, --rwhois               force an rwhois query to be made
  --rwhois-display=DISPLAY   sets the display option in rwhois queries
  --rwhois-limit=LIMIT       sets the maximum number of matches to return


Report bugs to bug-jwhois@gnu.org

exitcode: 0

setting timeout to 10 secs

cmd: /bin/jwhois -d google.name
output:

[Querying whois.nic.name]
[whois.nic.name]
Disclaimer: VeriSign, Inc. makes every effort to maintain the
completeness and accuracy of the Whois data, but cannot guarantee
that the results are error-free. Therefore, any data provided
through the Whois service are on an as is basis without any
warranties.
BY USING THE WHOIS SERVICE AND THE DATA CONTAINED
HEREIN OR IN ANY REPORT GENERATED WITH RESPECT THERETO, IT IS
ACCEPTED THAT VERISIGN, INC. IS NOT LIABLE FOR
ANY DAMAGES OF ANY KIND ARISING OUT OF, OR IN CONNECTION WITH, THE
REPORT OR THE INFORMATION PROVIDED BY THE WHOIS SERVICE, NOR
OMISSIONS OR MISSING INFORMATION. THE RESULTS OF ANY WHOIS REPORT OR
INFORMATION PROVIDED BY THE WHOIS SERVICE CANNOT BE RELIED UPON IN
CONTEMPLATION OF LEGAL PROCEEDINGS WITHOUT FURTHER VERIFICATION, NOR
DO SUCH RESULTS CONSTITUTE A LEGAL OPINION. Acceptance of the
results of the Whois constitutes acceptance of these terms,
conditions and limitations. Whois data may be requested only for
lawful purposes, in particular, to protect legal rights and
obligations. Illegitimate uses of Whois data include, but are not
limited to, unsolicited email, data mining, direct marketing or any
other improper purpose. Any request made for Whois data will be
documented by VeriSign, Inc. but will not be used for any commercial
purpose whatsoever.

For more information on Whois status codes, please visit
https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en.

 ****

   Domain Name ID: 5802011_DOMAIN_NAME-VRSN
   Domain Name: GOOGLE.NAME
   Sponsoring Registrar: MarkMonitor Inc.
   Sponsoring Registrar IANA ID: 292
   Domain Status: serverDeleteProhibited
   Domain Status: serverTransferProhibited
   Domain Status: serverUpdateProhibited
   Registrant ID: 3126226_CONTACT_NAME-VRSN
   Admin ID: 3126226_CONTACT_NAME-VRSN
   Tech ID: 3126226_CONTACT_NAME-VRSN
   Billing ID: 3126226_CONTACT_NAME-VRSN
   Name Server: NS1.GOOGLE.COM
   Name Server ID: 1024677_HOST_NAME-VRSN
   Name Server: NS2.GOOGLE.COM
   Name Server ID: 1024678_HOST_NAME-VRSN
   Name Server: NS3.GOOGLE.COM
   Name Server ID: 1024679_HOST_NAME-VRSN
   Name Server: NS4.GOOGLE.COM
   Name Server ID: 1024680_HOST_NAME-VRSN
   Created On: 2010-06-17T00:46:09Z
   Expires On: 2015-06-17T00:46:12Z
   Updated On: 2014-05-16T09:23:05Z

>>> Last update of whois database: 2015-01-17T14:29:55Z <<<

exitcode: 0

whois query returned in 0.1997 secs

Domain Name: GOOGLE.NAME
fqdn:                     NS1.GOOGLE.COM
fqdn:                     NS2.GOOGLE.COM
fqdn:                     NS3.GOOGLE.COM
fqdn:                     NS4.GOOGLE.COM
Excepting domain google.name from expiry check as we can't find the
expiry and it's a .name domain

created: '2010-06-17'
domain: 'GOOGLE.NAME'
registrar: 'MarkMonitor'
updated: '2015-01-17'
status: 'serverDeleteProhibited'
status: 'serverTransferProhibited'
status: 'serverUpdateProhibited'
name server: 'ns1.google.com'
name server: 'ns2.google.com'
name server: 'ns3.google.com'
name server: 'ns4.google.com'


extended command: ./check_whois.pl -vd google.name --no-expiry
--name-servers=ns1.google.com,ns2.google.com,ns3.google.com,ns4.google.com
--registrar="MarkMonitor"


CRITICAL: invalid status 'serverDeleteProhibited,serverUpdateProhibited'
found! EXPIRY NOT CHECKED for domain google.name,
nameservers:ns1.google.com,ns2.google.com,ns3.google.com,ns4.google.com
registrar:'MarkMonitor' created:2010-06-17 updated:2015-01-17 |
whois_query_time=0.1997s


Am 17.01.2015 um 15:19 schrieb Hari Sekhon:

**Comment by harisekhon** [comment]
@pbiering

Ok it turns out you have a slightly newer version of jwhois that returns that information, whereas the version I was testing didn't.

I've updated the plugin to work with .name domains. Please test and reopen this ticket if you encounter any more related issues.

Best Regards,

Hari
