### ISSUE TITLE
check_hadoop_balance.pl - UNKNOWN: self timed out after 10 seconds

### ISSUE THREAD

**Issue by szwed** [harisekhon/nagios-plugins#41]
Can anyone help me with the following issue? 

    hadoop@server:~$ /home/anpg/nagios-plugins/check_hadoop_balance.pl --hadoop-bin /home/yarn/hadoop/bin/hadoop --hadoop-user yarn -w 50 -c 80
    UNKNOWN: self timed out after 10 seconds

**Comment by harisekhon** [comment]
@szwed 

Please re-run with -vvv and paste full output back here.

How big is your Hadoop cluster?

Hari

**Comment by szwed** [comment]
My Hadoop cluster is rather tiny, just three small virtual machines without any load.

    hadoop@server:~/hadoop$ /home/anpg/nagios-plugins/check_hadoop_balance.pl -vvv --hadoop-bin /home/yarn/hadoop/bin/hadoop --hadoop-user hadoop -w 50 -c 80
    verbose mode on
    check_hadoop_balance.pl version 0.7.5  =>  Hari Sekhon Utils version 1.8.20
    checking HDFS balance
    warning  upper:           50
    critical upper:           80
    user:                     hadoop
    hadoop path:              /home/yarn/hadoop/bin/hadoop
    setting timeout to 10 secs
    fetching HDFS report
    cmd: /home/yarn/hadoop/bin/hadoop dfsadmin -report 2>&1
    UNKNOWN: self timed out after 10 seconds

Running the dfsadmin command manually results in:

    hadoop@server:~/hadoop$ time /home/yarn/hadoop/bin/hadoop dfsadmin -report 
    DEPRECATED: Use of this script to execute hdfs command is deprecated.
    Instead use the hdfs command for it.
    Configured Capacity: 8320901120 (7.75 GB)
    DFS Used: 147255296 (140.43 MB)
    Non DFS Used: 5000364032 (4.66 GB)
    DFS Remaining: 3173281792 (2.96 GB)
    DFS Used%: 1.77%
    DFS Remaining%: 38.14%
    Configured Cache Capacity: 0 (0 B)
    Cache Used: 0 (0 B)
    Cache Remaining: 0 (0 B)
    Cache Used%: 100.00%
    Cache Remaining%: 0.00%
    Xceivers: 1
    Last contact: Fri Jan 23 10:02:01 UTC 2015

    real    0m10.970s
    user    0m9.662s
    sys     0m0.984s
    hadoop@server:~/hadoop$ 

Which means that the hadoop/dfsc command takes more than 10 seconds... after increasing the timeout parameter all seems to be fine:

    hadoop@server:~/hadoop$ /home/anpg/nagios-plugins/check_hadoop_balance.pl --hadoop-bin /home/yarn/hadoop/bin/hadoop --hadoop-user hadoop -w 50 -c 80 -t 15
    OK: 2.45% HDFS imbalance on space used % across 3 datanodes | 'HDFS imbalance on space used %'=2.45%;50;80

So I see two possibilities there:
a) default timeout should be increased to some more reasonable value
b) my simple Hadoop cluster is slower than it should..  I am not an expert in the area - it can be the case that something is wrong with my cluster's configuration

Thanks for your help!

**Comment by harisekhon** [comment]
Actually the Nagios default was 10 secs, which is why high quality plugins
are supposed to default to 10 secs to self regulate themselves.

You can set -t 60 in your plugin command in Nagios but then you must
increase the Nagios global timeout to prevent Nagios from killing the
plugin itself.

Regards

Hari


On Friday, January 23, 2015, Piotr Szwed <notifications@github.com> wrote:

> My Hadoop cluster is rather tiny, just three small virtual machines
> without any load.
>
> hadoop@server:~/hadoop$ /home/anpg/nagios-plugins/check_hadoop_balance.pl -vvv --hadoop-bin /home/yarn/hadoop/bin/hadoop --hadoop-user hadoop -w 50 -c 80
> verbose mode oncheck_hadoop_balance.pl version 0.7.5  =>  Hari Sekhon Utils version 1.8.20
> checking HDFS balance
> warning  upper:           50
> critical upper:           80
> user:                     hadoop
> hadoop path:              /home/yarn/hadoop/bin/hadoop
> setting timeout to 10 secs
> fetching HDFS report
> cmd: /home/yarn/hadoop/bin/hadoop dfsadmin -report 2>&1
> UNKNOWN: self timed out after 10 seconds
>
> Running the dfsadmin command manually results in:
>
> hadoop@server:~/hadoop$ time /home/yarn/hadoop/bin/hadoop dfsadmin -report
> DEPRECATED: Use of this script to execute hdfs command is deprecated.
> Instead use the hdfs command for it.
> Configured Capacity: 8320901120 (7.75 GB)
> DFS Used: 147255296 (140.43 MB)
> Non DFS Used: 5000364032 (4.66 GB)
> DFS Remaining: 3173281792 (2.96 GB)
> DFS Used%: 1.77%
> DFS Remaining%: 38.14%
> Configured Cache Capacity: 0 (0 B)
> Cache Used: 0 (0 B)
> Cache Remaining: 0 (0 B)
> Cache Used%: 100.00%
> Cache Remaining%: 0.00%
> Xceivers: 1
> Last contact: Fri Jan 23 10:02:01 UTC 2015
>
> real    0m10.970s
> user    0m9.662s
> sys     0m0.984s
> hadoop@server:~/hadoop$
>
> Which means that the hadoop/dfsc command takes more than 10 seconds...
> after increasing the timeout parameter all seems to be fine:
>
> hadoop@server:~/hadoop$ /home/anpg/nagios-plugins/check_hadoop_balance.pl --hadoop-bin /home/yarn/hadoop/bin/hadoop --hadoop-user hadoop -w 50 -c 80 -t 15
> OK: 2.45% HDFS imbalance on space used % across 3 datanodes | 'HDFS imbalance on space used %'=2.45%;50;80
>
> So I see two possibilities there:
> a) default timeout should be increased to some more reasonable value
> b) my simple Hadoop cluster is slower than it should.. I am not an expert
> in the area - it can be the case that something is wrong with my cluster's
> configuration
>
> Thanks for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harisekhon/nagios-plugins/issues/41#issuecomment-71179257>
> .
>


-- 
Best Regards,

Hari Sekhon
http://www.linkedin.com/in/harisekhon

**Comment by szwed** [comment]
Seems like the current Nagios default is:
    service_check_timeout=60

So this shouldn't be an issue. Thanks anyway ! :)

**Comment by szwed** [comment]
Actually, you are right :)  I had to increase the default check_nrpe timeout as well (by modifying check_nrpe command definition).
