### ISSUE TITLE
check_hadoop_datanodes_block_balance.pl throws CRITICAL: Illegal division by zero

### ISSUE THREAD

**Issue by szwed** [harisekhon/nagios-plugins#42]
Stacktrace:

    datanode node01 has 2 blocks
    datanode node02 has 2 blocks
    datanode node03 has 0 blocks
    max blocks on a single datanode = 2
    min blocks on a single datanode = 0
    CRITICAL: Illegal division by zero at /home/anpc/nagios-plugins/check_hadoop_datanodes_block_balance.pl line 556.

**Comment by harisekhon** [comment]
I've just pushed a fix, please retry.

This is really because you're testing on a toy cluster with an edge condition where a datanode has zero blocks.

Regards,

Hari

**Comment by harisekhon** [comment]
@szwed I didn't hear back from you so I will close this ticket. Please re-open if needed.

Regards,

Hari
