### ISSUE TITLE
check_whois.pl throws segmentation fault

### ISSUE THREAD

**Issue by marcin-github** [harisekhon/nagios-plugins#43]
Hi!

When I tried to use mentioned plugin I got:
"$ ./check_whois.pl -d wp.pl
OK: Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 367.
Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 368.
Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 369.
Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 370.
Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 451.
Global symbol "$domain_regex2" requires explicit package name at ./check_whois.pl line 589.
Execution of ./check_whois.pl aborted due to compilation errors.
Segmentation fault (core dumped)
`
gdb shows:
`Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/perl -T ./check_whois.pl -d wp.pl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Perl_pp_enteriter () at pp_ctl.c:2164
2164                SvGETMAGIC(sv);
(gdb) bt
#0  Perl_pp_enteriter () at pp_ctl.c:2164
#1  0x000002b4b496d69b in Perl_runops_standard () at run.c:42
#2  0x000002b4b4905c44 in S_run_body (oldscope=1) at perl.c:2467
#3  perl_run (my_perl=<optimized out>) at perl.c:2383
#4  0x0000003c7a546edd in main (argc=5, argv=0x3b9955d8d78, env=0x3b9955d8da8) at perlmain.c:114
(gdb) bt full
#0  Perl_pp_enteriter () at pp_ctl.c:2164
        sv = 0x1761
        right = 0x2b4b4a486c0 <PL_sv_undef>
        maybe_ary = 0x2b4b4a486c0 <PL_sv_undef>
        sp = 0x3c7d0b47d0
        mark = 0x3c7d0b47e0
        cx = 0x3c7cd71420
        gimme = 1
        itervar = 0x3c7cd6e390
        cxtype = <optimized out>
#1  0x000002b4b496d69b in Perl_runops_standard () at run.c:42
        op = <optimized out>
#2  0x000002b4b4905c44 in S_run_body (oldscope=1) at perl.c:2467
No locals.
#3  perl_run (my_perl=<optimized out>) at perl.c:2383
        oldscope = 1
        ret = <optimized out>
        cur_env = {je_prev = 0x2b4b4a48000 <PL_start_env>, je_buf = {{__jmpbuf = {0, -1182142501882884752, 0, 4095609769328, 0, 0, -1182142501782221456,
                -1332383570017448592}, __mask_was_saved = 0, __saved_mask = {__val = {2975147823336, 259792495216, 2975146342032, 4095609769328, 0, 0,
                  4095609768928, 2975147224662, 4095609768928, 5817721573786848768, 2199023255554, 5817721573786848768, 2975146342032, 5817721573786848768,
                  4095609768976, 0}}}}, je_ret = 0, je_mustcatch = false}
#4  0x0000003c7a546edd in main (argc=5, argv=0x3b9955d8d78, env=0x3b9955d8da8) at perlmain.c:114
        exitstatus = <optimized out>
        i = <optimized out>
`

I'm not sure I should fill bug here or fill bug for perl team.
Perl-5.18.2, gentoo.

**Comment by harisekhon** [comment]
Did you run 'make update' or ensure you did a 'git submodule update' and
not just a 'git pull'?

The first error that cascades is telling you that $domain_regex2 is not
defined - that was defined in a more recent version of my library which is
included via git submodule so it looks like you haven't fetched the latest
version of the library dependency which is handled automatically via 'make
update'.

Regards

Hari


On Saturday, January 24, 2015, Marcin <notifications@github.com> wrote:

> Hi!
>
> When I tried to use mentioned plugin I got:
> "$ ./check_whois.pl -d wp.pl
> OK: Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 367.
> Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 368.
> Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 369.
> Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 370.
> Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 451.
> Global symbol "$domain_regex2" requires explicit package name at ./
> check_whois.pl line 589.
> Execution of ./check_whois.pl aborted due to compilation errors.
> Segmentation fault (core dumped)
>
> gdb shows:
> Using host libthread_db library "/lib64/libthread_db.so.1".
> Core was generated by /usr/bin/perl -T ./check_whois.pl -d wp.pl'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0 Perl_pp_enteriter () at pp_ctl.c:2164
> 2164 SvGETMAGIC(sv);
> (gdb) bt
> #0 Perl_pp_enteriter () at pp_ctl.c:2164
> #1 0x000002b4b496d69b in Perl_runops_standard () at run.c:42
> #2 0x000002b4b4905c44 in S_run_body (oldscope=1) at perl.c:2467
> #3 perl_run (my_perl=<optimized out>) at perl.c:2383
> #4 0x0000003c7a546edd in main (argc=5, argv=0x3b9955d8d78,
> env=0x3b9955d8da8) at perlmain.c:114
> (gdb) bt full
> #0 Perl_pp_enteriter () at pp_ctl.c:2164
> sv = 0x1761
> right = 0x2b4b4a486c0 <PL_sv_undef>
> maybe_ary = 0x2b4b4a486c0 <PL_sv_undef>
> sp = 0x3c7d0b47d0
> mark = 0x3c7d0b47e0
> cx = 0x3c7cd71420
> gimme = 1
> itervar = 0x3c7cd6e390
> cxtype = <optimized out>
> #1 0x000002b4b496d69b in Perl_runops_standard () at run.c:42
> op = <optimized out>
> #2 0x000002b4b4905c44 in S_run_body (oldscope=1) at perl.c:2467
> No locals.
> #3 perl_run (my_perl=<optimized out>) at perl.c:2383
> oldscope = 1
> ret = <optimized out>
> cur_env = {je_prev = 0x2b4b4a48000 <PL_start_env>, je_buf = {{__jmpbuf =
> {0, -1182142501882884752, 0, 4095609769328, 0, 0, -1182142501782221456,
> -1332383570017448592}, __mask_was_saved = 0, __saved_mask = {__val =
> {2975147823336, 259792495216, 2975146342032, 4095609769328, 0, 0,
> 4095609768928, 2975147224662, 4095609768928, 5817721573786848768,
> 2199023255554, 5817721573786848768, 2975146342032, 5817721573786848768,
> 4095609768976, 0}}}}, je_ret = 0, je_mustcatch = false}
> #4 0x0000003c7a546edd in main (argc=5, argv=0x3b9955d8d78,
> env=0x3b9955d8da8) at perlmain.c:114
> exitstatus = <optimized out>
> i = <optimized out>
>
> I'm not sure I should fill bug here or fill bug for perl team.
> Perl-5.18.2, gentoo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harisekhon/nagios-plugins/issues/43>.
>


-- 
Best Regards,

Hari Sekhon
http://www.linkedin.com/in/harisekhon

**Comment by marcin-github** [comment]
Yeah, you are right, after updating submodule everything works, thank you.

**Comment by harisekhon** [comment]
This is documented on the 1 readme page btw...


On Sunday, January 25, 2015, Marcin <notifications@github.com> wrote:

> Yeah, you are right, after updating submodule everything works, thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harisekhon/nagios-plugins/issues/43#issuecomment-71386520>
> .
>


-- 
Best Regards,

Hari Sekhon
http://www.linkedin.com/in/harisekhon
