### ISSUE TITLE
Yet another GoDaddy WHOIS Format Change

### ISSUE THREAD

**Issue by yakatz** [harisekhon/nagios-plugins#44]
GoDaddy added `--` in some of their domain statuses.
Plugin says `CRITICAL: invalid status 'clientDeleteProhibited --,clientRenewProhibited --,clientTransferProhibited --,clientUpdateProhibited --' found!  413 days left for shomershabbatscouting.org domain, expires '01-04-2016'` (so it does give the correct expire date, but it still has a critical error).

Sample domain: shomershabbatscouting.org
> Domain Name:SHOMERSHABBATSCOUTING.ORG
> Domain ID: D165173765-LROR
> Creation Date: 2012-04-01T20:45:33Z
> Updated Date: 2014-04-11T00:44:58Z
> Registry Expiry Date: 2016-04-01T20:45:33Z
> Sponsoring Registrar:GoDaddy.com, LLC (R91-LROR)
> Sponsoring Registrar IANA ID: 146
> WHOIS Server: 
> Referral URL: 
> Domain Status: clientDeleteProhibited -- http://www.icann.org/epp#clientDeleteProhibited
> Domain Status: clientRenewProhibited -- http://www.icann.org/epp#clientRenewProhibited
> Domain Status: clientTransferProhibited -- http://www.icann.org/epp#clientTransferProhibited
> Domain Status: clientUpdateProhibited -- http://www.icann.org/epp#clientUpdateProhibited
> Registrant ID:CR109443829
> Registrant Name:Brent Powers
> [[Truncated for issue entry, but registrant data is here]]

**Comment by harisekhon** [comment]
@yakatz I've just pushed a fix but can't test it right now, please try and let me know.

Thanks

Hari

**Comment by harisekhon** [comment]
I've tested this against that domain now and it fixes the issue so I'm going to close this ticket. Please reopen if needed.

Thanks

Hari

**Comment by yakatz** [comment]
Thanks. Just tested - works great.
