### ISSUE TITLE
check_kafka.pl topic not found (normal) and error when -vv debugging all topics when finding a topic with a dot in the name

### ISSUE THREAD

**Issue by Tamerkadan** [harisekhon/nagios-plugins#52]
HI Hari and thanks for the help, 

Am working to integrate some of the nagios-plugins you are using to icinga2 software,
As am new at this, am configurating the plugin and running it at the Kafka server to check the result and this what am having. 

CRITICAL: Error: There are no known brokers: topic = 'nagios'

/usr/lib64/nagios/plugins/check_kafka.pl -H 127.0.0.1 -P 9092 -B 127.0.0.1:9092 -vvv

The command give this error of :

CRITICAL: Error: There are no known brokers: topic = 'nagios'

for the -vvv option its working with passing all the check and have this

topic participant.action:
UNKNOWN: 'participant.action' 'participant' field not found. API may have changed.

**Comment by harisekhon** [comment]
@Tamerkadan 

Can you please paste the full output of ```-vvv``` - that is with three V so I can see the full output?

The first error is looks like you're using the default topic of 'nagios' and that topic doesn't exist.

In the second case it looks like your topic is 'participant.action' although I'm not sure how you'd be allowed with that given there is a regex filter for strictly alphanumeric topics. Did you edit the code?

In any case using three `-v` and pasting the full output will help me see what is happening so I can debug it. If you are concerned about anonymizing things you can use ```scrub.pl``` on that output - which you can find in my [Toolbox](https://github.com/harisekhon/toolbox) repo.

**Comment by Tamerkadan** [comment]
By the way i didn't touch the code :+1: 

/usr/lib64/nagios/plugins/check_kafka.pl -H 127.0.0.1 -P 9092 -vvv
verbose mode on

check_kafka.pl version 0.2  =>  Hari Sekhon Utils version 1.12.9

host:                     127.0.0.1
port:                     9092
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 127.0.0.1:9092

Metadata:

topic final:
		Partition: 0        Replicas: 1          ISR: 1          Leader: 1
		Partition: 1        Replicas: 1          ISR: 1          Leader: 1
		Partition: 2        Replicas: 1          ISR: 1          Leader: 1
		Partition: 3        Replicas: 1          ISR: 1          Leader: 1
		Partition: 4        Replicas: 1          ISR: 1          Leader: 1
		Partition: 5        Replicas: 1          ISR: 1          Leader: 1
		Partition: 6        Replicas: 1          ISR: 1          Leader: 1
		Partition: 7        Replicas: 1          ISR: 1          Leader: 1

topic participant.action:
UNKNOWN: 'participant.action' 'participant' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

**Comment by harisekhon** [comment]
Right, I see what's happening. There is a topic with a dot in the name which is found when attempting to traverse all topics in debug mode, which is not allowed as it's field separator. I've escaped that as well as allowing dots in the names of supplied --topic and pushed the latest version which should get past this for you.

You can also use ```--list-topics``` to concisely list the topics that are present and can be passed to ```--topic``` since that topic of 'nagios' that it tries by default obviously doesn't exist.

Please git pull and try to the latest version and let me know if I can close this ticket.

Thanks

Hari

**Comment by Tamerkadan** [comment]
Its now working with --list-topics to show all the topics with info like Partition/replicas,isr,leader perfectly.
You can close the bug, 
But what is the best syntax to use for monitoring kafka ? can you give me an examples ?

**Comment by harisekhon** [comment]
Other than --host/--port/--broker-list you pretty much just need --topic and run it with different --partitions if there is more than one partition in the topic, it will write to and read back from the topic to check Kafka is working end-to-end for that topic + partition. Everything else is optional.
