### ISSUE TITLE
Check_zookeeper plugin no results 

### ISSUE THREAD

**Issue by Tamerkadan** [harisekhon/nagios-plugins#53]
Once running the zookeeper plugin it don't give any results,

usr/lib64/nagios/plugins/check_zookeeper.pl -H 127.0.0.1 -w 1000 -c 20000 --port 2181

The command don't give any result ...

for the -vv option its working with passing all the checks .

Can you please advice how to fix such issue? 
what example of syntax need to use ?

**Comment by harisekhon** [comment]
@Tamerkadan 

Can you please paste the output in both cases so I have something to debug?

**Comment by Tamerkadan** [comment]
/usr/lib64/nagios/plugins/check_zookeeper.pl -H 127.0.0.1 -P 2181 -w 10000 -c 500000 -vvv
verbose mode on

check_zookeeper.pl version 0.8  =>  Hari Sekhon Utils version 1.12.9

host:                     127.0.0.1
port:                     2181
outstanding requests warning upper: 0
outstanding requests critical upper: 10
warning  upper:           10000
critical upper:           500000
setting timeout to 10 secs

connecting to 127.0.0.1:2181
OK connected
sending request: 'ruok'
sent request:    'ruok'
ruok response  = 'imok'

connecting to 127.0.0.1:2181
OK connected
sending request: 'isro'
sent request:    'isro'
isro response  = 'rw'

connecting to 127.0.0.1:2181
OK connected
sending request: 'wchs'
sent request:    'wchs'

Output from 'wchs':
=> 0 connections watching 0 paths
=> Total watches:0
wchs connections = 0
wchs paths = 0
wchs total_watches = 0

connecting to 127.0.0.1:2181
OK connected
sending request: 'srvr'
sent request:    'srvr'

Output from 'srvr':
=> Zookeeper version: 3.4.6-1569965, built on 02/20/2014 09:09 GMT
=> Latency min/avg/max: 0/0/34
=> Received: 82526
=> Sent: 82525
=> Connections: 1
=> Outstanding: 0
=> Zxid: 0x300154b5f
=> Mode: follower
=> Node count: 186

srvr Latency avg = 0
srvr Latency max = 34
srvr Latency min = 0
srvr Mode = follower
srvr Node count = 186
srvr Outstanding = 0
srvr Received = 82526
srvr Sent = 82525
srvr Zookeeper version = 3.4.6-1569965, built on 02/20/2014 09:09 GMT
srvr Zxid = 0x300154b5f

**Comment by harisekhon** [comment]
It looks like the output is truncated there should be an ending message prefixed with OK: / WARNING: / CRITICAL:.

What is the output when run without any -v switches?

Are you saying you see blank output when not using -v ? You should see a one line output as one line corresponds to Nagios standards and should work with all versions of Nagios & Icinga.

You should see output like the following:
```
OK: ZooKeeper Mode follower, avg latency 0, outstanding requests 0, version 3.4.6-2--1, built on 03/31/2015 19:31 GMT (state file wasn't found, stats will be available from next run)
```
The first runs builds state locally to compare with successive runs to find the rate of change for some additional stats. The second run onwards outputs those additional stats
```
OK: ZooKeeper Mode follower, avg latency 0, outstanding requests 0, version 3.4.6-2--1, built on 03/31/2015 19:31 GMT | 'zk_outstanding_requests/sec'=0 'zk_packets_received/sec'=2 'zk_packets_sent/sec'=2 zk_approximate_data_size=16145985 zk_avg_latency=0 zk_ephemerals_count=8 zk_max_file_descriptor_count=32000 zk_max_latency=7830 zk_min_latency=0 zk_open_file_descriptor_count=67 zk_outstanding_requests=0;0;10; zk_packets_received=504785 zk_packets_sent=504975 zk_watch_count=6579 zk_znode_count=7794 wchs_connections=3 wchs_paths=6575 wchs_total_watches=6575
```

**Comment by harisekhon** [comment]
@Tamerkadan 

Is that the output you're getting on the command line or from Icinga UI? It's possible Icinga caps the long -vvv output so I don't see the last end result OK/CRITICAL message and maybe you're not noticing the one liner output when not using -vv?

**Comment by Tamerkadan** [comment]
Am running it in the command line of the zookeeper, the strange thing that no result when running it,its just blank.

Maybe the (check_zookeeper.pl -H 127.0.0.1 -P 2181 -w 10000 -c 500000) is not a good syntax for it ?

**Comment by harisekhon** [comment]
I  noticed you're using 0.8 but what's strange is that 'srvr' hasn't been used since 0.5 according to my git log. I recommend the following before trying again:

```rm check_zookeeper.pl
git checkout master
git pull
git submodule update```

and check that those commands worked before trying again.

**Comment by Tamerkadan** [comment]
Its now working perfect ! thanks ! maybe its a bug also ?

**Comment by harisekhon** [comment]
'srvr' implies such an old version that a lot has changed since those days, srvr got replaced more than 2 years ago... I'm not sure if it was a bug or not, but more interesting is how it could claim to be version 0.8 and be using 'srvr' from 0.5, something was likely wrong in the local environment for that to be the case. Anyway, glad it's working, I'll close this ticket.

**Comment by Tamerkadan** [comment]
Perfect ! @harisekhon 
Something that i can't find, storm and couchbase plugin is not supported by nagios ? 
because no plugin for them at the official site nor your set of plugins

**Comment by harisekhon** [comment]
@Tamerkadan 

I haven't finished the Storm plugin... will be a while it's on the backlog. Couchbase has a Memcached API so you can use:
```
check_memcached_key.pl
check_memcached_stats.pl
check_memcached_write.pl
```

check_couchbase_* are currently symlinked to check_memcached_*:
```
check_couchbase_key.pl -> check_memcached_key.pl
check_couchbase_write.pl -> check_memcached_write.pl
check_couchbase_write_replication.pl -> check_memcached_write.pl
```
There is extra support for writing to one site and reading back from another when using ```check_couchbase_write_replication.pl ``` the code detects and exposes extra ```--slave``` and ```--slave-delay``` switches for checking Couchbase XDCR cross datacenter replication is working, where it writes to ```--host``` and reads back from remote ```--slave```.

It's also on the TODO list to add more Couchbase plugins . There's so many cool programs I haven't finished or haven't QA'd enough to release to this collection yet... you'll have to stay tuned.

If you can raise requests in separate tickets for each technology and plugin that would be helpful. Each plugin must try to do one thing and do it well, so separate tickets is necessary, not just a ticket for say "Couchbase" as a general term but what exactly you want a specific Couchbase plugin to check and preferably how (eg. Couchbase Views API or Couchbase metrics). We should continue this discussion in to those more specific tickets.

**Comment by Tamerkadan** [comment]
I will open separate tickets for such plugins.

Thanks a lot @harisekhon

**Comment by Tamerkadan** [comment]
@harisekhon  i can't find the open request for new plugin, i would like to test the storm plugin as am not finding anyone who created such plugin
