### ISSUE TITLE
Question: check_linux_timezone.pl

### ISSUE THREAD

**Issue by robayer** [harisekhon/nagios-plugins#55]
How can we get around this?:

```
# date
Mon Jun 29 12:34:57 CDT 2015

# /usr/lib64/nagios/plugins/nagios-advanced-plugins/check_linux_timezone.pl -T "US/Central"
CRITICAL: timezone is 'CDT' (expected: 'US/Central'), '/etc/localtime' is a symlink!

# cat /etc/sysconfig/clock 
ZONE="US/Central"

# /usr/lib64/nagios/plugins/nagios-advanced-plugins/check_linux_timezone.pl -T "CDT"
timezone does not appear to be valid, timezone file '/usr/share/zoneinfo/CDT' not found
```
I was not successful in using -L but I believe that was the intention of the flag.

Thanks

**Comment by harisekhon** [comment]
@robayer 

Have you tried using the -A flag since that is to allow for a daylight saving time zone change without tripping the check?

**Comment by robayer** [comment]
Ok - that works but can I avoid the WARN condition with a symlink?

/usr/lib64/nagios/plugins/nagios-advanced-plugins/check_linux_timezone.pl
-T "US/Central" -A "CDT"
WARNING: timezone is 'CDT', '/etc/localtime' is a symlink!

Many thanks.



On Tue, Jun 30, 2015 at 2:44 AM, Hari Sekhon <notifications@github.com>
wrote:

> @robayer <https://github.com/robayer>
>
> Have you tried using the -A flag since that is to allow for a daylight
> saving time zone change without tripping the check?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harisekhon/nagios-plugins/issues/55#issuecomment-117097772>
> .
>



-- 
Rob Ayer
360-531-1823

**Comment by harisekhon** [comment]
@robayer 

I've just pushed a new version which has --no-warn-symlinks option. Make sure to do ```make update``` to get the updated git submodule reference too as I'm using a new function.

**Comment by harisekhon** [comment]
@robayer 

I haven't heard back from you so I'm closing this ticket. Feel free to re-open it if needed.

Thanks

Hari
