### ISSUE TITLE
Can't locate Net/DNS.pm in @INC

### ISSUE THREAD

**Issue by pl33g0r** [harisekhon/nagios-plugins#59]
When I am trying to run ./check_dns.pl I am getting the following error:

./check_dns.pl
Can't locate Net/DNS.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./check_dns.pl line 23.
BEGIN failed--compilation aborted at ./check_dns.pl line 23. 
It appears that this error is related to missing Perl CPAN modules. Do you have nay instructions on downloading and installing this module?

**Comment by harisekhon** [comment]
The instructions are here:

https://github.com/harisekhon/nagios-plugins#quick-setup

**Comment by harisekhon** [comment]
@pl33g0r 

Did this solve your issue? Just running the ```make``` command as documented in the quick start should install all the modules required for all the plugins.

**Comment by Tamerkadan** [comment]
Its strange, am installing Kafka plug-in now again within fresh machine and its giving CRITICAL: Can't locate Kafka.pm in @INC , installed it via make with the quick guide and still now working :/

**Comment by pl33g0r** [comment]
Looks good at the moment! Thanks for such an amazing work on all plugins!

**Comment by pl33g0r** [comment]
@Tamerkadan 
Can you post related logs on the client's end? When you run check locally are you getting any output?

**Comment by Tamerkadan** [comment]
Hi,

The issue that am having, am installing the plugins+all required Perl modules from CPAN
with quick guide like this(centos 7):
git clone https://github.com/harisekhon/nagios-plugins
cd nagios-plugins
make

but once i use start testing the kafka plugin or zookeeper one, it asks me to add a lot of repos like syslog/HariSekhonUtils.pm/tlds-alpha-by-domain.txt and kafka.pm manually every time

now am having at this alert: CRITICAL: Can't locate Kafka.pm in @INC (@INC contains: /usr/lib64/nagios/plugins/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/lib64/nagios/plugins/check_kafka.pl line 41.

what am doing wrong with the instructions ?

**Comment by Tamerkadan** [comment]
@pl33g0r what do you suggest?

**Comment by harisekhon** [comment]
@Tamerkadan 

Some modules may fail to install but the build does not stop for them. Also you should not copy the plugins out of the git repo as there are other dependencies such as the tlds file which is incorporated in to a regex for domain validation.

Can you paste the output of running ```cpan Kafka```?

**Comment by harisekhon** [comment]
@Tamerkadan 

Any update on this? This isn't really a software problem, it's more of a generic environment setup issue to install Perl CPAN modules on your system, so I'm inclined to close this unless you want me to help you work through it in which case I need to see the output of ```cpan Kafka``` etc.

**Comment by Tamerkadan** [comment]
Hi @harisekhon  
The envirmoent for testing is down so i can't test it.
But if you can install the plugins at fresh centos server you will see a lot of missing files for unkown reason.

Thanks Hari for helping!

**Comment by harisekhon** [comment]
The build has been working for me and others for a long time. I'm going to close this for now, but you can reopen it if you get access to your test environment and want to continue debugging this.
