### ISSUE TITLE
check_mysql_query doesnt work if username has underscore

### ISSUE THREAD

**Issue by jorfermo** [harisekhon/nagios-plugins#61]
/usr/lib/nagios/plugins/check_mysql_query.pl -u test_user -H test.com
invalid username defined: must be alphanumeric

**Comment by harisekhon** [comment]
I've just extended the user name matching to permit underscores in the middle of user names.

Please run ```make update``` and try again, that should work for your scenario now.

**Comment by harisekhon** [comment]
@jorfermo 

Did you get a chance to try the update to solve this?

**Comment by jorfermo** [comment]
Yes, sorry for the delay.

It's working now, thank you!
