### ISSUE TITLE
check_solrcloud_cluster_status.pl Cluster status shows warning when replicas are not up to date (by design, consider showing more info)

### ISSUE THREAD

**Issue by arkadicolson** [HariSekhon/nagios-plugins#64]
When running:
check_solrcloud_cluster_status.pl -H solr20-dcg

the output looks like this:
WARNING: SolrCloud shard replicas down: collection 'messages' shard 'shard11', query time 161ms, QTime 37ms | query_time=161ms;;; query_QTime=37ms

while the clusterstatus xml looks like this:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">32</int>
</lst>
<lst name="cluster">
<lst name="collections">
<lst name="lvs">...</lst>
<lst name="messages">
<lst name="shards">
<lst name="shard1">
<str name="range">80000000-9744ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node1">
<str name="state">active</str>
<str name="core">messages_shard1_replica1</str>
<str name="node_name">solr20-dcg:8983_solr</str>
<str name="base_url">http://solr20-dcg:8983/solr</str>
</lst>
<lst name="core_node12">
<str name="state">active</str>
<str name="core">messages_shard1_replica2</str>
<str name="node_name">solr20-gs:8983_solr</str>
<str name="base_url">http://solr20-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard2">
<str name="range">97450000-ae8affff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node2">
<str name="state">active</str>
<str name="core">messages_shard2_replica1</str>
<str name="node_name">solr21-dcg:8983_solr</str>
<str name="base_url">http://solr21-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node13">
<str name="state">recovering</str>
<str name="core">messages_shard2_replica2</str>
<str name="node_name">solr21-gs:8983_solr</str>
<str name="base_url">http://solr21-gs:8983/solr</str>
</lst>
</lst>
</lst>
<lst name="shard3">
<str name="range">ae8b0000-c5d0ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node5">
<str name="state">active</str>
<str name="core">messages_shard3_replica1</str>
<str name="node_name">solr22-dcg:8983_solr</str>
<str name="base_url">http://solr22-dcg:8983/solr</str>
</lst>
<lst name="core_node14">
<str name="state">active</str>
<str name="core">messages_shard3_replica2</str>
<str name="node_name">solr22-gs:8983_solr</str>
<str name="base_url">http://solr22-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard4">
<str name="range">c5d10000-dd16ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node9">
<str name="state">active</str>
<str name="core">messages_shard4_replica1</str>
<str name="node_name">solr23-dcg:8983_solr</str>
<str name="base_url">http://solr23-dcg:8983/solr</str>
</lst>
<lst name="core_node15">
<str name="state">active</str>
<str name="core">messages_shard4_replica2</str>
<str name="node_name">solr23-gs:8983_solr</str>
<str name="base_url">http://solr23-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard5">
<str name="range">dd170000-f45cffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node3">
<str name="state">active</str>
<str name="core">messages_shard5_replica1</str>
<str name="node_name">solr24-dcg:8983_solr</str>
<str name="base_url">http://solr24-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node16">
<str name="state">recovering</str>
<str name="core">messages_shard5_replica2</str>
<str name="node_name">solr24-gs:8983_solr</str>
<str name="base_url">http://solr24-gs:8983/solr</str>
</lst>
</lst>
</lst>
<lst name="shard6">
<str name="range">f45d0000-ba1ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node4">
<str name="state">active</str>
<str name="core">messages_shard6_replica1</str>
<str name="node_name">solr25-dcg:8983_solr</str>
<str name="base_url">http://solr25-dcg:8983/solr</str>
</lst>
<lst name="core_node17">
<str name="state">active</str>
<str name="core">messages_shard6_replica2</str>
<str name="node_name">solr25-gs:8983_solr</str>
<str name="base_url">http://solr25-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard7">
<str name="range">ba20000-22e7ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node7">
<str name="state">active</str>
<str name="core">messages_shard7_replica1</str>
<str name="node_name">solr26-dcg:8983_solr</str>
<str name="base_url">http://solr26-dcg:8983/solr</str>
</lst>
<lst name="core_node18">
<str name="state">active</str>
<str name="core">messages_shard7_replica2</str>
<str name="node_name">solr26-gs:8983_solr</str>
<str name="base_url">http://solr26-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard8">
<str name="range">22e80000-3a2dffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node8">
<str name="state">active</str>
<str name="core">messages_shard8_replica1</str>
<str name="node_name">solr27-dcg:8983_solr</str>
<str name="base_url">http://solr27-dcg:8983/solr</str>
</lst>
<lst name="core_node19">
<str name="state">active</str>
<str name="core">messages_shard8_replica2</str>
<str name="node_name">solr27-gs:8983_solr</str>
<str name="base_url">http://solr27-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard9">
<str name="range">3a2e0000-5173ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node11">
<str name="state">active</str>
<str name="core">messages_shard9_replica1</str>
<str name="node_name">solr28-dcg:8983_solr</str>
<str name="base_url">http://solr28-dcg:8983/solr</str>
</lst>
<lst name="core_node20">
<str name="state">active</str>
<str name="core">messages_shard9_replica2</str>
<str name="node_name">solr28-gs:8983_solr</str>
<str name="base_url">http://solr28-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard10">
<str name="range">51740000-68b9ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node10">
<str name="state">active</str>
<str name="core">messages_shard10_replica1</str>
<str name="node_name">solr29-dcg:8983_solr</str>
<str name="base_url">http://solr29-dcg:8983/solr</str>
</lst>
<lst name="core_node21">
<str name="state">active</str>
<str name="core">messages_shard10_replica2</str>
<str name="node_name">solr29-gs:8983_solr</str>
<str name="base_url">http://solr29-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard11">
<str name="range">68ba0000-7fffffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node6">
<str name="state">active</str>
<str name="core">messages_shard11_replica1</str>
<str name="node_name">solr30-dcg:8983_solr</str>
<str name="base_url">http://solr30-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node22">
<str name="state">recovering</str>
<str name="core">messages_shard11_replica2</str>
<str name="node_name">solr30-gs:8983_solr</str>
<str name="base_url">http://solr30-gs:8983/solr</str>
</lst>
</lst>
</lst>
</lst>
<str name="maxShardsPerNode">1</str>
<lst name="router">
<str name="name">compositeId</str>
</lst>
<str name="replicationFactor">1</str>
<str name="autoAddReplicas">false</str>
<arr name="aliases">
<str>smsc</str>
</arr>
<str name="configName">messages</str>
</lst>
<lst name="intradesk">
<lst name="shards">
<lst name="shard1">
<str name="range">80000000-9744ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node5">
<str name="state">active</str>
<str name="core">intradesk_shard1_replica1</str>
<str name="node_name">solr20-dcg:8983_solr</str>
<str name="base_url">http://solr20-dcg:8983/solr</str>
</lst>
<lst name="core_node22">
<str name="state">active</str>
<str name="core">intradesk_shard1_replica2</str>
<str name="node_name">solr20-gs:8983_solr</str>
<str name="base_url">http://solr20-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard2">
<str name="range">97450000-ae8affff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node7">
<str name="state">active</str>
<str name="core">intradesk_shard2_replica1</str>
<str name="node_name">solr21-dcg:8983_solr</str>
<str name="base_url">http://solr21-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node21">
<str name="state">active</str>
<str name="core">intradesk_shard2_replica2</str>
<str name="node_name">solr21-gs:8983_solr</str>
<str name="base_url">http://solr21-gs:8983/solr</str>
</lst>
</lst>
</lst>
<lst name="shard3">
<str name="range">ae8b0000-c5d0ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node9">
<str name="state">active</str>
<str name="core">intradesk_shard3_replica1</str>
<str name="node_name">solr22-dcg:8983_solr</str>
<str name="base_url">http://solr22-dcg:8983/solr</str>
</lst>
<lst name="core_node20">
<str name="state">active</str>
<str name="core">intradesk_shard3_replica2</str>
<str name="node_name">solr22-gs:8983_solr</str>
<str name="base_url">http://solr22-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard4">
<str name="range">c5d10000-dd16ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node6">
<str name="state">active</str>
<str name="core">intradesk_shard4_replica1</str>
<str name="node_name">solr23-dcg:8983_solr</str>
<str name="base_url">http://solr23-dcg:8983/solr</str>
</lst>
<lst name="core_node19">
<str name="state">active</str>
<str name="core">intradesk_shard4_replica2</str>
<str name="node_name">solr23-gs:8983_solr</str>
<str name="base_url">http://solr23-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard5">
<str name="range">dd170000-f45cffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node1">
<str name="state">active</str>
<str name="core">intradesk_shard5_replica1</str>
<str name="node_name">solr24-dcg:8983_solr</str>
<str name="base_url">http://solr24-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node18">
<str name="state">active</str>
<str name="core">intradesk_shard5_replica2</str>
<str name="node_name">solr24-gs:8983_solr</str>
<str name="base_url">http://solr24-gs:8983/solr</str>
</lst>
</lst>
</lst>
<lst name="shard6">
<str name="range">f45d0000-ba1ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node10">
<str name="state">active</str>
<str name="core">intradesk_shard6_replica1</str>
<str name="node_name">solr25-dcg:8983_solr</str>
<str name="base_url">http://solr25-dcg:8983/solr</str>
</lst>
<lst name="core_node17">
<str name="state">active</str>
<str name="core">intradesk_shard6_replica2</str>
<str name="node_name">solr25-gs:8983_solr</str>
<str name="base_url">http://solr25-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard7">
<str name="range">ba20000-22e7ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node8">
<str name="state">active</str>
<str name="core">intradesk_shard7_replica1</str>
<str name="node_name">solr26-dcg:8983_solr</str>
<str name="base_url">http://solr26-dcg:8983/solr</str>
</lst>
<lst name="core_node16">
<str name="state">active</str>
<str name="core">intradesk_shard7_replica2</str>
<str name="node_name">solr26-gs:8983_solr</str>
<str name="base_url">http://solr26-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard8">
<str name="range">22e80000-3a2dffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node4">
<str name="state">active</str>
<str name="core">intradesk_shard8_replica1</str>
<str name="node_name">solr27-dcg:8983_solr</str>
<str name="base_url">http://solr27-dcg:8983/solr</str>
</lst>
<lst name="core_node15">
<str name="state">active</str>
<str name="core">intradesk_shard8_replica2</str>
<str name="node_name">solr27-gs:8983_solr</str>
<str name="base_url">http://solr27-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard9">
<str name="range">3a2e0000-5173ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node2">
<str name="state">active</str>
<str name="core">intradesk_shard9_replica1</str>
<str name="node_name">solr28-dcg:8983_solr</str>
<str name="base_url">http://solr28-dcg:8983/solr</str>
</lst>
<lst name="core_node14">
<str name="state">active</str>
<str name="core">intradesk_shard9_replica2</str>
<str name="node_name">solr28-gs:8983_solr</str>
<str name="base_url">http://solr28-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard10">
<str name="range">51740000-68b9ffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node3">
<str name="state">active</str>
<str name="core">intradesk_shard10_replica1</str>
<str name="node_name">solr29-dcg:8983_solr</str>
<str name="base_url">http://solr29-dcg:8983/solr</str>
</lst>
<lst name="core_node13">
<str name="state">active</str>
<str name="core">intradesk_shard10_replica2</str>
<str name="node_name">solr29-gs:8983_solr</str>
<str name="base_url">http://solr29-gs:8983/solr</str>
<str name="leader">true</str>
</lst>
</lst>
</lst>
<lst name="shard11">
<str name="range">68ba0000-7fffffff</str>
<str name="state">active</str>
<lst name="replicas">
<lst name="core_node11">
<str name="state">active</str>
<str name="core">intradesk_shard11_replica1</str>
<str name="node_name">solr30-dcg:8983_solr</str>
<str name="base_url">http://solr30-dcg:8983/solr</str>
<str name="leader">true</str>
</lst>
<lst name="core_node12">
<str name="state">active</str>
<str name="core">intradesk_shard11_replica2</str>
<str name="node_name">solr30-gs:8983_solr</str>
<str name="base_url">http://solr30-gs:8983/solr</str>
</lst>
</lst>
</lst>
</lst>
<str name="maxShardsPerNode">1</str>
<lst name="router">
<str name="name">compositeId</str>
</lst>
<str name="replicationFactor">1</str>
<str name="autoAddReplicas">false</str>
<arr name="aliases">
<str>smsc</str>
</arr>
<str name="configName">intradesk</str>
</lst>
</lst>
<lst name="aliases">
<str name="smsc">messages,intradesk,lvs</str>
</lst>
<arr name="live_nodes">
<str>solr27-gs:8983_solr</str>
<str>solr24-dcg:8983_solr</str>
<str>solr21-gs:8983_solr</str>
<str>solr29-dcg:8983_solr</str>
<str>solr28-gs:8983_solr</str>
<str>solr26-dcg:8983_solr</str>
<str>solr30-dcg:8983_solr</str>
<str>solr25-dcg:8983_solr</str>
<str>solr22-dcg:8983_solr</str>
<str>solr30-gs:8983_solr</str>
<str>solr25-gs:8983_solr</str>
<str>solr22-gs:8983_solr</str>
<str>solr23-gs:8983_solr</str>
<str>solr20-dcg:8983_solr</str>
<str>solr29-gs:8983_solr</str>
<str>solr23-dcg:8983_solr</str>
<str>solr28-dcg:8983_solr</str>
<str>solr20-gs:8983_solr</str>
<str>solr27-dcg:8983_solr</str>
<str>solr26-gs:8983_solr</str>
<str>solr21-dcg:8983_solr</str>
<str>solr24-gs:8983_solr</str>
</arr>
</lst>
</response>

So it should report "recovering" instead

**Comment by harisekhon** [comment]
@arkadicolson 

Technically this is correct, one of the shard replicas is not 'active' and regardless it should be a warning state since your cluster is running degraded during this time.

I could extend it to print that the replica is in 'recovering' mode after the shard name if that would be better?

**Comment by arkadicolson** [comment]
@harisekhon 
It would be great to have the actual state from the clusterstatus xml output (recovering in this case) in the output message. The warning status is indeed correct.
Thanks!

**Comment by harisekhon** [comment]
I think the reason I didn't do this originally was because the output could become very very long if several shards are down at once and there is a character limit in Nagios, which will end up not passing through the perfdata

**Comment by HariSekhon** [comment]
I'm going to close this as adding the extra information could break the Nagios character limit and chop off the perfdata from being interpreted, effectively blanking out your graph data for these periods.

Please re-open if necessary if you have any more input around this that would allow it to be implemented without breaking the character limit. For a quick bit of the extra detail you can always run with -vvv on the command line, I use these tools as cli testers too.
