### ISSUE TITLE
check_linux_timezone.pl support for RHEL7/CentOS7

### ISSUE THREAD

**Issue by petegallagher** [harisekhon/nagios-plugins#66]
There have been changes in behaviour of the timezone files moving to RHEL7/CentOS7. 

1. The file `/etc/sysconfig/clock` no longer exists. In fact from what I can tell this should never have been used in the first place e.g. [489586](https://bugzilla.redhat.com/show_bug.cgi?id=489586#c1) and from `/etc/sysconfig/clock`:

    ```
    # The time zone of the system is defined by the contents of /etc/localtime.
    # This file is only for evaluation by system-config-date, do not rely on its
    # contents elsewhere.
    ```

2. The file `/etc/localtime` is now expected to be a symlink, so throwing a warning here is detrimental.

**Comment by harisekhon** [comment]
Thanks for raising this.

I've commented out the sysconfig check. The symlink check could have been disabled by the command line switch but I've commented this out entirely now as it doesn't add much.
