### ISSUE TITLE
Issue with check_hadoop_datanode_blockcount.pl

### ISSUE THREAD

**Issue by shahrukhkhan489** [harisekhon/nagios-plugins#67]
# ./check_hadoop_datanode_blockcount.pl -H 10.200.99.103 -vvv
verbose mode on

check_hadoop_datanode_blockcount.pl version 0.3  =>  Hari Sekhon Utils version 1.16.2

host:                     10.200.99.103
port:                     50075
warning  upper:           300000
critical upper:           500000

setting timeout to 10 secs

setting http per request timeout to 9.00 secs

querying datanode 10.200.99.103
HTTP GET http://10.200.99.103:50075/blockScannerReport
returned HTML:

Periodic block scanner is not running. Please check the datanode log if this is unexpected.

http status code:     200
http status message:  OK

CRITICAL: failed to find total block count from blockScannerReport, Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

**Comment by harisekhon** [comment]
This isn't a fault of the plugin, the block scanner itself isn't running. If you git pull the latest version that I've just pushed it should raise the real issue more clearly.

What you need to do is check the datanode's log and configuration for why the periodic block scanner isn't running.

**Comment by harisekhon** [comment]
@shahrukhkhan489 

Were you able to check your datanode config + log to find out why the blockscanner wasn't running?

You probably have dfs.block.scanner.volume.bytes.per.second = 0 in your hdfs-site.xml.

**Comment by harisekhon** [comment]
I've added a note to the output when this is encountered to check for that setting in your hdfs-site.xml but since is beyond the scope of this program to deal with I'm going to close this ticket unless you can tell me of something you think the program should do about this.
