### ISSUE TITLE
Question about check_mysql

### ISSUE THREAD

**Issue by rduffner** [harisekhon/nagios-plugins#68]
Hi, 
I'm trying to use your plugin, but it does not work:

--- 
./c-m.pl -vv -u our_user -p our_pass --database=the_database -s /tmp/mysql.sock -q "select export_status from nt_nameserver where nt_nameserver_id='1'" -r error -v 
verbose mode on

c-m.pl version 1.1.3  =>  Hari Sekhon Utils version 1.15.7

mysql socket:             /tmp/mysql.sock
user:                     our_user
password:                 <omitted>
database:                 the_database
query:                    select export_status from nt_nameserver where nt_nameserver_id='1'
field:                    1
regex:                    (?^:error)

setting timeout to 10 secs

connecting to MySQL database via socket '/tmp/mysql.sock'

login to database successful

query: select export_status from nt_nameserver where nt_nameserver_id='1'
CRITICAL: Couldn't execute query: No database selected ("select export_status from nt_nameserver where nt_nameserver_id='1'")
--- 
(not sure why it capitalizes the above)

it keeps telling me I don't have selected a database, even though it prints said database just above.

This is on FreeBSD 10.1, with MariaDB 5.5

The "official" plugin can't check for a string in the result, just a number.

Do you have an idea about what I'm doing wrong here?

**Comment by harisekhon** [comment]
@rduffner kk this was a legit bug when using a default local unix socket to connect to MySQL that I've just fixed and written tests for.

The more common way of calling this plugin is actually using ```-H server``` to specify a remote MySQL database to query in which case the TCP connection would have passed the database through. It would also have worked if fully qualifying the table with the database in the query.

If you git pull the latest version it's fixed now. I'll close this ticket, but feel free to re-open it if this doesn't solve your issue.
