### ISSUE TITLE
check_spark_cluster_memory.pl - failed to determine spark cluster memory

### ISSUE THREAD

**Issue by sourabhniyogi** [harisekhon/nagios-plugins#70]
Hi,

I'm getting the following error while running this:

perl -T check_spark_cluster_memory.pl -H serv_name -w 1 -c 2

UNKNOWN: failed to determine spark cluster memory. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

Even though I downloaded the plugin from https://github.com/harisekhon/nagios-plugins.

perl -T check_spark_cluster_memory.pl -H ha202 -w 1 -c 2 -vvv
verbose mode on

check_spark_cluster_memory.pl version 0.1  =>  Hari Sekhon Utils version 1.8.21

host:                     server_name
port:                     8080
warning  upper:           1
critical upper:           2

setting timeout to 10 secs

querying Spark Master
HTTP GET http://ha202:8080
returned HTML:

<!DOCTYPE html><html>
      <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8"/><link rel="stylesheet" href="/static/bootstrap.min.css" type="text/css"/><link rel="stylesheet" href="/static/vis.min.css" type="text/css"/><link rel="stylesheet" href="/static/webui.css" type="text/css"/><link rel="stylesheet" href="/static/timeline-view.css" type="text/css"/><script src="/static/sorttable.js"></script><script src="/static/jquery-1.11.1.min.js"></script><script src="/static/vis.min.js"></script><script src="/static/bootstrap-tooltip.js"></script><script src="/static/initialize-tooltips.js"></script><script src="/static/table.js"></script><script src="/static/additional-metrics.js"></script><script src="/static/timeline-view.js"></script>
        <title>Spark Master at spark://ha202.mdotm.com:7077</title>
      </head>
      <body>
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span12">
              <h3 style="vertical-align: middle; display: inline-block;">
                <a style="text-decoration: none" href="/">
                  <img src="/static/spark-logo-77x50px-hd.png"/>
                  <span class="version" style="margin-right: 15px;">1.5.0</span>
                </a>
                Spark Master at spark://ha202.mdotm.com:7077
              </h3>
            </div>
          </div>
          <div class="row-fluid">
          <div class="span12">
            <ul class="unstyled">
              <li><strong>URL:</strong> spark://ha202.mdotm.com:7077</li>
              <li>
                    <strong>REST URL:</strong> spark://ha202.mdotm.com:6066
                    <span class="rest-uri"> (cluster mode)</span>
                  </li>
              <li><strong>Alive Workers:</strong> 33</li>
              <li><strong>Cores in use:</strong> 132 Total,
                0 Used</li>
              <li><strong>Memory in use:</strong>
                792.0 GB Total,
                0.0 B Used</li>
              <li><strong>Applications:</strong>
                0 Running,
                37 Completed </li>
              <li><strong>Drivers:</strong>
                0 Running,
                0 Completed </li>
              <li><strong>Status:</strong> ALIVE</li>
            </ul>
          </div>
        </div><div class="row-fluid">
          <div class="span12">
            <h4> Workers </h4>
            <table class="table table-bordered table-condensed table-striped sortable">
      <thead><th width="" class="">Worker Id</th><th width="" class="">Address</th><th width="" class="">State</th><th width="" class="">Cores</th><th width="" class="">Memory</th></thead>
      <tbody>
        <tr>
      <td>
        <a href="http://ha203sp:8081">worker-20151109171140-10.106.169.9-55649</a>
      </td>
      <td>10.106.169.9:55649</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha205sp:8081">worker-20151109171141-10.106.169.7-50152</a>
      </td>
      <td>10.106.169.7:50152</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha204sp:8081">worker-20151109171143-10.106.169.16-36502</a>
      </td>
      <td>10.106.169.16:36502</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha207sp:8081">worker-20151109191139-10.143.162.110-45160</a>
      </td>
      <td>10.143.162.110:45160</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha219sp:8081">worker-20151109191140-10.143.162.71-40285</a>
      </td>
      <td>10.143.162.71:40285</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha233sp:8081">worker-20151109191140-10.37.150.40-38104</a>
      </td>
      <td>10.37.150.40:38104</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha220sp:8081">worker-20151109191141-10.143.162.115-46569</a>
      </td>
      <td>10.143.162.115:46569</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha208sp:8081">worker-20151109191141-10.143.162.68-60955</a>
      </td>
      <td>10.143.162.68:60955</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha217sp:8081">worker-20151109191141-10.16.100.233-52513</a>
      </td>
      <td>10.16.100.233:52513</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha234sp:8081">worker-20151109191141-10.37.150.36-49948</a>
      </td>
      <td>10.37.150.36:49948</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha235sp:8081">worker-20151109191141-10.37.150.4-56443</a>
      </td>
      <td>10.37.150.4:56443</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha213sp:8081">worker-20151109191141-10.37.150.49-34915</a>
      </td>
      <td>10.37.150.49:34915</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha211sp:8081">worker-20151109191141-10.37.150.54-51310</a>
      </td>
      <td>10.37.150.54:51310</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha214sp:8081">worker-20151109191141-10.37.150.61-46182</a>
      </td>
      <td>10.37.150.61:46182</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha223sp:8081">worker-20151109191141-10.61.191.13-57375</a>
      </td>
      <td>10.61.191.13:57375</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha225sp:8081">worker-20151109191141-10.61.191.89-60442</a>
      </td>
      <td>10.61.191.89:60442</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha229sp:8081">worker-20151109191141-10.84.51.12-45291</a>
      </td>
      <td>10.84.51.12:45291</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha232sp:8081">worker-20151109191141-10.84.51.22-44581</a>
      </td>
      <td>10.84.51.22:44581</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha228sp:8081">worker-20151109191141-10.84.51.44-36814</a>
      </td>
      <td>10.84.51.44:36814</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha227sp:8081">worker-20151109191141-10.84.51.5-36990</a>
      </td>
      <td>10.84.51.5:36990</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha206sp:8081">worker-20151109191142-10.143.162.103-54081</a>
      </td>
      <td>10.143.162.103:54081</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha221sp:8081">worker-20151109191142-10.143.162.105-47332</a>
      </td>
      <td>10.143.162.105:47332</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha222sp:8081">worker-20151109191142-10.143.162.89-46732</a>
      </td>
      <td>10.143.162.89:46732</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha218sp:8081">worker-20151109191142-10.16.100.220-36670</a>
      </td>
      <td>10.16.100.220:36670</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha209sp:8081">worker-20151109191142-10.37.150.29-35989</a>
      </td>
      <td>10.37.150.29:35989</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha215sp:8081">worker-20151109191142-10.37.150.3-52047</a>
      </td>
      <td>10.37.150.3:52047</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha230sp:8081">worker-20151109191142-10.84.51.54-50532</a>
      </td>
      <td>10.84.51.54:50532</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha231sp:8081">worker-20151109191142-10.84.81.169-38085</a>
      </td>
      <td>10.84.81.169:38085</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha216sp:8081">worker-20151109191142-10.9.148.194-60391</a>
      </td>
      <td>10.9.148.194:60391</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha212sp:8081">worker-20151109191143-10.37.150.15-57215</a>
      </td>
      <td>10.37.150.15:57215</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha224sp:8081">worker-20151109191143-10.61.191.30-39664</a>
      </td>
      <td>10.61.191.30:39664</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha226sp:8081">worker-20151109191143-10.84.76.249-34451</a>
      </td>
      <td>10.84.76.249:34451</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr><tr>
      <td>
        <a href="http://ha210sp:8081">worker-20151109191145-10.37.150.5-44450</a>
      </td>
      <td>10.37.150.5:44450</td>
      <td>ALIVE</td>
      <td>4 (0 Used)</td>
      <td sorttable_customkey="24576.0">
        24.0 GB
        (0.0 B Used)
      </td>
    </tr>
      </tbody>
    </table>
          </div>
        </div><div class="row-fluid">
          <div class="span12">
            <h4> Running Applications </h4>
            <table class="table table-bordered table-condensed table-striped sortable">
      <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Node</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
      <tbody>
        
      </tbody>
    </table>
          </div>
        </div><div>
          
        </div><div class="row-fluid">
          <div class="span12">
            <h4> Completed Applications </h4>
            <table class="table table-bordered table-condensed table-striped sortable">
      <thead><th width="" class="">Application ID</th><th width="" class="">Name</th><th width="" class="">Cores</th><th width="" class="">Memory per Node</th><th width="" class="">Submitted Time</th><th width="" class="">User</th><th width="" class="">State</th><th width="" class="">Duration</th></thead>
      <tbody>
        <tr>
      <td>
        <a href="app?appId=app-20151109174205-0036">app-20151109174205-0036</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:42:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>27 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109174105-0035">app-20151109174105-0035</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:41:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>24 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109174006-0033">app-20151109174006-0033</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:40:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>31 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109174007-0034">app-20151109174007-0034</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:40:07</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>15 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173906-0032">app-20151109173906-0032</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:39:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>20 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173805-0031">app-20151109173805-0031</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:38:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>25 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173706-0030">app-20151109173706-0030</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:37:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>26 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173603-0029">app-20151109173603-0029</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:36:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173504-0028">app-20151109173504-0028</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:35:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>15 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173504-0027">app-20151109173504-0027</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:35:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>9 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173404-0026">app-20151109173404-0026</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:34:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173303-0025">app-20151109173303-0025</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:33:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>1 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173204-0024">app-20151109173204-0024</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:32:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173103-0023">app-20151109173103-0023</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:31:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173004-0021">app-20151109173004-0021</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:30:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>16 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109173004-0022">app-20151109173004-0022</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:30:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>15 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172902-0020">app-20151109172902-0020</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:29:02</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>15 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172804-0019">app-20151109172804-0019</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:28:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172703-0018">app-20151109172703-0018</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:27:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172603-0017">app-20151109172603-0017</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:26:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172506-0015">app-20151109172506-0015</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:25:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>22 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172508-0016">app-20151109172508-0016</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:25:08</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>13 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172405-0014">app-20151109172405-0014</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:24:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>18 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172303-0013">app-20151109172303-0013</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:23:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>0.9 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172203-0012">app-20151109172203-0012</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:22:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172103-0011">app-20151109172103-0011</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:21:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172006-0009">app-20151109172006-0009</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:20:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109172006-0010">app-20151109172006-0010</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:20:06</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>9 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171903-0008">app-20151109171903-0008</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:19:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171804-0007">app-20151109171804-0007</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:18:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>16 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171703-0006">app-20151109171703-0006</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:17:03</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>15 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171604-0005">app-20151109171604-0005</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:16:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>19 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171505-0003">app-20151109171505-0003</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:15:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171505-0004">app-20151109171505-0004</a>
        
      </td>
      <td>
        <a href="/history/not-found">Pico</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:15:05</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>9 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171404-0002">app-20151109171404-0002</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:14:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>14 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171304-0001">app-20151109171304-0001</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:13:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>2 s</td>
    </tr><tr>
      <td>
        <a href="app?appId=app-20151109171204-0000">app-20151109171204-0000</a>
        
      </td>
      <td>
        <a href="/history/not-found">AdxRTF</a>
      </td>
      <td>
        20
      </td>
      <td sorttable_customkey="2048">
        2.0 GB
      </td>
      <td>2015/11/09 17:12:04</td>
      <td>root</td>
      <td>FINISHED</td>
      <td>18 s</td>
    </tr>
      </tbody>
    </table>
          </div>
        </div><div>
          
        </div>
        </div>
      </body>
    </html>

http status code:     200
http status message:  OK

UNKNOWN: failed to determine spark cluster memory. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

Thanks!
~anand

**Comment by harisekhon** [comment]
@sourabhniyogi 

I've just pushed updates for Spark 1.5.2, please run ```make update2``` and try again.

**Comment by harisekhon** [comment]
@sourabhniyogi 

Have you had a chance to try the updated Spark plugins?

**Comment by harisekhon** [comment]
This was fixed in testing so I'm going to close this ticket. If your problem persists you're free to re-open this.

Thanks

Hari
