### ISSUE TITLE
check_cloudera_manager_metrics.pl 

### ISSUE THREAD

**Issue by johnc10uk** [harisekhon/nagios-plugins#71]
Running OMD 1.30 and this check started failing 9th November 2015 after all the plugin files had auto updated in local/lib/nagios/plugins/ . Its doesn't like the "vlog_option" change and changing back to "vlog_options" it works normally.

./check_cloudera_manager_metrics.pl -H cm1 -u user1 -p pass1 -C "Cluster 1" -S hbase -m total_regions_across_regionservers
String found where operator expected at ./check_cloudera_manager_metrics.pl line 67, near "vlog_option "metrics""
        (Do you need to predeclare vlog_option?)
String found where operator expected at ./check_cloudera_manager_metrics.pl line 78, near "vlog_option "metrics""
        (Do you need to predeclare vlog_option?)
CRITICAL: syntax error at ./check_cloudera_manager_metrics.pl line 67, near "vlog_option "metrics""
syntax error at ./check_cloudera_manager_metrics.pl line 78, near "vlog_option "metrics""

Thanks, John.

**Comment by harisekhon** [comment]
@johnc10uk 

Did you run ```git pull``` instead of ```make update```?

**Comment by johnc10uk** [comment]
My auto script does 

  git clone https://github.com/harisekhon/nagios-plugins.git
  cd /tmp/nagios-plugins
  git submodule init
  git submodule update

Then I move them to the plugins folder.

**Comment by harisekhon** [comment]
Ok perhaps the corresponding changes weren't pushed to github, I'll check this when I get home in a couple hours and push the required changes.

**Comment by johnc10uk** [comment]
Great, thanks.

**Comment by harisekhon** [comment]
I've checked and double checked this and it works fine over here - the recent change is in line with the library submodule.

It looks like the library submodule hasn't been updated (and nor will it if you've changed anything in there).

Try this:
```
cd lib
git checkout master .
cd ..
git submodule update
```
and see if the problem goes away.

**Comment by johnc10uk** [comment]
Yes it was the lib directory not being updated properly by my script, nothing to do with your code. Now working correctly. Thanks, John.
