### ISSUE TITLE
check_whois.pl is not working well with .xyz TLD

### ISSUE THREAD

**Issue by zenkius** [harisekhon/nagios-plugins#72]
To solve please add "addPeriod" to valid_statuses in check_whois.pl to work well  with .xyz TLD.

**Comment by harisekhon** [comment]
@zenkius 

Thanks for raising a ticket. Can you please provide a bit more detail, with the ```-v -v -v``` output so I can see what's happening. You can use scrub.pl from my [Tools](https://github.com/harisekhon/tools) repo if you want to anonymize the output.

**Comment by zenkius** [comment]
When I exec:
check_whois.pl -H whois.nic.xyz -d abc.xyz

I get this error:
WARNING: invalid status 'addPeriod' found! 3413 days left for abc.xyz domain, expires '20-03-2025' | whois_query_time=0.3576s

I have solved adding "addPeriod" string to "valid_statuses" in "check_whois.pl" file.

**Comment by harisekhon** [comment]
Yes I realized just after I replied and hence the edit above, I've added it to valid statuses as well as several other possible status codes a doc on ICANN that I hadn't previously seen on all the many domains and registrars I used to monitor with this code. I'm going to close this ticket as this should now be resolved for you with the latest version.

**Comment by zenkius** [comment]
Thanks @harisekhon !
