### ISSUE TITLE
check_kafka.pl is not working

### ISSUE THREAD

**Issue by davidgarvey** [HariSekhon/nagios-plugins#73]
check_kafka.pl
CRITICAL: Can't locate auto/NetAddr/IP/InetBase/AF_INET6.al in @INC (@INC contains: ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/local/lib64/perl5/NetAddr/IP/InetBase.pm line 81.

Does anyone know what is causing this? I am installing on minimal centos 6.5.
[vagrant@vagrant-centos65 nagios-plugins]$ sudo /usr/local/bin/cpanm NetAddr::IP::InetBase
NetAddr::IP::InetBase is up to date. (0.08)
[vagrant@vagrant-centos65 nagios-plugins]$

I noticed this was failing. sudo required to install rpm.
$(SUDO) rpm -ivh "https://dl.fedoraproject.org/pub/epel/epel-release-latest-`awk '{print substr($$3, 0, 1); exit}' /etc/*release`.noarch.rpm" || :

**Comment by harisekhon** [comment]
@davidgarvey 

It looks like an upstream issue in the CPAN module rather than any change to the check_kaka.pl code. I suggest posting the issue against the NetAddr::IP::InetBase in CPAN.

On a minor side note I've added the missing sudo for epel direct rpm install in case running ```make``` as a normal user.

**Comment by hundredacres** [comment]
The following work around corrected the error for me -

In NetAddr/IP/InetBase.pm, add the following around line 10 -

use Socket;

Plugin works successfully then.

**Comment by HariSekhon** [comment]
@hundredacres 

That does seem to get past this autoload issue. I'll put it as a workaround on the README page:

https://github.com/HariSekhon/nagios-plugins#kafka-dependency-netaddripinetbase-autoload-bug

@davidgarvey 

I'm not sure there is much more I can do about this as it seems like an upstream issue so I'm going to close this issue for now. Feel free to re-open if needed.

Thanks

Hari
