### ISSUE TITLE
check_elasticsearch.pl is not working with elasticsearch (2.1.0)

### ISSUE THREAD

**Issue by abdelbassit** [harisekhon/nagios-plugins#76]
Hello,
The check_elasticsearch.pl seems it's not working with the new version of elasticsearch (2.1.0).
The error is:

UNKNOWN: 'status' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new

The verbos output is:

verbose mode on

check_elasticsearch.pl version 0.2 => Hari Sekhon Utils version 1.16.2

host: XX.XX.XX.XX
port: 9200

setting timeout to 10 secs

querying Elasticsearch
HTTP GET http://XX.XX.XX.XX:9200/?timeout=9&pretty=true
returned HTML:

{
"name" : "elasticserver",
"cluster_name" : "logs",
"version" : {
"number" : "2.1.0",
"build_hash" : "72cd1f1se3eee0957805e036106146dc1949dc5c",
"build_timestamp" : "2015-11-18T22:40:03Z",
"build_snapshot" : false,
"lucene_version" : "5.3.1"
},
"tagline" : "You Know, for Search"
}

http status code: 200
http status message: OK

Regards,

**Comment by abdelbassit** [comment]
The verbos output is:

verbose mode on

check_elasticsearch.pl version 0.2  =>  Hari Sekhon Utils version 1.16.2

host:                     XX.XX.XX.XX
port:                     9200

setting timeout to 10 secs

querying Elasticsearch
HTTP GET http://XX.XX.XX.XX:9200/?timeout=9&pretty=true
returned HTML:

{
  "name" : "elasticserver",
  "cluster_name" : "logs",
  "version" : {
    "number" : "2.1.0",
    "build_hash" : "72cd1f1a3eee09505e036106146dc1949dc5dc87",
    "build_timestamp" : "2015-11-18T22:40:03Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}


http status code:     200
http status message:  OK

**Comment by harisekhon** [comment]
@abdelbassit 

Thanks for raising this. I've just added a fix to make this field optional as it appears to have been removed in Elasticsearch 2.x. Please git pull and try again.

**Comment by abdelbassit** [comment]
Thank you very much harisekhon!!
Is working well now :) 

root@nagios:/# /elasticsearch/nagios-plugins/check_elasticsearch.pl -H 1.1.1.1
OK: cluster: 'logs', elasticsearch version: 2.1.0, lucene version: 5.3.1

**Comment by harisekhon** [comment]
Cool, thanks for confirming, I'll close this ticket.
