### ISSUE TITLE
make error building '_snappy' extension on CentOS 6.6

### ISSUE THREAD

**Issue by david-caldwell** [harisekhon/nagios-plugins#78]
Not sure if it is a 'file not found' error or a syntax error in the setup script.  Here is the output.

```
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c snappymodule.cc -o build/temp.linux-x86_64-2.6/snappymodule.o
  snappymodule.cc:31:22: error: snappy-c.h: No such file or directory
  snappymodule.cc:77: error: ‘snappy_status’ was not declared in this scope
  snappymodule.cc:78: error: expected ‘,’ or ‘;’ before ‘{’ token
  snappymodule.cc:45: warning: ‘_state’ defined but not used
  snappymodule.cc:56: warning: ‘SnappyCompressError’ defined but not used
  snappymodule.cc:57: warning: ‘SnappyUncompressError’ defined but not used
  snappymodule.cc:58: warning: ‘SnappyInvalidCompressedInputError’ defined but not used
  snappymodule.cc:59: warning: ‘SnappyCompressedLengthError’ defined but not used
  snappymodule.cc:77: warning: ‘snappy_strerror’ defined but not used
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-snappy
Failed to build python-snappy
Installing collected packages: python-snappy
  Running setup.py install for python-snappy
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-AkPXKj/python-snappy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-J2vwhi-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building '_snappy' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c snappymodule.cc -o build/temp.linux-x86_64-2.6/snappymodule.o
    snappymodule.cc:31:22: error: snappy-c.h: No such file or directory
    snappymodule.cc:77: error: ‘snappy_status’ was not declared in this scope
    snappymodule.cc:78: error: expected ‘,’ or ‘;’ before ‘{’ token
    snappymodule.cc:45: warning: ‘_state’ defined but not used
    snappymodule.cc:56: warning: ‘SnappyCompressError’ defined but not used
    snappymodule.cc:57: warning: ‘SnappyUncompressError’ defined but not used
    snappymodule.cc:58: warning: ‘SnappyInvalidCompressedInputError’ defined but not used
    snappymodule.cc:59: warning: ‘SnappyCompressedLengthError’ defined but not used
    snappymodule.cc:77: warning: ‘snappy_strerror’ defined but not used
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-AkPXKj/python-snappy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-J2vwhi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-AkPXKj/python-snappy
make: *** [make] Error 1
```

**Comment by harisekhon** [comment]
I built this on CentOS 6 + & + Ubuntu just this weekend... and it's run on continuous integration on Ubuntu... so the build should work, I've even tested it on bare bones docker containers. The error above implies that the snappy devel rpm isn't installed for the python pip installer to compile against.

What does ```rpm -q snappy-devel``` say?

**Comment by harisekhon** [comment]
I've tweaked the build to error out if the package install section fails as I suspect an earlier error was missed on package install. Please ```make update2; make``` and paste the results if the build fails again.

**Comment by david-caldwell** [comment]
Thank you for your response.

I spun up a new instance of 'CentOS release 6.6 (Final)' and received different error this time. 

One thing I wanted to clarify is, Should I be running the make command on a nagios server or client machine, or will a fresh clean machine do?

The output is attached.

I also saw your message about `make update2; make` and the output is in output-2.txt file.

[output.txt](https://github.com/harisekhon/nagios-plugins/files/47927/output.txt)
[output-2.txt](https://github.com/harisekhon/nagios-plugins/files/47934/output-2.txt)

**Comment by harisekhon** [comment]
A fresh machine would do, either way the build will install or build what's missing on RHEL or Debian based Linux systems. Git clone and run ```make``` on any machine you want to run these plugins on, via NRPE or whatever.

I've just done a new build from scratch on a bare bones CentOS 6.7 system and it didn't have this issue.

It's strange because if you look at the output it installs cpanm one command before, then the next command complains it can't find the cpanm command.

I wonder if you have a restricted $PATH or something? cpan installs cpanm to /usr/local/bin/cpanm... perhaps this is excluded from your $PATH environment variable or a restricted sudo setup that is restricting the $PATH to not include /usr/local/bin as per default?

I reproduced that error on a test system by removing /usr/local/bin from $PATH before running ```make```  and have just modified the build again to provide explicit paths to cpanm for those with restricted $PATH environment variables. Try ```make update2; make``` again.

**Comment by david-caldwell** [comment]
Build Successful!

Once I added the `/usr/local/bin` to the $PATH, it worked perfectly! Thank You for your help!

**Comment by harisekhon** [comment]
You're welcome, I'm trying to add the full path to the build to make this work regardless... it's a bit of a trade off because someone might not have cpanm installed to the standard place.

**Comment by david-caldwell** [comment]
I would leave it the way you had it. I think the problem was on my end with a custom AWS AMI that did not have the correct $PATH value.

**Comment by david-caldwell** [comment]
Having trouble getting some of the plugins to work.

```
./check_hbase_metrics.pl -H [IP_ADDRESS] -P 60010 -a -vvv

querying hadoop daemon :60010
HTTP GET http://[IP_ADDRESS]:60010/metrics?format=json
```
If I manually send a GET request to 
`http://[IP_ADDRESS]:60010/metrics?format=json` 
I get 
`CRITICAL: invalid json returned`

If I manually send a GET request to 
`http://[IP_ADDRESS]:60010/jmx` 
I get json back.

Here is my hbase version info.
```
HBase Version	0.98.4.2.2.6.0-2800-hadoop2, rbb78cdaa94c5a6e309f3bdaa83ce48b0365e21e0	HBase version and revision
```
Did the _URL_ change in this version?

i think the _URL_ to the metrics might be the key to getting some of the other plugins working.

**Comment by harisekhon** [comment]
@david-caldwell 

I'm going to track that in a separate issue which you can see the link to just above this comment. Please follow up there rather than chain too many issues in to the same ticket.

**Comment by david-caldwell** [comment]
ok, thanks
