### ISSUE TITLE
Missing SASL library header when building

### ISSUE THREAD

**Issue by pparkkin** [harisekhon/nagios-plugins#79]
When building I get this error

    sasl/saslwrapper.cpp:21:23: fatal error: sasl/sasl.h: No such file or directory

     #include <sasl/sasl.h>

Ubuntu 14.04.2 LTS

**Comment by harisekhon** [comment]
@pparkkin 

Looks like you're missing the sasl development libraries. Try

```apt-get install libsasl2-dev```

and then run make again.

**Comment by pparkkin** [comment]
That is what we're doing right now, and it works fine. Just wanted to report this to you in case you want to add it to your Makefile where you install dependencies, or the README.

**Comment by harisekhon** [comment]
I've added it to the list of deb packages, thanks.
