### ISSUE TITLE
Kerberos supported ?

### ISSUE THREAD

**Issue by Azef1** [HariSekhon/nagios-plugins#82]
Hi,

I use Kerberos for authentification and when i execute your scripts, i haven't results.
Did you support SPNEGO on your scripts ?
If no, do you know what is the best perl module to use SPNEGO ?

I have this problem on check_hadoop_yarn_metrics.pl

thx

**Comment by HariSekhon** [comment]
Kerberos support is implicitly supported via LWP if you have LWP::Authen::Negotiate cpan module installed which is in the list of modules installed by the Make build.

I've verified this with the webhdfs plugin on a kerberos secured cluster... I can't remember if the yarn metrics endpoint actually gets protected.

Can you please paste the full output of your run with -v -v -v ?

**Comment by HariSekhon** [comment]
@Azef1 

Did you get a chance to try using a local TGT and ensuring the LWP::Authen::Negotiate cpan module was installed?

Have you have a chance to re-run it with the full debug -v -v -v output yet?

**Comment by Azef1** [comment]
Hi,
I confirm you all is ok now. In fact, i had two problems:
- First, a problem with my certificat SSL (Crypt-SSLeay can't verify hostnames), so i resolved this, with this command `export PERL_LWP_SSL_VERIFY_HOSTNAME=0 `
- Secondly, my hadoop cluster use https and not http so i edited your scripts and add https.
So no problem with  Perl kerberos authentifiation .

Thank you very much for all.

**Comment by HariSekhon** [comment]
@Azef1 

Can you please let me know which scripts you edited, perhaps submit a pull request as I usually support SSL via an optional --ssl switch. If there are plugins where I haven't exposed the SSL switch I'm inclined to add it for everybody.

Thanks

Hari

**Comment by Azef1** [comment]
I tested this script: `check_hadoop_yarn_metrics.pl`
In some weeks i will test more scripts and i will do a list where i have some errors.

Thx

**Comment by Azef1** [comment]
Hi, 
You talked about to add an option --ssl. I've tested some checks and i provide you the first scripts where I added httpS:
- check_hadoop_namenode_heap.pl
- check_hadoop_replication.pl
- check_hadoop_yarn_app_stats.pl
- check_hadoop_yarn_metrics.pl
- check_hadoop_yarn_resource_manager_state.pl
- check_hbase_regionservers_jsp.pl
- check_hbase_regionservers.pl
- check_hadoop_yarn_resource_manager_heap.pl
- check_hadoop_yarn_queue_state.pl
- check_hadoop_yarn_queue_capacity.pl
- check_hadoop_yarn_node_manager_via_rm.pl
- check_hadoop_yarn_node_managers.pl
- check_hadoop_yarn_app_stats_queue.pl
- check_hadoop_yarn_apps_memory_used.pl

I have not tested all scripts.

Your scripts are a treasure !
