### ISSUE TITLE
check_solr_metrics.pl: allow underscore in stat names to extract

### ISSUE THREAD

**Issue by EC-jlopez** [HariSekhon/nagios-plugins#86]
I think there is a bug in check_solr_metrics.pl script. If stat param (-s / --stats) contains "_", i get an error "invalid stat defined: must be alphanumeric", so i can not monitor any 'cumulative' stats (i.e. 'cumulaitve_hits') from CACHE key.

Thx.

**Comment by HariSekhon** [comment]
I've just extended the validation check to allow underscores in stat names.

**Comment by EC-jlopez** [comment]
Thank you.  It works ok now.
