### ISSUE TITLE
check_solrcloud_cluster_status_zookeeper.pl - Not working with Solr 5/6

### ISSUE THREAD

**Issue by stefuNz** [HariSekhon/nagios-plugins#94]
Hey,

since Solr 5.x / 6.x does not store the node data in /clusterstate.json, the plugin is not working with those version. Are there plans to fix it?

**Comment by HariSekhon** [comment]
@stefuNz 

Thanks for raising this.

I will aim to provide an update but it might take 3-4 weeks for me to find the time for it as it's not just the update itself which is probably easy but I need to build additional functional tests for all the SolrCloud checks and I'm busy working on other right now.

**Comment by stefuNz** [comment]
Hey, thanks for the quick answer. I'm happy to test, once it's finished.

**Comment by HariSekhon** [comment]
@stefuNz 

I've just pushed updates for Solr 5/6 as well as some dockerized tests for these newer versions.

The tests are in ```tests/test_solrcloud.sh``` (non cloud mode tests are in ```tests/test_solr.sh```), although the Docker images may not be available on DockerHub just yet as they tend to sit in build queues for hours.

Hari
