### ISSUE TITLE
check_hbase_table*: Base class package "Class::Accessor" is empty

### ISSUE THREAD

**Issue by eLvErDe** [HariSekhon/nagios-plugins#96]
Hello,

When running these script I get this error:

> root@centreon:/tmp# /usr/lib/nagios/plugins/check_hbase_tables.pl --help
> CRITICAL: Base class package "Class::Accessor" is empty.
>     (Perhaps you need to 'use' the module which defines that package first,
>     or make that module available in @INC (@INC contains: /usr/lib/nagios-plugins-bigdata/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl).
>  at /usr/lib/nagios-plugins-bigdata/lib/Hbase/Types.pm line 12
> BEGIN failed--compilation aborted at /usr/lib/nagios-plugins-bigdata/lib/Hbase/Types.pm line 12.

The issue comes from lib/Hbase/Hbase.pm at line "use base qw(Class::Accessor);"

Does it makes sense to you ? Did I missed something while installing ? Can you explain me what this line means so I can tried to fix and provide a pull request ?

Best regards, Adam.

**Comment by eLvErDe** [comment]
Sorry, I just figured out:
http://search.cpan.org/~kasei/Class-Accessor-0.34/lib/Class/Accessor.pm

=> apt-get install libclass-accessor-perl

However the error message is very unusual for a Perl import issue, that's weird!

**Comment by HariSekhon** [comment]
Class::Accessor is actually in the list of CPAN modules to get pulled in as part of the build. Glad you solved it though, using the packaged cpan module is fine too.
